### ISSUE TITLE
Lag Spikes

### ISSUE THREAD

**Issue by umutcantkn** [DarkPacks/SkyFactory-4#1027]
Please help me! I can play with 80 75 fps around but after 30 minutes the lag spikes starts every 5 minute i get 1 fps. I closed fancy block it helped little bit 
I have rx570
8gb ram

**Comment by Darkosto** [comment]
Use these arguments when running the pack: http://bit.ly/DarkostoJavaArgs Your launcher should have a field to insert custom arguments. Outside of that, your PC may not be able to play the modpack without turning down your settings or upgrading your hardware.
