### ISSUE TITLE
NuclearCraft: cannot export spent fuel from fission reactor port

### ISSUE THREAD

**Issue by wcdanh2** [DarkPacks/SkyFactory-4#1042]
## Bug Report
Using itemducts with servos or item export cables form cyclic I cannot export items from a nuclearcraft fission reactor through the fission reactor ports. ( items are extract-able through the controller.)

## Expected Behaviour
Items should be export-able through the fission reactor port.

## Possible Solution
Update Nuclearcraft from 2.16 to 2.17, the Change log suggests it has been fixed.

## Steps to Reproduce (for bugs)
1. Build fission reactor and spend some fuel.
2. attach an itemduct with servo or cyclic Item extraction cable and pipe to a chest.
3. Spend fuel does not extract.

## Logs
No crash, so not needed?

## World Information

* Preset: skyblock

* Prestige: no

* Modpack Version world created in: 4.0.5

* Additional Content Installed: wireless crafting terminals, Just enough energistics, (including libraries needed for these.)

## Client Information

* Modpack Version:4.0.5
* Java Version:
* Launcher Used:multimc
* Memory Allocated:
* Server/LAN/Single Player: server
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:Ubuntu
* Hoster/Hosting Solution: 
* Sponge (Non-Vanilla Forge) Server:

**Comment by wcdanh2** [comment]
Addendum: I just tried a Thermal Dynamics Retriever and am able to extract items as a workaround to not being able to use servos.

**Comment by turbodiesel4598** [comment]
@wcdanh2 Could you try breaking and replacing the port? I did think I'd fixed that, but maybe not.

**Comment by wcdanh2** [comment]
I've tried several times. The pack is using version 2.16,and the change log for nuclear craft suggests the fix in in 2.17

**Comment by turbodiesel4598** [comment]
Sorry, misread the original post - I read update as 'updated', to I thought it was still not working after you'd tried 2.17 :P

Version 2.17a is already in the next build, so I guess just wait around a bit until its release :)

**Comment by wcdanh2** [comment]
Last I saw the update list showed that 2.16f was the upcoming version in the pack. I may not be seeing the right commit though.

**Comment by turbodiesel4598** [comment]
I think you're right, but that got updated again just the other day when Darko returned from Sweden :)
