### ISSUE TITLE
Sometimes I can hear some irrelevant random noises in the background

### ISSUE THREAD

**Issue by loliconxdd** [DarkPacks/SkyFactory-4#1050]
## Bug Report

Just now I don't remember I had some horses in my base or I just don't know I can hear some random noise made by horses or noises other than that such as some creepy laugh or some monster noises although there are none of them are around my base but my monster spawning area. 
## Expected Behaviour

There shouldn't be noises like that because those noises irritates or annoys me.
## Possible Solution

Huh?
## Steps to Reproduce (for bugs)

1. It just happens randomly
2. I just don't know why

## Logs

* Client/Server Log: https://gist.github.com/loliconxdd/a7f3bb89acbf4eb506db051c70f74815
* Crash Log: *It didn't crash it just some in game bugs*

## World Information

* Preset: Classic

* Prestige: No
 Latest version I guess...
* Modpack Version world created in: 22-05-2019

* Additional Content Installed: *none*

## Client Information

 
* Modpack Version: 
* Java Version: 1.8.0_211 64bit
* Launcher Used: AT Launcher 
* Memory Allocated: 85% 3433MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by uberfuzzy** [comment]
If you turn on sound subtitles, they show up as "Eerie noise", its just part of Minecraft since 1.9ish?
"Ambient" sounds like that just happen randomly.

**Comment by Darkosto** [comment]
It sounds like you have the hunting dimension portal close to where you're standing ingame. That portal will make mob sounds. Just turn down mob sounds or move the portal to a different location.
