### ISSUE TITLE
Filing cabinets not working in 4.0.6

### ISSUE THREAD

**Issue by TZ47** [DarkPacks/SkyFactory-4#1071]
## Bug Report
Filing cabinets from Real Filing Cabinets that were placed in the world before updating to 4.0.6 are not functioning with simple storage networks cables, or storage busses. When the folders are removed there is no tooltip saying what is in them. The folders can have items removed from them in a crafting table however.

## Expected Behaviour
They should work like normal

## Steps to Reproduce (for bugs)
1. I updated
2. I unlocked project e and the new parabox
3. I made patterns to autocraft 9 paraboxes
4. When trying to craft 9 paraboxes I noticed I was low on redstone acorns, only having 12
5. Looking at the filing cabinet it said I had ~113k of them
6. I made a simple storage network and it said I had 64 of all the materials in the filing cabinets and wouldn't let me remove them.

## World Information

* Preset: Default

* Prestige: YES! YES! YES!

* Modpack Version world created in: 4

* Additional Content Installed: Optifine and Builders wands

## Client Information

* Modpack Version:4.0.6
* Java Version: I'm not sure, but It should be the latest version
* Launcher Used: twitch
* Memory Allocated: 4G (~3060 mb)
* Server/LAN/Single Player: single player
* Optifine Installed: YES!
* Shaders Enabled:I'm not that fortunate

**Comment by cohan888** [comment]
Same Issue with 4.0.6. Encounted the Problem first with AE2 and Storage Bus to the Filing Cabinet. It limits each Folders content to 64 in the AE Crafting Terminal. Then I tried with Simple Storage, but there is the same behavior. In the Folder itself is the right content and with the Folder direct in Crafting Grid I can extract all Items. Its easy to reproduce: Put only more than 64 of the same Items in a Folder of a Filing Cabinet and check the AE Crafting Terminal or the Storage request Table.

**Comment by sk2048** [comment]
An update for Real Filing Cabinets has been released that should address this issue - it is v0.2.0.13. We are currently testing it to make sure there are no other issues with it.

For anyone looking to update, we recommend skipping 4.0.6 and waiting for 4.0.7 to release. If you already have 4.0.6, we recommend going back to 4.0.5 using a backup taken before updating. However, if you have made significant progress, you could try updating real filing cabinets.

**Comment by TZ47** [comment]
Updating Real Filing Cabinets makes a bug where some folders contain "Air" so I'm going to revert and wait for 4.0.7

**Comment by sk2048** [comment]
Reopening as issue is not yet addressed

**Comment by cohan888** [comment]
Yeah made a rollback to 4.0.5 at the moment. Thanks for reply. Wait then for 4.0.7.

**Comment by madokaorimura** [comment]
Have fix yet?

**Comment by RenaudGelai** [comment]
Problem with "air" items still there in 4.0.8

**Comment by RenaudGelai** [comment]
Update the cabinet mod fixes the problem
