### ISSUE TITLE
Advancement book outdated for tutorial mode

### ISSUE THREAD

**Issue by Calvinman** [DarkPacks/SkyFactory-4#1078]
If you choose Sky Factory Tutorial upon creating a new world, listed as having tutorial advancements to help new players out, the advancement book is missing links and intermediate steps that the normal Sky Factory 4 map type has.

**Comment by sk2048** [comment]
What do you feel is missing?

**Comment by Calvinman** [comment]
The parts that confused me personally were the parts that involved creating some of the saplings with molten metals since that part wasn't clear in the tutorial map, such as creating the amber and melting them. The advancement book in the default map is much more straightforward in my personal opinion.
