### ISSUE TITLE
Cannot trigger the Going on Your Permanent Record advancement

### ISSUE THREAD

**Issue by md5i** [DarkPacks/SkyFactory-4#1079]
# Problem

Right-clicking on a file cabinet with over one million items in its single folder does is not triggering the "Going on Your Permanent Record" advancement.

# Client Information
Modpack Version:4.0.7
Java Version: Java is OpenJDK 64-Bit Server VM, version 1.8.0_212, running on Linux:amd64:4.19.0-5-amd64, installed at /usr/lib/jvm/java-8-openjdk-amd64/jre
Launcher Used: MultiMC
Memory Allocated: 8G
Server/LAN/Single Player: single player
Optifine Installed: No
Shaders Enabled: None

**Comment by mkleiman312** [comment]
I have the same issue, but under 4.0.6.

**Comment by sk2048** [comment]
Given the changes to RFC, that advancement probably does need attention.

**Comment by Trashcant** [comment]
I have triggered this achievement with a fluid and it was way way faster.

**Comment by mkleiman312** [comment]
> I have triggered this achievement with a fluid and it was way way faster.

If you'd like to contribute to the thread, please at least include the pack version you used when you claim you triggered the achievement. Including the version of Real Filing Cabinets may also be useful.

**Comment by madokaorimura** [comment]
Right click on the Cabinet storage that File
Test it

**Comment by sk2048** [comment]
@madokaorimura This is an issue in 4.0.6 and above due to RFC being rewritten.

**Comment by SWampyG8r** [comment]
Still an issue in 4.0.8

**Comment by VasalisErretti** [comment]
Same here still and issue on 4.0.8 currently, please fix if you can, one of the few achievements I've got left

**Comment by dtroitskiy** [comment]
+1, last two advancements left, can't trigger this one.

**Comment by helpfulchicken** [comment]
Still an issue on pack version 4.1.0, can't trigger with cabinets full of acorns or resin.
