### ISSUE TITLE
Skipping Block Entity 

### ISSUE THREAD

**Issue by ZombieZohan** [DarkPacks/SkyFactory-4#1080]
hi,
i have an issue with Sky Factory 4. ive been playing this world for a few days now without a problem. now im getting a skipping block entity when starting the server.
the game loads for single player, but when i save the game for online server game play, the game loads but most the content failed to load. 

http://codepad.org/ykUCeKb0

**Comment by sk2048** [comment]
I'm struggling to understand your log, it looks like you've spliced the log of a vanilla server attempting to start a modded world in the middle of an SF4 client log. Follow the instructions to set up a modded server, and once you've got that working copy your world in.

**Comment by ZombieZohan** [comment]
Hi there...
That entire log was from a fresh twitch download and server pack download. I uninstalled everything, deleted everything and redownloaded just SF4 and still have the same problem... ive Not opened anything up from vanilla Minecraft, was all done through the twitch app. 

Sent from Mail for Windows 10

**Comment by sk2048** [comment]
How are you starting a server from the Twitch app?

Lines 338 - 440 come from a vanilla server. The rest of the log looks like a client log.

**Comment by ZombieZohan** [comment]
No from the server download pack SF4 offers in twitch. 

Sent from Mail for Windows 10

**Comment by ZombieZohan** [comment]
Im now deleting everything again and re downloading it again. 

Sent from Mail for Windows 10

**Comment by sk2048** [comment]
Okay, it sounds like you might be double clicking on `minecraft_server.1.12.2.jar` file, which launches a vanilla minecraft server.

Use the start script provided to launch a Forge modded server with the correct arguments.

**Comment by sk2048** [comment]
Please take follow up questions to https://discord.gg/darkosto `#sf4-server-support`

**Comment by ZombieZohan** [comment]
I think ive figured out the problem.  When you click on Forge and install client and server.  They don’t get added to that folder. It goes to my C:\Users\Home\AppData\Roaming\.minecraft  folder. The server file added to the SF4 instance you unpacked doesn’t get a working Minecraft 1.12.2 server file, there is another added to the roaming\.minecraft folder that allow the server to be loaded. 
The Forge universal also done the same, I copied and pasted both Jar files back to the SkyFactory twitch folder and ran the folders and seems to be working now.  thanks for your help tho. If you never made me remove everything and reinstall I wouldn’t of found this out. 

Sent from Mail for Windows 10
