### ISSUE TITLE
DupeBug: Real Filing Cabinet Folders (RFC issue or compat issue with SF4?)

### ISSUE THREAD

**Issue by remclave** [DarkPacks/SkyFactory-4#1081]
Place multiple folders in your personal crafting space. Place a single item with the folders, then pick up the resulting folders. You will now have 126 empty folders. Repeat with a new item. Before I realized what was occurring I had an inventory full of empty folders.

**Comment by Darkosto** [comment]
This was fixed in 4.0.7/4.0.8
