### ISSUE TITLE
I need help!!!

### ISSUE THREAD

**Issue by WitherOG** [DarkPacks/SkyFactory-4#1083]
## Bug Report
 I can not craft certain items in this game. The hopping bonsai are gone, and I go to make a tinkers smeltery and I can not make all of the pieces needed. I cant make the controller or the faucet or anything like that. Im not on prestige mode at all, just playing for the first time and am having a fun time as I have played the other skyfactory's. My only problem with this, is that I didn't realize this until after I had completed the first page of the achievement book. Please help me.

## Expected Behaviour
 Again I just cant craft some of the crucial things needed for this pack. And I see other people being able to craft them

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
 Skyfactory 4
* Preset:
 No
* Prestige: 
  4.0.5 1.12.2
* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by ktole1999** [comment]
the pack is based on achievements to open recipes. open achievement screen and see if you have unlocked that item

**Comment by WitherOG** [comment]
> the pack is based on achievements to open recipes. open achievement screen and see if you have unlocked that item

I have, you cant even find these items in the search bar of NEI on any of the maps ive created. I even opened a map in creative to search for them. Cant find them at all.

**Comment by MuteTiefling** [comment]
This really sounds like you've got prestige mode enabled.

**Comment by sk2048** [comment]
This sounds like you've started in prestige mode. What happens if you press `p`?

You should be able to give yourself all the gamestages that you would have if you weren't playing prestige by running the command `/function triumph:classic_mode`
