### ISSUE TITLE
Multiplayer and prestige

### ISSUE THREAD

**Issue by SigurdValiant** [DarkPacks/SkyFactory-4#1086]
Hello, since I installed my server, I did not find the prestige.cfg file so I created it and put it in the prestige folder. I have a friend who plays with me, he is not blocked to go into the twilight forest portal and can use ore excavation without putting prestige point.
I also can not allocate / worldspawn in dimensions, it changes them.
I have already read the guide on prestige that does not say where the .cfg is or how to create it. I have already forced prestige mode so everything works for my friend except that I wrote above. Thank you for giving precise help without referring to already existing data.

**Comment by sk2048** [comment]
`prestige.cfg` can be found in the `./config/` folder. It is **not** inside the prestige folder, which is where reward data is stored. To avoid any doubt, the file path is `./config/prestige.cfg`. You do not have to create it yourself, it already exists in the official server files.

You should make sure the settings are correct before you start playing, the easiest solution is to start again with Prestige properly enabled. As it stands, your friend started playing with prestige disabled and so has all the unlocks already.

**Comment by SigurdValiant** [comment]
Really thank you for this, i found it now, i hope it will arrange a lot of problems. thks
