### ISSUE TITLE
Core mods missing on install

### ISSUE THREAD

**Issue by mannermauler** [DarkPacks/SkyFactory-4#1090]
Hello, just downloaded this modpack (on the latest beta) and several core mods are missing, causing this screen to show: 
https://gyazo.com/1d36f32a5ccea9438866fbf4142ae853
https://gyazo.com/4969956fff4edeb594ce9e450caa22fc
https://gyazo.com/9c06a881ccd8467721115e5a01ee793e

Here's the log.
[latest (censored).txt](https://github.com/DarkPacks/SkyFactory-4/files/3298688/latest.censored.txt) (Replaced log with a version that has my name removed)

Missing dependencies:

- Placebo
- Cucumber
- Bookshelf
- Mysticalagriculture
- xnet
- opencomputers
- Valkyrielib
- cofhworld
- cofhcore
- waila

**Comment by mannermauler** [comment]
Missing dependencies:

- Placebo
- Cucumber
- Bookshelf
- Mysticalagriculture
- xnet
- opencomputers
- Valkyrielib
- cofhworld
- cofhcore
- waila

**Comment by sk2048** [comment]
Current release on the Twitch launcher seems fine to me, and we'd have got complaints prior to today if this was the case generally.

Delete the pack, or download it through MultiMC or the ATLauncher if this problem persists, but I doubt there is anything we can do to resolve this for you.
