### ISSUE TITLE
Advancements - Unbroken Lumber Axe

### ISSUE THREAD

**Issue by RayYung** [DarkPacks/SkyFactory-4#1093]
## Bug Report
I crafted an unbroken Lumber Axe and cut down a tree, it does NOT fulfill neither Unbroken nor Axe Me Anything 

## Expected Behaviour
crafting an unbroken Lumber Axe should fulfill Unbroken advancement and  shop down a tree should fulfill Axe Me Anything

## Possible Solution
Not Sure

## Steps to Reproduce (for bugs)
1. Craft a all paper Lumber Axe
2. add 5 reinforcement ( it became unbreakable)
3. Chop down a diamond tree

## Logs
Game continues, no log...

## World Information
* Preset: Material Girl in a Material World
* Prestige: No
* Modpack Version world created in: 4.0.5
* Additional Content Installed: None

* Modpack Version: 4.0.8
* Java Version: (build-in)
* Launcher Used: Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single player in LAN mode
* Optifine Installed: NO
* Shaders Enabled: NO

**Comment by RayYung** [comment]
Reload game and both advancement completed.......

**Comment by sk2048** [comment]
Sometimes Minecraft advancements stop updating until you relog, it's an unfortunate vanilla issue.
