### ISSUE TITLE
Bug. Lauch Game with new Update

### ISSUE THREAD

**Issue by nono11aj11** [DarkPacks/SkyFactory-4#1094]
Since I update, when I give to play from the AtLauncher does not start me gives this error in the console:
Error: Could not find or load main class net.minecraft.launchwrapper.Launch
(java is updated)
I have reinstalled to the previous version and it does not happen to me, it only happens with 4.0.8.
a greeting.

**Comment by madokaorimura** [comment]
Delete minecraft file (1.12.2)
delete modpack, then install again
if you can't
use another Launcher

**Comment by madokaorimura** [comment]
https://www.minecraftforum.net/forums/support/java-edition-support/2627598-could-not-find-or-load-main-class-net-minecraft

**Comment by CinnamonFreak** [comment]
You can install the 4.0.5 version and the 4.0.8 version together. Then copy the bin folder from the 4.0.5 version into the 4.0.8 version WITHOUT overwriting.

**Comment by sk2048** [comment]
This is not a pack issue, it is an issue with your launcher.
