### ISSUE TITLE
Update Mekanism to prevent turbine crash

### ISSUE THREAD

**Issue by i9hdkill** [DarkPacks/SkyFactory-4#1095]
See
https://github.com/mekanism/Mekanism/issues/5495
Fixed in 
https://minecraft.curseforge.com/projects/mekanism/files/2719846
and up

**Comment by madokaorimura** [comment]
Have updated yet?

**Comment by StephenLujan** [comment]
I just got this. It's rather annoying that I just spent the time and resources on a huge turbine, and now my world crashes on load unless I revert to a backup.

**Comment by sk2048** [comment]
I’m pretty sure this was resolved in 4.1.0, so you could always update.
