### ISSUE TITLE
This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 64578

### ISSUE THREAD

**Issue by dh47** [DarkPacks/SkyFactory-4#1098]
Having issues installing the new pack.

![image](https://user-images.githubusercontent.com/909007/59869257-fdb88400-93e6-11e9-94d5-9a75e8d02467.png)

**Comment by dh47** [comment]
This was an issue with my machine.  Sorry about that.

**Comment by Vasa-ctrl** [comment]
How did you fix

**Comment by sk2048** [comment]
It's not an issue with their machine, it's a really common curse/twitch issue. It will eventually fix itself, usually within an hour.
