### ISSUE TITLE
Parabox won't accept requested item

### ISSUE THREAD

**Issue by Benjamin-Berry** [DarkPacks/SkyFactory-4#1102]
4.0.8 

Parabox requested, Jungle Planks, Sandstone Slab, Emerald Nugget.
Using hopper it accepted the first two but not the nugget.

**Comment by sk2048** [comment]
Possibly it was requesting an emerald nugget that is unobtainable due to unification; this is another category of item we will need to investigate and blacklist.

**Comment by gaminggirl** [comment]
Parabox does not accept any of the 2 Fancy lamp that are in JEI
