### ISSUE TITLE
Items changing to 'Air' in File Cabinets from Real File Cabinets

### ISSUE THREAD

**Issue by Dominus787** [DarkPacks/SkyFactory-4#1103]
## Bug Report
Items in configured file folders (ie Iron Resin) inside File Cabinets are turned into item type 'Air' when connected to AE2 network. Crafting large amounts of items (ie 64 Iron Amber at a time using Shift + Click) using AE2 Crafting Terminal seems to be the trigger. Issue is Exacerbated when using an AE2 Molecular Assembler.

## Expected Behaviour
Items within file folders should remain the same type as the originally configured item.

## Possible Solution
None at this time.

## Setup for bug:
1.) File File Folders with 1K plus of each item (ie Iron Acorn, Iron Resin, etc).
2.) Have simple AE2 network with Crafting Terminal, single ME Interface connected to single Molecular Assembler. Molecular Assembler can have 0 - 4 acceleration cards.
3.) Have pattern for Iron Amber (or amber of choice)
4.) Connect File Cabinet to AE2 network using unconfigured Storage Bus.

## Steps to Reproduce Bug:

1.) Interact with ME Crafting Terminal
2.) Input recipe for Iron Amber.
3.) Autocraft 100+ Iron Resin using AE2 crafting terminal

## Logs

* Client/Server Log: https://gist.github.com/Dominus787/9040fbbfa7b9cb6836afa7fb88d9ae28

* Crash Log: N/A (no crash)

## World Information

* Preset:

* Prestige: None

* Modpack Version world created in: 4.0.8

* Additional Content Installed: None

## Client Information

* Modpack Version: 4.0.8
* Java Version: build 1.8.0_211-b12
* Launcher Used: Twitch Launcher version 8.0.0.0)
* Memory Allocated: 6037 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by aisair** [comment]
Someone in #1071 also mentioned this problem.

**Comment by JIMBLYB** [comment]
It doesn't fix the problem, but the simple storage network correctly reads the cabinet even if it shows air, and removing then replacing an item that was turned into air seems to make it recognisable in an applied energistics system, but does not fix the item in the filing cabinet itself.

**Comment by RenaudGelai** [comment]
Same issue here

**Comment by RenaudGelai** [comment]
> It doesn't fix the problem, but the simple storage network correctly reads the cabinet even if it shows air, and removing then replacing an item that was turned into air seems to make it recognisable in an applied energistics system, but does not fix the item in the filing cabinet itself.

would i have to do it repeatedly because the issue will happen again and so wait for a bugfix, or is it a one-time fix that allows me to continue playing without worrying ?

**Comment by RenaudGelai** [comment]
a working fix is to update the cabinets mod, it seems it is corrected, no more occurences of the problem appeared.

**Comment by SoulzBAen** [comment]
I had this issue and found in the /r forums a solution. Restore a previous backup to before the Air issue cropped up(no pun intended) and update the AE2 and Real Filing Cabinets. Then start it back up. Solution helped me quite a bit...now I just need to figure out why my Flux Networks won't interface with Integrated Dynamics anymore.

https://www.reddit.com/r/SkyFactory/comments/cquqog/sf4_bug_solution_real_filing_cabinet_items_turn/

**Comment by CyphixHL** [comment]
Just had this happen to me! :( Happened to all of my Cabinets.

**Comment by CyphixHL** [comment]
> 
> 
> I had this issue and found in the /r forums a solution. Restore a previous backup to before the Air issue cropped up(no pun intended) and update the AE2 and Real Filing Cabinets. Then start it back up. Solution helped me quite a bit...now I just need to figure out why my Flux Networks won't interface with Integrated Dynamics anymore.
> 
> https://www.reddit.com/r/SkyFactory/comments/cquqog/sf4_bug_solution_real_filing_cabinet_items_turn/

The problem with that is you lose all of your data that you worked on from that point of "air" forward. :(

**Comment by sam-kirby** [comment]
This issue is fixed in 4.1.0. Please update to prevent reoccurrence in the future. Restoring a backup is the only way to repopulate the contents of your storage.
