### ISSUE TITLE
地狱门点不燃

### ISSUE THREAD

**Issue by leeyf888** [DarkPacks/SkyFactory-4#1104]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by madokaorimura** [comment]
English please

**Comment by aisair** [comment]
Instead of the nether portal, you have to use the Nether Cake from Telepastries to get to the nether.

**Comment by leeyf888** [comment]
> English please
i m sorry .i am chinese. 我就要说中文

**Comment by leeyf888** [comment]
> Instead of the nether portal, you have to use the Nether Cake from Telepastries to get to the nether.

OK ，i get it.
