### ISSUE TITLE
Cyclic milk fluid has no texture and doesn't show recipes in JEI

### ISSUE THREAD

**Issue by Blaster84x** [DarkPacks/SkyFactory-4#1105]
## Bug Report

The cauldron recipe for Blue Slime Sapling is showing a milk fluid with a missing texture from Cyclic, which is apparently uncraftable. This makes the blue slime sapling (and slime as a result) unobtainable at least in early game.

## Expected Behaviour

The expected behavior is for the recipe to use an obtainable fluid, like the other Cyclic one.

## Possible Solution

Use CraftTweaker to point the recipe to the functional Cyclic milk or a new fluid created with ContentTweaker. Then create a cauldron or TiCon recipe for the milk.

## Steps to Reproduce (for bugs)

1. Left click on the Blue Slime Sapling model in the JEI interface
2. Click on the fluid shown in the recipe OR any of the missing textures shown when searching for "milk" in JEI.
3. See that nothing happens, meaning the fluid is unobtainable.

## Logs

* Client/Server Log: https://gist.github.com/Blaster84x/85e68f2b47060f4f7ba17768498a02a5
* Crash Log:

## World Information

* Preset: classic (dirt block)

* Prestige: false

* Modpack Version world created in: 4.0.7

* Additional Content Installed: None (ItemPhysic Lite installed before, uninstalling didn't affect this bug)

## Client Information

* Modpack Version: 4.0.8
* Java Version: 1.8.0.51 (64 bit)
* Launcher Used: Twitch
* Memory Allocated: 4608 MB
* Server/LAN/Single Player: singleplayer
* Optifine Installed: false
* Shaders Enabled: false

**Comment by aisair** [comment]
The Cyclic milk can be obtained from vanilla methods, like milking cows.

**Comment by Blaster84x** [comment]
But the one in the recipe is the *wrong* Cyclic milk. It has a missing texture and is only used in one recipe.

**Comment by sk2048** [comment]
When you right click the cauldron with a bucket of milk, its internal state becomes `state:{fluid:"milk"}`, the texture it displays is visual only. All the recipe cares about is that it thinks it is milk, and it does.

The recipe still works.

I believe Cyclic needs to update to fix the visual issue.

**Comment by Blaster84x** [comment]
@sk2048 A temporary workaround would be to change the milk's texture with Resource Loader, until the Cyclic dev fixes it himself.
