### ISSUE TITLE
Cannot play coop in CompactSky world

### ISSUE THREAD

**Issue by Foxdemon** [DarkPacks/SkyFactory-4#1106]
**Bug Report**
As the title says you can't join another persons compact machine to play coop. It says that you don't have permission to join another compact machine.

**Possible Solution**
A config setting to allow people to join other compact machines or let it depend on teaming.

**World Information**
Preset: CompactSkies
Prestige: No
Modpack Version world created in: 4.0.2
Additional Content Installed: no
Client Information
Modpack Version: 4.0.2
Java Version: 1.8.0_51
Launcher Used: Twitch
Memory Allocated: 6 gb
Server/LAN/Single Player: Single Player
Optifine Installed: no
Shaders Enabled: no

**Comment by JackRuby1** [comment]
But you can, if you right click the compact machines, there's a section for whitelisting other players to join your machine. This is also a suppose type issue and would of been better suited for the discord over at: http://bit.ly/DarkostoDiscord

**Comment by Darkosto** [comment]
You can, you need to add them to your compact machine by adding them to your whitelist ingame
