### ISSUE TITLE
charm bug mystical agriculture

### ISSUE THREAD

**Issue by SadNerdIsSad** [DarkPacks/SkyFactory-4#1109]
## Bug Report
so i made a full set of supremium armor and a sword and made charms for each and every one of them, but no matter what i do i cant put the charms on the armor and sword

## Expected Behaviour
what  i thought would happen is that i'll put them in a crafting table together with the charms and it would give me the option to have it with the charm, which obviously didn't work

## Possible Solution
i have no idea

## Steps to Reproduce (for bugs)
1. craft full supremium armor and sword
2. make the following mystical agriculture charms: night vision, fire resistance, absorption, resistance and strength 2
3. try to put the chams on the armor and sword

## Logs
* Client/Server Log: this part confused me
* Crash Log: idk what to put here

## World Information
* Preset: skyfactory classic
* Prestige: no
* Modpack Version world created in: 4.0.8
* Additional Content Installed: no

## Client Information

* Modpack Version: 4.0.8
* Java Version: latest?
* Launcher Used: idk
* Memory Allocated: the default, i dont know what is it
* Server/LAN/Single Player: single player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by sk2048** [comment]
The recipe for the application of each charm is visible in JEI. You need a Tinkering Table from Mystical Agriculture and some essence and prosperity shards for each one. They do not combine in the crafting grid, and as far as I can tell nothing indicates they should.

![Screenshot 2019-06-27 at 12 53 20](https://user-images.githubusercontent.com/23245543/60264334-d7a94d00-98da-11e9-961c-586eb15cd1ea.png)

You would be better off asking questions about gameplay mechanics you don't understand on the discord: https://discord.gg/darkosto in the #sf4-gameplay channel.
