### ISSUE TITLE
Pink Slime Seeds reciepe invalid that is found in JEI

### ISSUE THREAD

**Issue by TXM-MC** [DarkPacks/SkyFactory-4#1110]
## Bug Report

Cannot craft Pink Slime Seeds as the recipe followed in JEI with Pink (dye), Melon Seeds, Slimeball (Any)

## Expected Behaviour

Notting comes out the output in any crafting tables.

## Steps to Reproduce (for bugs)

1. Joined a private server.
2. Open a Crafting Table (Minecraft) OR a Craft Station (Tinker).
3. Put Pink (dye) in; A, top-left OR B, top-middle OR C, top-right.
4. Put Melon Seeds (Minecraft) in; A, middle-left OR B, middle-middle OR C, middle-right.
5. Put Slime Ball (Minecraft, Tinker) in A, bottom-left OR B, bottom-middle OR C, bottom-left.

## Logs

* Client/Server Log: Latest log file is outdated and for the wrong version - https://txm-mc.homeserver.com/SkyFactory4/fml-client-latest.txt
* Crash Log: https://txm-mc.homeserver.com/SkyFactory4/crash-2019-06-18_01.02.54-client.txt

## World Information

* Preset: Sky World ?

* Prestige: ?

* Modpack Version world created in: Minecraft 1.12.2 Sky Factory 4 V4.0.2

* Additional Content Installed: none

## Client Information

* Modpack Version: 4.0.2
* Java Version: 1.8.0_201-b09
* Launcher Used: Twitch - OutOfMemmory so now using the same modpack in Minecraft (Vanilla, FML)
* Memory Allocated: java -Xmx6G
* Server/LAN/Single Player: Server
* Optifine Installed: no
* Shaders Enabled: no

**Comment by sk2048** [comment]
Does not appear to be a problem in 4.0.8. Please update.
