### ISSUE TITLE
project e don´t exist in my tmi menu, but the mod is installed and in the modlist. Also i cant play the Project e world in the world create menu.

### ISSUE THREAD

**Issue by TheMLP** [DarkPacks/SkyFactory-4#1111]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
This sounds like intended behaviour, ProjectE and its associated world type are a prestige reward only and are not available to players not playing by that ruleset.
