### ISSUE TITLE
Fixing Prestige points - transfer/upgrade problems

### ISSUE THREAD

**Issue by Ann-MarieR** [DarkPacks/SkyFactory-4#1112]
I've loved playing this pack, always on Prestige, earning points... allocating them etc...

But... transferring saves from desktop to laptop, the Prestige points don't transfer.... plus with a crash with te update to 4.0.8 I've lost tham all again. Please could you a) explain what needs to be copied across to bring Prestige work over, and b) is there please a way to add some basic ones if I need to totally restart - no bonsai/ore-excavation gets tiring the 10th+ time of doing it...

so, Feature request…

A) Info to move prestige points along with save files

B) a way to re-apply them if lost! (if only the first 2 points)

**Comment by sk2048** [comment]
Copy the prestige folder to transfer prestige between systems. You can find it in the root folder of your instance, i.e. it and the saves folder are in the same place.

Second, to add prestige points to your character, I think the command is `/prestige add @p <number>`
