### ISSUE TITLE
What am I missing

### ISSUE THREAD

**Issue by ForevrUndead** [DarkPacks/SkyFactory-4#1114]
I've tried to make an effective SkyFactory 4 lite for the fact my pc is not powerful, the game will load up but wont let me into a world b4 freezing up. Cutting some mods (37) is was able to get myself to load into my friends world but we found we couldn't get acorns to dry on drying racks. re-added some mods one at a time to try and find if we can get it to function again and found no fix. Re-installed, pack cut again (~30), barely loaded a world but the acorns still wouldn't dry. the list is below of the current 30 i've tried removing. i'm wondering which of these mods allows that function, and of course if there where some additional mods i can cut to assist performance. drying the "vanilla" (fish/zflesh) on the rack worked fine but anything after what tinkers racks were coded for previously would not work.

Note: i abbreviated and too point out as well this is also what i found these mods would mainly offer, not that the statement i make bout the mod is correct. i also did the same process for SF3 previously and got it to work on my own but i new more of the mods from there.

**key**
visual- it is functionally a player comfort or as stated
large- Large mod that i didn't find anything i'd want
better mod- there was already another mod in the pack i'd use instead 
wont use - as said

apotheosis - large 
bibliocraft - large
bouncycreepers -visual
chargers - better mod
chineseworkshop - visual
cookingforblockheads - better mod/large
darkutils - large
fancyblockpart. - visual
fenceoverhaul - visual
headcrumbs - visual
hydrogel - wont use
malisiscore/door - visual
neat - visual
nuclearcraft - large/better mod
parabox - wont use
portalgun - wont use
practicallog - wont use
prestige - wont use
rustic - visual
slab_mach - wont use
slimyboyos - visual
snad - wont use
talgates - visual
tipsthescales - wont use
twitchcrumbs - visual
uppers - better mod
viescraft - wont use
waddles - wont use
walljump - wont use
withercrumbs -  visual

**Comment by Streamcyper** [comment]
The problem you're running into is that most of the mods that adds any blocks, is also referenced in one or more scripts. By removing a mod you will then break that whole script and that will cause all sorts of problems. So it is unfortunate then that you will pretty much have to remake the whole pack in order to achieve what you're looking for here.
