### ISSUE TITLE
Can the new parabox be documented, please?

### ISSUE THREAD

**Issue by oliverjanik** [DarkPacks/SkyFactory-4#1116]
What does it say min/max power? It used to be constant number. What happens if power input dips below min?

Also, why does say a random item name?

**Comment by Darkosto** [comment]
The modpack has already documented these features in the advancement. Read the tooltips given to you for the information you're looking for.

![image](https://user-images.githubusercontent.com/10309699/61999384-c045b700-b074-11e9-95c7-0a1f7973a65f.png)
