### ISSUE TITLE
Can't load a spesific modded minecraft world

### ISSUE THREAD

**Issue by xxjoubertpxx** [DarkPacks/SkyFactory-4#1125]
HI there,

I just want someone to help me with a problem I'm having. I am currently playing Sky Factory 4 (using twitch) and everything was going perfectly, until this morning. I launched it, as usual, but then when I clicked play on my world, it loaded and then, right before finishing, it said not responding and this would happen sometimes, so I waited. A hour passed and nothing happened, so I clicked on it, and it turned slightly white and said that binary java is not responding and gave a option of waiting or closing and then taking me to the launcher and saying it crashed (I don't understand the crash log ). I repeated this a couple of times, with same result, so I tried giving it more RAM. 8gigs, but same output. After that, I tried creating a new world, and that worked perfectly. Can someone please help me with this problem, I came quite far and I don't want to lose my progress.
![Screenshot (31)](https://user-images.githubusercontent.com/52620746/60765593-49cd1f00-a09d-11e9-9986-2ed55bb8f06a.png)

[crash-2019-07-07_09.54.09-server.txt](https://github.com/DarkPacks/SkyFactory-4/files/3365383/crash-2019-07-07_09.54.09-server.txt)

Tank you

**Comment by sk2048** [comment]
I think this is a known issue with RFTools Information Screens being unloaded. Forge has a system built in to help you recover from issues like this, with the game closed set `B:removeErroringTileEntities=true` in forge.cfg, start the game, load the world. The crash shouldn't occur and you should validate that information screens are removed from the world until RFTools Power is updated in a future release of the pack.

Once you've done this, close the game, go back to the config file and set `B:removeErroringTileEntities=false` again.

If you need assistance with this, please use the Discord - you will get faster support there generally.
