### ISSUE TITLE
plz, add wireless crafting terminal to AE or do something to integrate AE and simple storage... miss ender io cables too (playing version 4.0.8 in prestige mode)

### ISSUE THREAD

**Issue by peagasp** [DarkPacks/SkyFactory-4#1129]
## Config/Script Details
* Link:

## Mod Details
* Name:
* CurseForge Link:

**Comment by ktole1999** [comment]
since this is a feature request you might want to speak in discord about it. github is for bugs.

**Comment by Itszipzon** [comment]
I think EnderIO have some issues with some of the mods installed on this modpack. One of them is "AE2". I checked that out myself too. https://www.curseforge.com/minecraft/mc-mods/ender-io
