### ISSUE TITLE
OreExcavator doesnt work anyone more and makes the mod pack feel tedious pls fix 

### ISSUE THREAD

**Issue by sweadingduro** [DarkPacks/SkyFactory-4#1130]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by Darkosto** [comment]
No information given in report. No way I can give you help since you've given nothing to investigate with. How am I supposed to figure out what's happening when you don't fill out any of the fields?
