### ISSUE TITLE
Added back the ex nihilo creatio and ex compression back into SF4

### ISSUE THREAD

**Issue by aussie4** [DarkPacks/SkyFactory-4#1131]
Bug Report
I added back the exnihilo creatio and ex compression back into skyfactory (found the trees and resource hogs not as sustainable) and the ore pieces wont craft into ore chunks.
## Expected Behaviour
When I place four of the same kind of pieces, I do not get a chunk.
## Possible Solution
help making a custom recipe?
# World Information

* Preset: normal

* Prestige: no

* Additional Content Installed:
exnihilocreatio-1.12.2-0.4.5.1
LootBags-1.12.2-2.5.8.5
StorageDrawers-1.12.2-5.3.8
EnderCore-1.12.2-0.5.59
Chameleon-1.12-4.1.3
EnderIO-1.12.2-5.0.46
extrautils2-1.12-1.9.9
ExCompressum_1.12.2-3.0.31
ImmersiveEngineering-0.12-89
## Client Information

* Modpack Version:
* Java Version: 4.0.8
* Launcher Used: twitch
* Memory Allocated: 4gb
* Server/LAN/Single Player: server/single player

**Comment by ktole1999** [comment]
when you added the mods you changed the pack and the functionality of the scripts. bad news for you.

**Comment by aussie4** [comment]
It shouldnt make a mod, that doesnt relay on anything from skyfactory, not work

**Comment by ktole1999** [comment]
but the scripts that were created for the pack removes and adds items functionality. You wont get any support due to these changes. I have seen it too many times before.

**Comment by aussie4** [comment]
neat
thanks
