### ISSUE TITLE
Tinkers Mod Issue

### ISSUE THREAD

**Issue by GDBrallon** [DarkPacks/SkyFactory-4#1132]
## Bug Report
I was going to make a smelter, and when I was going to make a drain and a controller none of it would craft, like didn't pop up. When I looked it up In the JUI, it didn't show. I just looked up the recipe online and it still didn't work

## Expected Behaviour
 Explained in the bug report

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log: No logs about it
* Crash Log: No crash

## World Information

* Preset: SkyFactory 4

* Prestige:  Yes

* Modpack Version world created in: 1.12.2

* Additional Content Installed:

## Client Information

* Modpack Version: SkyFactory 4 4.04
* Java Version: 1.12.2
* Launcher Used: Minecraft launcher (twitch)
* Memory Allocated: 3228 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: No

![reeeerereresasd](https://user-images.githubusercontent.com/52804503/61093848-0f071600-a412-11e9-9d7a-349d75d7a4e0.PNG)

**Comment by sk2048** [comment]
You are playing prestige mode, please check what the available rewards are by pressing (by default) the `p` key. You'll see that one of the rewards is the smeltery.

Without unlocking it, you can use the melter and alloy tank to fulfil all the smeltery's functions.

If you don't like this unlock system, then play without prestige enabled. It is not forced on you.

**Comment by GDBrallon** [comment]
Makes sense, but i don't understand the first one of prestige so i was just ajsdasldasd
