### ISSUE TITLE
Ram/kb/mb

### ISSUE THREAD

**Issue by EnBoue** [DarkPacks/SkyFactory-4#1134]
i am trying to play skyfactory 4 on the twitch launcher and any time i hit play on the minecraft launcher part of it, it either says Invalid maximum heap size: -Xmx4096m
The specified size exceeds the maximum representable size. or when i lower it Error occurred during initialization of VM
Could not reserve enough space for 3932160KB object heap
Java HotSpot(TM) Client VM warning: ignoring option PermSize=256m; support was removed in 8.0

**Comment by sk2048** [comment]
Sounds like you're using 32-bit Java, which cannot reference more than 3.5GB of RAM. Uninstall it and replace it with a 64-bit version of Java 8.
