### ISSUE TITLE
The game crashed whilst loading nbt data Error: java.io.EOFException: Unexpected end of ZLIB input stream

### ISSUE THREAD

**Issue by xxjoubertpxx** [DarkPacks/SkyFactory-4#1135]
## Bug Report
Whenever I go into my one world, it instantly kicks me out and gives me a error:
The game crashed whilst loading nbt data
Error: java.io.EOFException: Unexpected end of ZLIB input stream

## Expected Behaviour
I log into my world, then it kicks me out

## Possible Solution
I don't have a clue, since it worked yesterday

## Steps to Reproduce (for bugs)
1.open minecraft sky factory 4
2.open specific world (other worlds work)

## Logs
[crash-2019-07-14_09.58.07-server.txt](https://github.com/DarkPacks/SkyFactory-4/files/3389604/crash-2019-07-14_09.58.07-server.txt)

## World Information
* Preset:Normal sky factory
* Prestige: no 
* Modpack Version world created in:1.12.2

## Client Information
* Modpack Version:4.0.8
* Launcher Used:2.1.5387
* Memory Allocated: 3G
* Server/LAN/Single Player: Single player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sk2048** [comment]
Unfortunately your world is corrupted. The NBT tag it's trying to read is incomplete. There's nothing here that indicates that is due to an issue in the pack. You should restore a backup.
