### ISSUE TITLE
Cant download

### ISSUE THREAD

**Issue by ThePugMaster89** [DarkPacks/SkyFactory-4#1138]
When I try to download it, it says "This Modpack requires a dependency that is missingor no longer available. Missing addon ID:279131
Please help me

**Comment by ktole1999** [comment]
where are you downloading it from?

**Comment by bennington55** [comment]
im trying from twitch app and im getting same error

**Comment by sk2048** [comment]
This is an issue with Twitch, it usually clears itself up but you can use an alternative launcher. Both MultiMC and ATLauncher are supported.
