### ISSUE TITLE
Can't take out anything from my ME-System

### ISSUE THREAD

**Issue by Itszipzon** [DarkPacks/SkyFactory-4#1143]
## Expected Behaviour
Take my items out of my ME-System

## Logs
* Client/Server Log: Not my server
* Crash Log:

## Client Information

* Modpack Version: 4.0.8
* Java Version: Not sure how to check. downloaded latest in 30.01.19 (dd.mm.yy)
* Launcher Used:Twitch
* Memory Allocated:45-50%
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: i dont know
* Operating System: Hosted
* Hoster/Hosting Solution: Serverminer.com
* Sponge (Non-Vanilla Forge) Server: no

**Comment by sk2048** [comment]
Have you got a security station on the network and is it setup correctly?

**Comment by Itszipzon** [comment]
Yeah i had. it worked when i removed it thanks
