### ISSUE TITLE
Want to be able to make Tinkers' Construct bolts

### ISSUE THREAD

**Issue by Itszipzon** [DarkPacks/SkyFactory-4#1145]
Context
I would like to be able to make bolts for my crossbow. i didnt know i couldnt make bolts so i made my crossbow first

Config/Script Details
Link: https://github.com/SlimeKnights/TinkersConstruct
Mod Details
Name: Tinkers' construct
CurseForge Link:

**Comment by JackRuby1** [comment]
You need to make a tool rod and pour liquid over it for the desired tip on the bolt you want.

**Comment by Itszipzon** [comment]
Thank you so much!! i'm used to just use sticks

**Comment by Darkosto** [comment]
Looks like this is taken care of. Closing the issue.
