### ISSUE TITLE
Install and ServerStart scripts can't find settings.sh

### ISSUE THREAD

**Issue by Batchicken** [DarkPacks/SkyFactory-4#1147]
I'm trying to set up a server on a machine running Ubuntu 18.04.2. I took everything from the ZIP file and put it into a folder on my desktop named "SkyFactory4". I didn't change any settings or anything, but when I try to install it using
 `sudo bash ~/Desktop/SkyFactory4/Install.sh`
I get
`/home/**********/Desktop/SkyFactory4/Install.sh: line 4: ./settings.sh: No such file or directory
Installing Forge and required jars.
Done!`
and no files/folders are changed or created.

Any help with this would be greatly appreciated.

**Comment by ktole1999** [comment]
did you accept the eula?

**Comment by Batchicken** [comment]
There is no EULA to accept. Running the install script doesn't actually install Forge. I can't boot the server without a server JAR

**Comment by sk2048** [comment]
You should `cd` into SF4's directory. Otherwise it's looking in your `~` directory for the settings.sh file.

**Comment by Batchicken** [comment]
Thanks! That worked great.
