### ISSUE TITLE
Missing a Dependacy

### ISSUE THREAD

**Issue by CosmicPegasus34** [DarkPacks/SkyFactory-4#1152]
## Bug Report
There is a Missing Depending. The Add-on ID for the Missing Dependency is #222348
## Steps to Reproduce (for bugs)

1. Find the fix for the missing dependency

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: SkyFactory 4/The Void

* Prestige: No 
Provide the version of the modpack that the world was created in if known. Rough estimates are OK -->
* Modpack Version world created in: 1.12.2

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.8
* Java Version: 1.12.2
* Launcher Used: Twitch
* Memory Allocated:
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sk2048** [comment]
This is a Twitch caching or CDN issue that is becoming increasingly frequent. Download the pack using MultiMC or ATLauncher, or wait for Twitch to resolve its issue - usually about 30 mins.
