### ISSUE TITLE
Uncrafting Grinder using power for no reason

### ISSUE THREAD

**Issue by iKayuri** [DarkPacks/SkyFactory-4#1155]
## Bug Report
The Uncrafting Grinder sucks energy even though there is nothing to uncraft.

## Expected Behaviour
Like every other "crafting" machine it should use energy only when it's uncrafting something.

## Possible Solution
Don't know ...

## Steps to Reproduce (for bugs)
Mekanism energy cube linked to the Uncrafting Grinder with fluxduct.

## Logs
* Client/Server Log:
* Crash Log:

## World Information

* Preset: Sky Factory 4

* Prestige: Yes

* Modpack Version world created in: 4.0.8

* Additional Content Installed: None

## Client Information

* Modpack Version: 4.0.8
* Java Version:
* Launcher Used: Twitch
* Memory Allocated: 8Go
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information

* Java Version:
* Operating System:
* Hoster/Hosting Solution: Apex Hosting
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
This does not appear to be true, it uses no energy when disconnected or when connected and idle.

Regardless, even if it did having an idle energy usage is a valid design decision for the mod author to make.
