### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by DoppiaeSSe** [DarkPacks/SkyFactory-4#1162]
### BUG
I'm on the latest version of the server and modpack.
If you use a wireless item node to transfer an item to a filing cabinet with inside an empty folder assigned to the item, it will duplicate infinite times the item in the folder!
Please fix thanks.

**Comment by graphicjazz** [comment]
Just came here to say that I can replicate this problem as well.

**Comment by sam-kirby** [comment]
Closed by dfd8dbb0ee9c226e9d0f0f4becf4bb5da0a5e766
