### ISSUE TITLE
Cyclic/AE2 Crashing chunk in Skyfactory 4

### ISSUE THREAD

**Issue by MrDietPeppsi** [DarkPacks/SkyFactory-4#1163]
Whenever you render in the area it immediately crashes the server. Small separate island that I repeatedly went to multiple times and had no problem and as far as I can see spontaneously started having this problem.

https://pastebin.com/8e4ct6y3

**Comment by sk2048** [comment]
You look to be having an issue with overflowing items. Close the server, set `max-tick-time=-1` in server.properties and then restart. Go to the chunks you're having an issue in and execute `/kill @e[type=item]`

This may take several minutes to work.

**Comment by MrDietPeppsi** [comment]
This worked however I previously was using a geothermal generator setup with a spam clicking dropper which I assume is the overflow of items however I removed that and replaced it with a auto clicking setup which doesnt drop the blocks and it happened again with the same style crash report so just wondering thoughts on that

https://pastebin.com/BEU0ctwg

additionally I do have an ae2 setup with a crafting terminal, me drive with 1 drive in it and energy acceptor accepting energy from the geothermal generator setup.
