### ISSUE TITLE
Ore Excavation mod isnt working (I downloaded from Twitch)

### ISSUE THREAD

**Issue by SaiTR38** [DarkPacks/SkyFactory-4#1164]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.8
* Java Version: Idk
* Launcher Used: Minecraft ??
* Memory Allocated:6144
* Server/LAN/Single Player: Single
* Optifine Installed: NO
* Shaders Enabled: NO

**Comment by sk2048** [comment]
You've neglected to mention if you're playing prestige.

If you are this is intended behaviour, and you should read the in game text on the subject.

**Comment by SaiTR38** [comment]
Im not playing prestige. I want to say this 'Ore Excavation is not ACTIVE'
