### ISSUE TITLE
Base heat removed per tick value for Quartz Cooler may be incorrect [Nuclearcraft]

### ISSUE THREAD

**Issue by lionspridde** [DarkPacks/SkyFactory-4#1173]
## Bug Report

After inconsistencies with my nuclearcraft planner program and the game [in reference to the heat generated per tick by my fission reactor], I dug into the nuclearcraft.cfg file and realized that the problem was that in the _Fission Section, Base Heat removed per tick_ (Line 139).
The value for the quartz cooler was 70 when in most modpacks and in the standard nuclearcraft mod the value is 90. 

## Expected Behaviour

Expected default quartz cooler value is 90, current value is 70.

Default value 90 = more consistency with prebuilt reactors from other modpacks, and in my case, my previous reactors from other playthroughs and modpacks

## Possible Solution

Change quartz cooler value to the default 90 rather than 70, if it is in fact a bug

## Steps to Reproduce (for bugs)

1. Check Quartz Cooler block default value for NuclearCraft
2. Check Quartz Cooler block value in current version of Skyblock 4 under nuclearcraft.cfg (Line 139)

## Logs

* Client/Server Log: No log
* Crash Log: No crash

## World Information

* Preset: Sky Factory 4

* Prestige: No

* Modpack Version world created in: 4.0.8

* Additional Content Installed: None

## Client Information

* Modpack Version:1.12.2
* Java Version: 1.8.0.15 64bit
* Launcher Used: Twitch Launcher (or Native Launcher)
* Memory Allocated: 12288 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No
![Quartz](https://user-images.githubusercontent.com/53855515/62607208-b1a89c80-b8cb-11e9-96a6-b69323b81053.png)

**Comment by sk2048** [comment]
The nuclearcraft config was generated by an earlier version of the mod. These values are the old defaults.

We have already been asked by the nuclearcraft dev to regenerate this config to get the latest balance tweaks.

**Comment by lionspridde** [comment]
I appreciate the quick response and am glad you've already found the issue. If you have the same issue, for now, you can just change the value back to 90 yourself if you wish.

**Comment by sk2048** [comment]
Please leave the issue open until it is resolved on the master branch :)
