### ISSUE TITLE
im cant die or use any objects. im just stuck with no hearts and in the end

### ISSUE THREAD

**Issue by kingbeardly** [DarkPacks/SkyFactory-4#1178]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/Darkosto/SkyFactory4Issues/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!

**Comment by kingbeardly** [comment]
in all fairness im kind of dumb and just assumed it pulled the report from the game... i dont actually know how to get half the info it wants.

**Comment by sk2048** [comment]
Give it your best effort, if there's something you don't know how to get and we really need someone will explain how you can get it after you post. For this we at least need what happened leading up to the issue (Steps to reproduce) and a better description of the issue. What does can't use mean?

Whether you're playing on a server or single player may also be important.

It'll be easiest if you start again with a new issue.

**Comment by kingbeardly** [comment]
ok i made another issue sadly im off to work now.
