### ISSUE TITLE
Internal Exception Error

### ISSUE THREAD

**Issue by AstiLouise** [DarkPacks/SkyFactory-4#1186]
Connection Lost
Internal Exception: com.google.common.util.concurrent.UncheckedExecutionException:java.lang.IllegalStateException: Recipe minecraft:wooden_door (net.minecraft.item.crafting.ShapedRecipes@6c25123e) produces unregistered item minecraft:wooden_door (net.minecraft.item.ItemDoor@20c283b4)

**Comment by sk2048** [comment]
Caused by a config mismatch between server and client.

**Comment by AstiLouise** [comment]
I read that, so I tried just copying the config from the client to the server and still got the same error
