### ISSUE TITLE
There doesn't seem to be an early-game way to obtain aquamarine from Astral Sorcery. Also, there are no obtainable constellation papers either.

### ISSUE THREAD

**Issue by Bluetwisters** [DarkPacks/SkyFactory-4#1189]
## Config/Script Details
* Link:

## Mod Details
* Name:
* CurseForge Link:

**Comment by JPitholz** [comment]
The only way for me was the IF Laser, which tbh isnt that expensive. Constellation Papers are made in Astral Sorcerys Iridescent (maybe butchered the name) Altar.

**Comment by TStan47** [comment]
aquamarine can be found in sandy areas in the lost cities early in the game without the need for astral sorcery.
