### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Blackpanter23** [DarkPacks/SkyFactory-4#1201]
I download SkyFactory 4 - 4.0.8 Server Files (Here: https://www.curseforge.com/minecraft/modpacks/skyfactory-4/files/2724357)
Unzip and click install.  
Change it eula=true.
ServerStart.bat click.
And crash.
Try again, crashed again.

Java versiyon: Java 8 221 64bit

Server Crash: https://pastebin.com/DzYkVbx6
log:                https://pastebin.com/7Zez35iA

**Comment by sk2048** [comment]
This is an issue with unexpected characters being used by a mod in the name of an NBT tag. The only solution at present is to run the server with the OS set to English or another language which does not use restricted characters.

**Comment by Blackpanter23** [comment]
> This is an issue with unexpected characters being used by a mod in the name of an NBT tag. The only solution at present is to run the server with the OS set to English or another language which does not use restricted characters.
Thank. I change OS eng fix.

**Comment by Blackpanter23** [comment]
Thanks ı change OS to eng fix.
