### ISSUE TITLE
Killed enderdragon

### ISSUE THREAD

**Issue by ProKaspar** [DarkPacks/SkyFactory-4#1210]
So basically I went to the End, but when  I got there the dragon was already dead, the ender crystals were not existing but xp was on the ground around the dragon egg altar thingy. Now I need to get 4 nether stars to get the dragon killing achievement. Also, I could not find the elytra in End City. I could not even find chests in the buildings, but there was 1 building, no more.

**Comment by sk2048** [comment]
Dragon is supposed to be dead. End cities are a vanilla structure, which are randomly generated from a set of building blocks. They vary in size and do not always contain elytra.
