### ISSUE TITLE
Can't download the modpack

### ISSUE THREAD

**Issue by DevilBG2** [DarkPacks/SkyFactory-4#1211]
I get this message when I press download. what do I do?
![994e2d741c7e98ab86aac374673b8bce](https://user-images.githubusercontent.com/45860178/63636699-56bcc680-c67b-11e9-87a3-e1f281fe02c4.png)
i tried running twitch as administrator and it didn't work

**Comment by sk2048** [comment]
This is not a modpack issue, please contact Twitch support.
