### ISSUE TITLE
Server Crashes With Mekanism Valve For Turbine

### ISSUE THREAD

**Issue by Kyamonster** [DarkPacks/SkyFactory-4#1214]
## Bug Report
The server crashes when the valve is being used on the turbine.

## Expected Behaviour
It shouldn't crash

## Possible Solution
Update mekanism to the newest update 
## Steps to Reproduce (for bugs)
1. Put the valve on the turbine.
2. Crash

## Logs
No logs

## World Information
* Preset: Default Skyfactory 4
* Prestige: No
* Modpack Version world created in: Newest update/ Newest server update
* Additional Content Installed: none

## Client Information
* Modpack Version: Newest
* Java Version: Idk
* Launcher Used: Twitch
* Memory Allocated: 4.5
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: Newest
* Operating System: I don't know (bought server)
* Hoster/Hosting Solution: Update mekanism
* Sponge (Non-Vanilla Forge) Server: No

**Comment by sk2048** [comment]
Mekanism has been updated in the `newest` version of the pack, which version are you actually playing?

**Comment by Kyamonster** [comment]
For my client I have 4.0.8 and server 4.0.8 and the server crashes to the valve. One of the people on the server told me there was an update for mekanism that fixed that. Now if he is wrong we still can't use that valve so idk what to do then. The server is for sure on 4.0.8 because I made the server about 2 weeks ago and got the newest version.

**Comment by sk2048** [comment]
This is why giving actual version numbers is important. Version 4.1.0, released last week, should fix your issue.
