### ISSUE TITLE
I can't destroy the tree by SkyFactory 4 

### ISSUE THREAD

**Issue by Felix11042005** [DarkPacks/SkyFactory-4#1227]
I go into my Server and there is only the tree there you start and I CAN'T BREAK THAT TREE so I can't play this modpack :/

**Comment by sk2048** [comment]
You are encountering vanilla minecraft’s spawn protection. Please learn a little about how to run a server before you accuse the pack of being broken.

**Comment by Felix11042005** [comment]
And what should I do now?


Sam Kirby <notifications@github.com> schrieb am Di., 3. Sep. 2019, 07:40:
