### ISSUE TITLE
Anvil disappears when broken with Block Breaker (Industrial Foregoing)

### ISSUE THREAD

**Issue by Yurihhh** [DarkPacks/SkyFactory-4#1231]
When a (vanilla Minecraft) Anvil is broken by a Block Breaker from Industrial Foregoing, it doesn't move to it's inventory, but instead disappears completely. It would be nice if this could be fixed, because I'd like to use it to automatically anvil smash things.

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/Darkosto/SkyFactory4Issues/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
