### ISSUE TITLE
problems with making iron and gold ingots with other mods

### ISSUE THREAD

**Issue by SebasManzana007** [DarkPacks/SkyFactory-4#1238]
I put several extra mods, with which you can plant iron and gold, an example is croparia, all other minerals if they can be crafted, but there is a bug with gold and iron ingots.
![2019-09-08_20 32 18](https://user-images.githubusercontent.com/55072879/64501816-e36ca480-d277-11e9-98ba-89498e7e6c7a.png)
![2019-09-08_20 32 26](https://user-images.githubusercontent.com/55072879/64501818-e4053b00-d277-11e9-87a6-8f5f9efafe3d.png)
It's something like that, but with iron or gold it doesn't work

**Comment by SebasManzana007** [comment]
I tried several mods, but none let me make the iron

**Comment by ktole1999** [comment]
you changed the pack. therefore you broke the scripts. not supported.
