### ISSUE TITLE
filing cabinet items converting into air

### ISSUE THREAD

**Issue by chriss1314** [DarkPacks/SkyFactory-4#1239]
i have set up about 30 filing cabinets with the applied energistics 2 system
by now half items i had in those cabinets have converted into air...

**Comment by BioGeekJoey** [comment]
This is fixed in the next version of Real Filing Cabinets, which is supposed to be in the next release of Sky Factory. You can install the beta version of the mod pack or manually upgrade Real Filing Cabinets in your current instance.
