### ISSUE TITLE
Mob masher killing me at random

### ISSUE THREAD

**Issue by Raptorture** [DarkPacks/SkyFactory-4#1245]
The mob masher will randomly kill me, even if I'm not in the world it is located in.

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SkyFactory-4/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
