### ISSUE TITLE
Sky Orchards + tinkers' construct 

### ISSUE THREAD

**Issue by Silvanop1** [DarkPacks/SkyFactory-4#1247]
**Bug Report**
When trying to dry and Dirt Arcon on drying rack, the Dirt Arcon would not transform in petrified one. Same with cottonwood leaves. Other thing, as rotten flesh, are transform correctly.
Client waila see progress bar going to 100% after that nothing happens

**Expected Behavior**
 Dirt Arcon have to transform in to Petrified Acorn

**Possible Solution**
Probably the mod Sky Orchards is not connecting to tinkers'

**Steps to Reproduce (for bugs)**
Put a Dirt Arcon on a drying rack and wait for 1 minute.

**Logs**
Client/Server Log: Crash Log: Bug does not cause a crash.

**World Information**
Preset: Sky Factory 4
Prestige: Yes
Modpack Version world created in: 4.0.8
Additional Content Installed: None
Client Information
Modpack Version: 4.0.8
Java Version: 1.12.2
Launcher Used: Twitch
Memory Allocated: 4G
Server/LAN/Single Player: Server
Optifine Installed: No
Shaders Enabled: No

**Comment by Silvanop1** [comment]
The tinkers.zs in "/scripts/crafttweaker/modIntegrations" is correctly have right line:
tinkers.addDrying(<sky_orchards:acorn_petrified>, <sky_orchards:acorn_dirt>, 1200);

and this is crafttweaker.log for undertand if it connect as it have to.
Thank you very much, i tried to reinstall, but it's the same.
[crafttweaker.log](https://github.com/DarkPacks/SkyFactory-4/files/3614080/crafttweaker.log)

**Comment by sk2048** [comment]
The scripts are crashing due to missing items from ceramics and tcomplement. Have you removed these mods or changed their configs?

**Comment by Silvanop1** [comment]
> The scripts are crashing due to missing items from ceramics and tcomplement. Have you removed these mods or changed their configs?

No, it's same modpack that i downloaded from curse. The same exactly pack is working well on local pc, so im really lost
