### ISSUE TITLE
Trees cannot grow

### ISSUE THREAD

**Issue by Shademoon112** [DarkPacks/SkyFactory-4#1253]
In my world there is no way for me to grow trees. I have a torch but you also need water and there is no way for me to get water to use. I hope you can try to find a way to work around this, maybe by putting a 1 by 1 hole of water by the tree you start with?

**Comment by sk2048** [comment]
You don't need water.

**Comment by sk2048** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SkyFactory-4/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
