### ISSUE TITLE
mods have different client than server

### ISSUE THREAD

**Issue by SLGKing** [DarkPacks/SkyFactory-4#1260]
[13:58:44] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: KingOfH8ers lost connection: Server Mod rejections:
Applied Energistics 2: Requires version rv6-stable-7 but client has rv6-stable-6.
Carry On: Requires version 1.12.2 but client has 1.12.1.
CodeChicken Lib: Requires version 3.2.3.357 but client has 3.2.2.353.
Construct's Armory: Requires version 1.2.4 but client has 1.2.3.
Cooking for Blockheads: Requires version 6.4.71 but client has 6.4.70.
Culinary Construct: Requires version 1.3.3 but client has 1.3.2.1.
EnderStorage: Requires version 2.4.6.137 but client has 2.4.5.135.
Inspirations: Requires version 1.12.2-0.2.6 but client has 1.12.2-0.2.4.
JourneyMap: Failed mod's custom NetworkCheckHandler FMLMod:journeymap{1.12.2-5.5.5}
Mantle: Requires version 1.12-1.3.3.55 but client has 1.12-1.3.3.49.
Mekanism: Requires version 1.12.2-9.8.0.381 but client has 1.12.2-9.7.5.376.
Mekanism: Generators: Requires version 1.12.2-9.8.0.381 but client has 1.12.2-9.7.5.376.
More Cauldrons: Requires version 1.4.5 but client has 1.4.4.
Mystcraft: Requires version 0.13.7.04 but client has 0.13.7.03.
NuclearCraft: Requires version 2.17c but client has 2.17a.
Prestige: Requires version 1.1.58 but client has 1.1.53.
Primitive Crafting: Requires version 1.3.5 but client has 1.3.1.
Real Filing Cabinet: Requires version 0.2.0.19 but client has 0.2.0.14.
RecipeStages: Requires version 1.1.3 but client has 1.1.1.
Simple Storage Network: Requires version 1.7.8 but client has 1.7.6.
Statues mod: Requires version 0.8.9 but client has 0.8.7.2.
Tinkers' Complement: Requires version 1.12.2-0.4.2 but client has ${version}.
Tiny Progressions: Requires version 3.2.34 but client has 3.2.32.
Topography: Requires version 1.10.1 but client has 1.5.1.
Translocators: Requires version 2.5.2.81 but client has 2.5.1.77.
Yoyos: Requires version 1.12.2-1.3.3.25 but client has 1.12.2-1.2.2.20.

this is the  error im getting, i have and cannot find out how to update my client to the server, i installed the most up to date installation.

**Comment by rosshadden** [comment]
You have SkyFactory `v4.0.8` and you are trying to join a server with `v4.1.0`...
