### ISSUE TITLE
Languaje support

### ISSUE THREAD

**Issue by cr998** [DarkPacks/SkyFactory-4#1264]
There are any way to transalate this modpack?

**Comment by sam-kirby** [comment]
Yes, see here https://github.com/DarkPacks/SkyFactory-4/tree/master/src/resources/skyfactory4/lang

**Comment by cr998** [comment]
I will work to translate SkyFactory4 to spanish

**Comment by cr998** [comment]
There are any way to make more easy the process of translation, like use self-hosted weblate
