### ISSUE TITLE
Server crash on unloading overworld

### ISSUE THREAD

**Issue by VoidCallerZ** [DarkPacks/SkyFactory-4#1266]
## Bug Report
Whenever I join another dimension the server crashes, when rejoining the server after a restart I do am in that dimension but the server will once again crash due to a "World Ticking Exception"

## Expected Behaviour
Whenever I join another dimension the server is supposed to properly unload the overworld chunks and load in the other dimension its chunks.

## Possible Solution
I have managed to fix the problem myself by updating the Forge version to 2846. I have tried removing Foamfix as this appareantly did something with unloading chunks, but unfortunatly this didn't resolve the problem.

## Steps to Reproduce (for bugs)
1. Download my backup world from: [Skyfactory 4 Server Backup zip on Github](https://github.com/VoidCallerZ/SkyFactory4Server)
2. Place the world into a server using Forge 2838 (which is the standard when downloading the server pack)
3. When entered into the server eat a dimensional cake to teleport to another dimension (lost worlds or nether doesn't matter)
4. Whilst loading into the world the server crashes and shuts down.

## Logs

* Client/Server Log: [Server Log on Gist](https://gist.github.com/VoidCallerZ/a507ff658707fcaa52119e7c9a8c9de2)
* Crash Log: [Crash Log on Pastebin](https://pastebin.com/MqtEY5RM)

## World Information

* Preset: Sky Factory 4

* Prestige: False

* Modpack Version world created in: 4.0.8

* Additional Content Installed: None

## Client Information

* Modpack Version: 4.0.8
* Java Version: 1.8.0_212
* Launcher Used: Twitch
* Memory Allocated: 6GB
* Server/LAN/Single Player: Server
* Optifine Installed: False
* Shaders Enabled: False

## Server Information
* Java Version: 1.8.0_212
* Operating System: Windows 10
* Hoster/Hosting Solution: None
* Sponge (Non-Vanilla Forge) Server: False

**Comment by sam-kirby** [comment]
You have correctly identified this as a Forge bug, we will update in the next version of the pack.

See here: https://github.com/MinecraftForge/MinecraftForge/commit/863ab2ca184cf2e2dfa134d07bfc20d6a9a6a4e8
