### ISSUE TITLE
Topography throwing NullPointerException on "island new" command

### ISSUE THREAD

**Issue by NightEule5** [DarkPacks/SkyFactory-4#1267]
## Bug Report

When I run /topography island new [player] on my server it throws a NullPointerException.

## Steps to Reproduce (for bugs)

1. Run /topography island new [Player]

## Logs

* Client/Server Log: https://pastebin.com/LVSwh7Ki
* Crash Log: N/A

## World Information

* Preset: Sky Crash Factory Landing

* Prestige: Whatever default is

* Modpack Version world created in: 4.0.8

* Additional Content Installed: None

## Client Information

* Modpack Version: 4.0.8
* Java Version: OpenJDK 1.8.0_222 OpenJ9 0.15.1
* Launcher Used: MultiMC
* Memory Allocated: 5128M
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: OpenJDK 1.8.0_222 OpenJ9 0.15.1
* Operating System: Ubuntu Server
* Hoster/Hosting Solution: Self-hosted
* Sponge (Non-Vanilla Forge) Server: No

**Comment by sam-kirby** [comment]
Sky Crash Factory Landing was not added to the pack until 4.1.0. This leads me to believe you have made a mistake when incorporating it into an older version, or a mod update was included in 4.1.0 to address this issue.

Topography is unable to match a configuration to the world's generator settings and so is unable to generate a new "island".

This is not an issue on 4.1.0.

**Comment by NightEule5** [comment]
Ok, my bad then. Thank you.
