### ISSUE TITLE
Simple Storage Network Fluid Cabnit

### ISSUE THREAD

**Issue by CyphixHL** [DarkPacks/SkyFactory-4#1269]
I have a Fluid Cabinet that contains a lot of water, and the cables won't connect to it. All the cables don't work with it. Is it supposed to be like this?

**Comment by sam-kirby** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SkyFactory-4/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
