### ISSUE TITLE
prestige

### ISSUE THREAD

**Issue by snakels4** [DarkPacks/SkyFactory-4#1272]
hallo ich habe ein Problem ich habe ebend mein prestige punkt einfach gelöscht oder der gleich aufjedenfall ist er weg. wie kriege ich ihn wieder? muss ich dazu eine neue welt machen und von vorne anfangen oder gehts auch anders? 

viele dankt.

**Comment by cr998** [comment]
I thank that you can add prestige points using /prestige command
