### ISSUE TITLE
Advancments not working

### ISSUE THREAD

**Issue by SWampyG8r** [DarkPacks/SkyFactory-4#1274]
same issue as another closed topic"Some advancements not triggering until world reload #83"
Playing single player,  when  I acquired both the me terminal and Drive bay.  the advancements didn't complete.  so I placed them and broke them to pick them up still no change.  I quit game, restarted game.  broke items again, and when I picked them up, the acheivments completed.

**Comment by cr998** [comment]
what version are you playing?

**Comment by sam-kirby** [comment]
Vanilla Minecraft issue.
