### ISSUE TITLE
Launch Issue

### ISSUE THREAD

**Issue by TStan47** [DarkPacks/SkyFactory-4#1277]
I am having an issue with launching a new game of SkyFactory 4 on twitch, it appears there is  no profile loading when you click "play" it goes into an endless "loading" loop. I tried deleting the pack and re-installing it but get the same issue. 
I also tried other mod packs and get the same launch issue with them.

**Comment by cr998** [comment]
This is a question for support please enter into http://discord.gg/darkosto inside the channel sf4-client-support
