### ISSUE TITLE
Problem with prestige

### ISSUE THREAD

**Issue by Vsyncrooo** [DarkPacks/SkyFactory-4#1278]
just clean Sky factory 4

## Bug Report
 Prestige isn't enabled even if changing the config.

## Expected Behaviour
 That it is enabled.

## Steps to Reproduce (for bugs)

1. Start Sky factory 4 server and play for a few days
2. Enable prestige

## Logs

* Client/Server Log: https://anonfile.com/d389Wc78nc/2019-10-08-6.log_gz
* Crash Log:

## World Information

* Preset:
 Yes
* Prestige: 
 newest 
* Modpack Version world created in:latest
 none
* Additional Content Installed:

## Client Information

* Modpack Version: 4,0,8,
* Java Version: 2,8,221,11
* Launcher Used: latest
* Memory Allocated: unlimited
* Server/LAN/Single Player: Server
* Optifine Installed: NA
* Shaders Enabled: NA

## Server Information
* Java Version: 2,8,221,11
* Operating System: Windows
* Hoster/Hosting Solution: local
* Sponge (Non-Vanilla Forge) Server: NA

**Comment by cr998** [comment]
This is a question for support.

Please take a look at the pdf guide inside the skyfactory4-server.zip you can also take a look here https://usermanual.wiki/Document/SkyFactory20420Multiplayer20Instructions.1284397797/html
at the end of the file you can read about prestige settings

**Comment by Vsyncrooo** [comment]
Already tried this. It won't enable prestige. force open opens it but we can still craft hopper bonsai's and such without unlocking.

**Comment by sam-kirby** [comment]
You cannot easily go from playing without prestige to playing with it whilst keeping your world. This is because the initial state of each player differs between the two modes.

To properly change between the two, it is easiest to start a new world.

You cannot get prestige points from advancements in your current world and you won't have access to the parabox.

**Comment by Vsyncrooo** [comment]
Ok i know this is closed and all. But for a reason prestige managed to enable. But even with unlocking the perks it still drops itself when held in our mainhand. How do i undo this ?
