### ISSUE TITLE
found a dupe, if connected "item transfer node" and "filling cabinet"

### ISSUE THREAD

**Issue by undead467** [DarkPacks/SkyFactory-4#1279]
## Steps to Reproduce (for bugs)

1. Connect "item transfer node" and "filling cabinet"
2. Watch an item appear out of nowhere in the vault

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: Sky factory 4

* Prestige: 

* Modpack Version world created in: 4.0.8

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.8
* Java Version:
* Launcher Used: twitch
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System: win 10
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by shadowfire-ew** [comment]
Encountered this myself. i think the item transfer node is trying to put the item into the filing cabinet, but is failing to take it out of it's inventory. E.g., if you put 10 items into an item filter pipe which goes into the filing cabinet, it will put 10 items into the cabinet per tick while the cabinet's color allows items through.

**Comment by Spontini** [comment]
I can confirm this bug still works.

**Comment by sam-kirby** [comment]
Closed by dfd8dbb0ee9c226e9d0f0f4becf4bb5da0a5e766
