### ISSUE TITLE
Setting up server on mac

### ISSUE THREAD

**Issue by Phantomlink95** [DarkPacks/SkyFactory-4#1280]
I'll admit now; I am a total newb when it comes to ANYTHING server related.
Now, to the meat of the issue: I'm trying to set up a server on mac, however nothing is working or running at all. The instructions provided for Linux SHOULD work, I think, but they just don't. Install.sh and serverstart.sh won't do anything but open as text files.

Does ANYONE know how to get this to work? I know it's not the most common OS to run these things on, but it's what I have.

**Comment by sam-kirby** [comment]
Use the terminal to run the scripts. It does work, I do development and testing for this pack on a mac.
