### ISSUE TITLE
together forever issue !

### ISSUE THREAD

**Issue by TheSpaceman88** [DarkPacks/SkyFactory-4#1284]
## Bug Report

 normaly we can open the quest book both of us and read and complete quest but idk why it doesn t work

## Expected Behaviour
 / the current problmeme is when create a team with the coommand "/tofe invite "name tag" " and then the other accepted we cant sync our books (even with the force sync) only one man can open the book on the island so it s pretty hard for the 2nd to do quest cauz he can t see the quest ... 
 /

## Possible Solution
maybe change that you can . put the both owner of the isle and the team like this maybe the both can read quest
edit : the next day it was resolve :/ so the bug exist but we don t know how it work i think dec onexion renexion of the both work

 

## Steps to Reproduce (for bugs)

1.create an island 
2.add a someone with /tofe invite "namletag"
3. the other guy accept and then he can t open the quest book ...

## Logs

* Client/Server Log:
* Crash Log:

## World Information
 
* Preset: skyblock

* Prestige: yes

* Modpack Version world created in: 4.0.8

* Additional Content Installed: /

## Client Information

* Modpack Version: 4.0.8
* Java Version: 1.8
* Launcher Used:at launcher
* Memory Allocated: 10 g
* Server/LAN/Single Player: server 
* Optifine Installed: no
* Shaders Enabled:no

## Server Information
* Java Version:1.8
* Operating System:*windows 10
* Hoster/Hosting Solution: /
* Sponge (Non-Vanilla Forge) Server: ?

**Comment by sam-kirby** [comment]
Advancements not loading is a known vanilla issue. Unfortunately there's nothing we can do about this, and it will likely recur from time to time.
