### ISSUE TITLE
0.1TPS in dim0

### ISSUE THREAD

**Issue by pablo3x6** [DarkPacks/SkyFactory-4#1288]
I have the default twitch settings. Game worked fine up until I planted the enderseeds and closed minecraft down. Now, whenever  i launch skyfactory /forge tps shows 0.1tps in dim0

**Comment by sam-kirby** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SkyFactory-4/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
