### ISSUE TITLE
Textures

### ISSUE THREAD

**Issue by profwicket** [DarkPacks/SkyFactory-4#1302]
The textures don't seem to work with the Technic Launcher, and I even downloaded the texture pack for it and the textures are still off. The sky is pink and black, and the advancements book background is full of little pink of black squares. Any idea on how to fix?

**Comment by sam-kirby** [comment]
This pack has not been released on the Technic Launcher. As such we have no control over whatever it is you've downloaded and will not support it.

Please try using the official releases on Twitch/Curseforge or ATLauncher.
