### ISSUE TITLE
2.1b duplication glitch

### ISSUE THREAD

**Issue by Floofyluna** [DarkPacks/SkyFactory-4#1316]
Okay so, When you take a filing cabinet with a empty auto filling folder and connect it with a item trans locator and a chest, When you put a item in the chest and it goes into the filing cabinet it DUPLICATES the item by 2.1 billion. Its pretty nutty and quite game breaking.
![5f9ec5c9a520249e9dce41e90883d5a6-png](https://user-images.githubusercontent.com/57967858/69191970-9ddb1c00-0af1-11ea-9faf-8cd692461968.jpg)
![image](https://user-images.githubusercontent.com/57967858/69192049-ca8f3380-0af1-11ea-8fd4-705ac34d43ae.png)

**Comment by Searchcat37** [comment]
I think this is caused because the item translocator does not register the item is in the file cabinet and keeps retrying until it gives up.

**Comment by sam-kirby** [comment]
Closed by dfd8dbb0ee9c226e9d0f0f4becf4bb5da0a5e766
