### ISSUE TITLE
Dup bug

### ISSUE THREAD

**Issue by juozas-commits** [DarkPacks/SkyFactory-4#1324]
Hi, i don’t know if this is a place to report it, but i found duplication bug using wireless transfer node with filling cabinets, it seems like node caches i.e 6 rotten flesh and doesn’t fully transfer it to cabinet, but instead duplicates it rapidly (happens with any item that firstly enters transfer node). I spotted this when after setting up mob spawner, i looked at cabinet and number of gun powder was rising insanely fast. Again sorry if this isn’t a roght place to report

**Comment by PoopingPants** [comment]
can you please give me a link to your sky factory 4 because curse forge isnt working and i need the modpack

**Comment by juozas-commits** [comment]
Just use ATLauncher instead

**Comment by ThePadawan** [comment]
See also #1234

**Comment by sam-kirby** [comment]
Closed by dfd8dbb0ee9c226e9d0f0f4becf4bb5da0a5e766
