### ISSUE TITLE
Crash on Sky Factory 4 Server

### ISSUE THREAD

**Issue by Krimwalde** [DarkPacks/SkyFactory-4#1325]
Fresh install Sky Factory 4
Fresh install Sky Factory 4 Server both of 4.1.0 and 4.0.8

## Bug Report
Crash on starting server without any error reports.

## Steps to Reproduce (for bugs)

1. Starting server.
2. Waiting a couple minutes to do stuffs.
3. Suddenly crashing server without any error reports.

## Logs

* Client/Server and Crash Log: https://pastebin.com/dvKLsw6R

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in: 

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:  jre1.8.0_231
* Operating System: Windows 10
* Hoster/Hosting Solution: Hamachi Server
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
This is a result of a bug in cyclic which prevents the game from launching in a language that has non-ascii characters in the spelling of inventory. If you add `-Duser.language=en -Duser.country=US` to your server start arguments it should fix your issue.

**Comment by Krimwalde** [comment]
> 
> 
> This is a result of a bug in cyclic which prevents the game from launching in a language that has non-ascii characters in the spelling of inventory. If you add `-Duser.language=en -Duser.country=US` to your server start arguments it should fix your issue.

I'm not sure how can i do that. I need to add `-Duser.language=en -Duser.country=US` to ServerStart.bat file. But which line?

`@echo off

call settings.bat

:start_server
-Duser.language=en -Duser.country=US
echo Starting Sky Factory 4 Server...
java -server -Xms%MIN_RAM% -Xmx%MAX_RAM% %JAVA_PARAMETERS% -jar %SERVER_JAR% nogui
exit /B

goto start_server`

Is that true?

**Comment by sam-kirby** [comment]
No, in settings.bat add them to the end of the line that starts `set JAVA_PARAMETERS=...`. For further support, please use the Discord.
