### ISSUE TITLE
Ender Tank Kicking out players in LAN

### ISSUE THREAD

**Issue by KingDigidrop** [DarkPacks/SkyFactory-4#1327]
## Bug Report
Ender tank is kicking players from a LAN server when there's an interaction with it, like using a bucket to take out lava from the tank, also right clicking to change fluid directions kick the players from the LAN

## Steps to Reproduce (for bugs)

1.https://www.youtube.com/watch?v=ETHWwtUx29k&feature=youtu.be
2.https://www.youtube.com/watch?v=IeGpdXRhMBs&feature=youtu.be

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:default

* Prestige: no

* Modpack Version world created in:4.1.0

* Additional Content Installed:None

## Client Information

* Modpack Version:4.1.0
* Java Version: 8 update 201
* Launcher Used: Twitch default launcher settings
* Memory Allocated: 8GB
* Server/LAN/Single Player: LAN
* Optifine Installed: NO
* Shaders Enabled: NO

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Unfortunately we cannot support LAN as it is a hack in vanilla and does not work very well in a modded environment.

I would suggest setting up a dedicated server. You can run this on the same machine as your client without issue if you have more than 12GB of system memory.

If you need assistance setting this up, please use the discord for support: https://discord.gg/darkosto
