### ISSUE TITLE
Modpack not loading

### ISSUE THREAD

**Issue by algamoda** [DarkPacks/SkyFactory-4#1330]
I tried installing skyfactory4 with the twitch launcher and all i get is an error message, it doesnt even load minecraft and crash.
![eaeaeaea](https://user-images.githubusercontent.com/58119650/70090449-3096b300-15e8-11ea-940e-e89c4c4804b3.JPG)

**Comment by algamoda** [comment]
i get this error with lots of other modpacks too, but on this pc i only have skyfactory, and there are no other mods i put in the folder and no other versions.

**Comment by algamoda** [comment]
should i try manually with the server pack?

**Comment by sam-kirby** [comment]
Not really an issue with the pack, try running using MultiMC or ATLauncher.
