### ISSUE TITLE
Skyfactory 4 crashing for seemingly no reason

### ISSUE THREAD

**Issue by gabenthel0rd** [DarkPacks/SkyFactory-4#1331]
So for quite a while I've been getting seemingly random crashes. It can happen during any time and I don't know what could possibly cause it. I'm using version 4.1 of Sky factory and 1.12.2 of Minecraft. I haven't changed any configs or added any mods manually. Help?

[Log and crash report.zip](https://github.com/DarkPacks/SkyFactory-4/files/3920030/Log.and.crash.report.zip)

**Comment by sam-kirby** [comment]
Forge Multipart 2.6.2.83 may fix this as it has additional null checks.

**Comment by gabenthel0rd** [comment]
Thanks, that worked!

**Comment by sam-kirby** [comment]
Please leave this issue open until it has been fixed in a release of the pack.
