### ISSUE TITLE
Config Settings blocked from being changed?

### ISSUE THREAD

**Issue by Furyocity** [DarkPacks/SkyFactory-4#1340]
ive changed some of the configs in BansaiTrees Config to balance out the % chance of resin and acorns so players get an even amount of both and not just acorns. Reloaded server, client, tried reloading configs with any reload cmds i can remember but server/client side the percentages don't change. Going into the mods folder from the client and going though config shows my changes but is not represented in JEI. any help would be nice sorry if this is something simple that i missed.

**Comment by sam-kirby** [comment]
We do not support modifications to the pack. However, there is nothing “locking” the configs. To apply your changes, you either need to restart the game or use a bonsai trees specific command to trigger a reload as there is no global reload config command. You haven’t been overly clear so if you haven’t tried using `/bonsaitrees reloadTrees` then this is probably your issue.

**Comment by Furyocity** [comment]
ive tried that via cmd prompt, if i do it in solo it crashes the world
