### ISSUE TITLE
Server Guide Installation???

### ISSUE THREAD

**Issue by JSCoyt** [DarkPacks/SkyFactory-4#1341]
## Context
I want to play with my friends this amazing mod pack, but we can't configure the server, we hope anyone of you please can help us making a installation guide step by step.

**Comment by sam-kirby** [comment]
There is a readme and set of instructions in PDF form included in the server download. Everything you need should be there. For further support please ask on the relevant channel on Discord. Please ask specific questions about specific issues there as this issue does not give any real indication where you have had problems, nor specifically what you are trying to do.
