### ISSUE TITLE
launcher isn't loading game

### ISSUE THREAD

**Issue by Gaz3b0** [DarkPacks/SkyFactory-4#1344]
Failed to download file, the file contents differ from what was expected.
Name: jna-4.4.0.jar
URL: https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
Filename on disk: jna-4.4.0.jar
Path: C:\Users\kelso\Twitch\Minecraft\Instances\SkyFactory 4\Install\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
Exists: File

this is the error. Help?

**Comment by sam-kirby** [comment]
This is an issue with Mojang’s native launcher and there is nothing we can do to fix it. Please either use the jar launcher or follow the advice given here: https://bugs.mojang.com/plugins/servlet/mobile#issue/MCL-12570
