### ISSUE TITLE
exception in server tick loop caused by Topography - skyfactory 4

### ISSUE THREAD

**Issue by NatureKas101** [DarkPacks/SkyFactory-4#1345]
I am having a problem with skyfactory 4 where when i try to load the world it sends me to the minecraft launcher with a error code saying, "The game crashed whilst exception in server tick loop
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Topography (topography)." Is there a way to fix this. I am using the twitch mod loader.

**Comment by sam-kirby** [comment]
Without the contents of the error I can't say for certain, but this sounds like your `level.dat` file has become corrupted by a crash or other incident. The easiest way to fix this is usually to restore `level.dat` from a backup. If you need further assistance with this, please use the discord linked above.

**Comment by NatureKas101** [comment]
ok
