### ISSUE TITLE
Deep Moob Learning DML - Crafting error & no recipes in JEI

### ISSUE THREAD

**Issue by JoSToNio** [DarkPacks/SkyFactory-4#1348]
Hi,

I am playing Sky Factory 4 and when I try to start with the DML it doesn't let me crawl most of the recipes of this mod.
Only blank templates, the creator of the loot and the recipient of the andrioid templates appear. I can't crawl wither templates or any other, not even zombie ones. I do not see the recipes but I can not crawl by entering the materials correctly by hand.

What can happen?

Thank you.

**Comment by sam-kirby** [comment]
Run the command `/gamestage add @p non_pacifist`
