### ISSUE TITLE
Description: Exception in server tick loop / my serverstart.pat crush

### ISSUE THREAD

**Issue by Ariaastrid** [DarkPacks/SkyFactory-4#1349]
skyfactory4

**Comment by Ariaastrid** [comment]
![as](https://user-images.githubusercontent.com/59166346/71352647-e4f07d00-2587-11ea-92f0-9c551a9fe8fe.png)

**Comment by sam-kirby** [comment]
At the end of the line in `settings.bat` that begins with `set JAVA_PARAMETERS=...` add ` -Duser.language=en -Duser.country=US`

Note that this needs to be separated from what is already there by a space.
