### ISSUE TITLE
pack not installable via twitch launcher

### ISSUE THREAD

**Issue by MattDahEpic** [DarkPacks/SkyFactory-4#1352]
The pack is not currently installable via the twitch launcher. The pack does appear to be installable via MultiMC, albiet with the `bedpatch` mod missing.

The twitch log notes the error `("message": "Modpack addon id: 296062 does not exist in the database")`, though I can't determine if the mod with curseforge id 296062 is in fact bedpatch.

**Comment by sam-kirby** [comment]
This is an issue with Twitch. If you try installing again a few hours later it should work, or you can use multimc or ATLauncher to install the pack.
