### ISSUE TITLE
Tutorial inconsistency

### ISSUE THREAD

**Issue by mihaitacgeorge** [DarkPacks/SkyFactory-4#1355]
In the "tutorial", the book jumps from building a "drying rack" to "using cottonwood saplings" without ever mentioning them before, what they are, how you are supposed to get them.
If this is to be considered an actual tutorial, more effort and consideration towards the player has to be put in it.
As of now, it looks like a project more than anything.

**Comment by sam-kirby** [comment]
The tutorial has already introduced the concept of using saplings/trees for resources by this point; giving a use for the cottonwood sapling implies its existence as well as what it is. This is less an inconsistency and more an omission for brevity's sake.

As the tutorial is aimed at someone who has played modded minecraft before - though perhaps not in too much depth - it shouldn't be a great leap for the player to search in JEI for a cottonwood sapling - particularly given that recipes are only described in one advancement so the player must be doing this already anyway.

I feel it is also worth pointing out that this entire pack is a "project" put together by a bunch of volunteers who want to make something interesting for others to enjoy. We welcome constructive feedback, but being dismissive about what has been achieved generally won't meet with the best response. Please keep that in mind if you submit another issue.

I'm closing this as, in my view, there is nothing left unaddressed.
