### ISSUE TITLE
ore excavating mod not working

### ISSUE THREAD

**Issue by zombieslayerwtf** [DarkPacks/SkyFactory-4#1357]
## Bug Report
block does break in area when held the hotkey

## Expected Behaviour
when holding the hotkey then break a block it should break all nearby block that is the same as the broken one

## Possible Solution
??

## Steps to Reproduce (for bugs)

1.idk, this? https://www.youtube.com/watch?v=uUnGkCFdLMk
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: sky factory 4

* Prestige: true

* Modpack Version world created in: 4.1.0

* Additional Content Installed:

## Client Information

* Modpack Version:4.1.0
* Java Version:
* Launcher Used:official minecraft launcher
* Memory Allocated:
* Server/LAN/Single Player:single
* Optifine Installed:true
* Shaders Enabled:false

## Server Information
* Java Version:
* Operating System:windows
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
> Prestige: true

Have you unlocked it?

**Comment by zombieslayerwtf** [comment]
> > Prestige: true
> 
> Have you unlocked it?

realized it. thanks
