### ISSUE TITLE
Cant start world Error: java.lang.NullPointerException: Ticking block entity

### ISSUE THREAD

**Issue by Amanhem** [DarkPacks/SkyFactory-4#1368]
## Bug Report
I suddenly cannot start my save file anymore. I get errors about a ticking entity. The problem seems to follow the world folder.

## Possible Solution
Have tried fresh installs of the modpack to no avail

## Logs
* Client/Server Log: https://gist.github.com/Amanhem/f2a9c01512cb194b27f1eb5ba348f8e8
* Crash Log: https://pastebin.com/4DfNG7PY

## World Information
* Preset: Default
* Prestige:  No
* Modpack Version world created in: 4.1.0

## Client Information
* Modpack Version:4.1.0
* Java Version: 1.8.0.51
* Launcher Used: Twitch
* Memory Allocated: 4554
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sam-kirby** [comment]
Caused by a conflict between ender core and industrial foregoing meaning bottles cannot be placed in the potion maker.

Either restore a backup of your world or use Forge's remove erroring tile entities config option.
