### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by fdu2019xzy** [DarkPacks/SkyFactory-4#1369]
## Bug Report

Server Crash when starting the ServerStart.bat

## Logs

* Crash Log:
![image](https://user-images.githubusercontent.com/59246000/73085606-e5bf5a80-3f09-11ea-942f-b96097aa906b.png)

## Server Information
* Java Version:1.8.0_241
* Operating System:Win10

**Comment by sam-kirby** [comment]
Normally this failure means that you are somehow missing the vanilla Minecraft jar. I suggest you start over and make sure to follow all the steps in the setup document. If you need further assistance the best place to ask is the Discord.
