### ISSUE TITLE
Cannot Launch SkyFactory 4 (On SSD now and just transferred files from hard drive)

### ISSUE THREAD

**Issue by forshale** [DarkPacks/SkyFactory-4#1382]
## Bug Report
 
My Game will not boot up or load past the launcher and am being forced to use the legacy launcher, and is having an error (which i will copy paste later) which is (mostly) focusing on the dedicated ram.

## Expected Behaviour

Game should launch with (ideally) 8gb dedicated

## Possible Solution

(no idea tbh)

## Steps to Reproduce (for bugs)

I get multiple different crash reports depending on what I do so I'll do different number sets for each.
(using Jar launcher cause it doesnt work with native, and 1.8.0.241)
1.      Profile options
2. Dont use system memory
3. Set memory to 8192 mb
4. Press play, and Play in legacy launcher
I'm then hit with the following https://prnt.sc/r6ql6a and https://prnt.sc/r6qloy

1. Use System memory
2. Play & Play
Get hit with this https://prnt.sc/r6qm0t

1.  Dont use system Memory and set to 4gb
Hit with same exact error as 8gb

If I set to any other memory I either get the error from case one, or from case two.  
NOTE: I just set it to 4095 Mb after writing the previous and, while not working I got a god awful crash report  

## Logs

https://pastebin.com/rFkDEYGH (launcher crash report)

* Client/Server Log:
* Crash Log:

## World Information - N/A

* Preset:

* Prestige: 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version: 4.1.0
* Java Version: 1.8.0.241 (the 13.0 etc. in twitch doesn't work)
* Launcher Used: Twitch
* Memory Allocated: Everything between 2048 and 8192 mb
* Server/LAN/Single Player: 
* Optifine Installed: 
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
You are using a 32-bit version of Java which cannot handle the memory requirements of this pack. Please install a 64-bit version and use that instead.
