### ISSUE TITLE
Infinite amounts of any item you want using the Item transfer node by cyclic

### ISSUE THREAD

**Issue by phonybolony** [DarkPacks/SkyFactory-4#1405]
Basically it is very simple. If you make an Item Transfer Node by **cyclic**, and you also make a filing cabinet **Real Filing Cabinet**. You can get infinite amounts of any item you want, simply place that item in the Item Transfer node, and also creating a file for that item. Then put that file in the filing cabinet and use the GPS by **Cyclic** on that filing cabinet. Put the GPS back into the item transfer node and BOOM infinite amounts of that item. Pls fix, accidentally found bug with my friend trying to make a bonsai storage :).

**Comment by sam-kirby** [comment]
Closed by dfd8dbb0ee9c226e9d0f0f4becf4bb5da0a5e766
