### ISSUE TITLE
Ghosty Pig Sounds

### ISSUE THREAD

**Issue by nukerojbt** [DarkPacks/SkyFactory-4#1406]
I have a problem with skyfactory 4

I am in my world and I hear the sound of a pig but it is nothing there.

I have even pressed the combination f3 + B to see the hit boxes and there is nothing

**Comment by RaySmith-ttc** [comment]
From the first of April. Look at your character model

**Comment by nukerojbt** [comment]
NICE!!!...I'm a Pig!!!!!

:D
![APRILFOOL2020](https://user-images.githubusercontent.com/62990655/78160488-52902d00-7444-11ea-9dd0-13c3c15b220d.jpg)
