### ISSUE TITLE
Crash while i open the world

### ISSUE THREAD

**Issue by kenibenf** [DarkPacks/SkyFactory-4#1411]
idk what it is
[crash-2020-04-04_20.23.47-server.txt](https://github.com/DarkPacks/SkyFactory-4/files/4432212/crash-2020-04-04_20.23.47-server.txt)
![Cattura](https://user-images.githubusercontent.com/63164661/78458553-8bcdd480-76b2-11ea-8ed5-bcec617173ac.JPG)

**Comment by sam-kirby** [comment]
Your world has become corrupted. Restore from a backup.

**Comment by kenibenf** [comment]
> Your world has become corrupted. Restore from a backup.

how?

**Comment by sam-kirby** [comment]
I don't know, that information isn't in the log.
