### ISSUE TITLE
Twilight Forest Portal doesn't work

### ISSUE THREAD

**Issue by Pujji-mc** [DarkPacks/SkyFactory-4#1418]
## Bug Report
I have built the TF Portal and it also hums along, but when I enter it I am not teleported. I have no chance of getting into the TF right now.

## Expected Behaviour
After the portal was built and you enter it you should be teleported into the TF Dimension.

## Steps to Reproduce (for bugs)
![2020-04-12_10 33 27](https://user-images.githubusercontent.com/63535201/79064525-d3072700-7ca9-11ea-8421-df9cc40329bf.png)

## Logs
* Client/Server Log: https://gist.github.com/Pujji-mc/d433c8d5e3fb1389fd12f809298f26aa
* Crash Log: No Crash

## World Information
Topography: Sky Factory 4.5
Prestige is enabled
Installed Versinon: 2.0
Additional Content Installed:
None

## Client Information
* Modpack Version: Sky Factory 4.5 re
* Java Version: Java 8 Update 241 (64-Bit)
* Launcher Used: TechnicLauncher
* Memory Allocated: 8 GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sam-kirby** [comment]
This is not a pack made by us. As such, I don't know how anything works there.

The latest official release is 4.1.0, you can download it on Twitch or ATLauncher, or through MultiMC.
