### ISSUE TITLE
Prestige BIG PROBLEM

### ISSUE THREAD

**Issue by VoXterX** [DarkPacks/SkyFactory-4#1420]
Hi , i have a problem with prestige , this morning i prestige for the hopper bonsai and i coming back this afternoon and i see the hopper bonsai i created this morning in unfamilliar item and in the new block prestige hopper is blue and activated , thanks for help

**Comment by sam-kirby** [comment]
There may have been a problem storing your game stage information. Try running the command `/gamestage add @p bonsai_trees` and see if it resolves it.

**Comment by VoXterX** [comment]
ok thanks i will do that now

**Comment by VoXterX** [comment]
It 

> There may have been a problem storing your game stage information. Try running the command `/gamestage add @p bonsai_trees` and see if it resolves it.

It say i dont have the permission
