### ISSUE TITLE
Crafting the Wireless Crafting Terminal

### ISSUE THREAD

**Issue by GladBody22** [DarkPacks/SkyFactory-4#1421]
I am trying to make the Wireless crafting terminal in the latest version of Skyfactory 4. The crafting recipe calls for a normal Wireless Terminal, and a Crafting Terminal next to each other in the crafting grid. Well, I'm doing that and it's not doing anything. Whatsoever. This really needs to be looked into.

**Comment by sam-kirby** [comment]
The mod which adds the wireless crafting terminal is not in this pack and we do not support modifications to the pack.
