### ISSUE TITLE
Crafting Conflicts Can't Craft Dirt Or Crushing Tub

### ISSUE THREAD

**Issue by CharlieMort** [DarkPacks/SkyFactory-4#1424]
I started a server and me and my friends joined and we were unable to craft dirt with acorns and resin. To start the server i transferred the config files from the twitch instance to the server and also transferred the mods. Im not sure if this is the right way but we cant progress through your modpack. Could you please help.

**Comment by sam-kirby** [comment]
Download the server files from the following link and follow the ReadMe included.

If you need support, please use the discord in future.
