### ISSUE TITLE
topography mod crash

### ISSUE THREAD

**Issue by kingnakosa** [DarkPacks/SkyFactory-4#1427]
## Bug Report

When I start up my server It starts up like it should but the server crashes before it is done because the topography mod has an error everytime. I have added more than enough ram and nothing I do can fix it.
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: any

* Prestige: 

* Modpack Version world created in: newest (4.1.0)

* Additional Content Installed:

## Client Information

* Modpack Version: newest (4.1.0)
* Java Version: 8
* Launcher Used:
* Memory Allocated: 12gb
* Server/LAN/Single Player: server
* Optifine Installed: no
* Shaders Enabled: no

## Server Information
* Java Version: 8
* Operating System: windows 64-bit
* Hoster/Hosting Solution: my own computer
* Sponge (Non-Vanilla Forge) Server:

Crash logs:
[Skyfactory 4 crash.txt](https://github.com/DarkPacks/SkyFactory-4/files/4518522/Skyfactory.4.crash.txt)
[Skyfactory 4 crash.txt](https://github.com/DarkPacks/SkyFactory-4/files/4518525/Skyfactory.4.crash.txt)

**Comment by sam-kirby** [comment]
There is an error in your server.properties file which is causing this crash; check your `generator-setting` variable is valid.
