### ISSUE TITLE
games crashes

### ISSUE THREAD

**Issue by dxd1234** [DarkPacks/SkyFactory-4#1429]
each time i go to enter my world its crashes right before loading in with the error
java.lang.IllegalArgumentException: Name and ID cannot both be blank
im no good with coding so i am in need of some help

**Comment by sam-kirby** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critical information, we can't help you. So if you would like to report the issue again please re-create an issue using the provided template.

[Click here to make a new issue](https://github.com/DarkPacks/SkyFactory-4/issues/new/choose)

Thanks again for reporting, and we hope you enjoy the pack!
