### ISSUE TITLE
Uranium Bacon Melts to Steel in Smeltery

### ISSUE THREAD

**Issue by Darkosto** [DarkPacks/SkyFactory-4#1430]
Just checked, looks like steel is being created when trying to smelt Uranium Bacon. Other recipes in grinders/crushers work just fine. 

I haven't worked out where exactly the issue is occurring yet.

**Comment by sam-kirby** [comment]
Duplicate of #451

**Comment by sam-kirby** [comment]
Closed by dfd8dbb0ee9c226e9d0f0f4becf4bb5da0a5e766
