### ISSUE TITLE
I can't craft Draconium Seeds.

### ISSUE THREAD

**Issue by cfGAMEcf1** [DarkPacks/SkyFactory-4#1432]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Given Draconic Evolution is not in the pack, I'm not surprised.

**Comment by cfGAMEcf1** [comment]
I do have it in there, still not working.

**Comment by TheGamingOtaku** [comment]
Do you still need help?

**Comment by cfGAMEcf1** [comment]
No, thank you though for replying. I got it.

TheGamingOtaku <notifications@github.com> schrieb am Mi., 4. Nov. 2020,
03:49:
