### ISSUE TITLE
I can't craft Draconium Seeds.

### ISSUE THREAD

**Issue by cfGAMEcf1** [DarkPacks/SkyFactory-4#1433]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in: 1.12.2

* Additional Content Installed: Mystical Agriculture and Draconic Evolution

## Client Information

* Modpack Version: 1.12.2
* Java Version:
* Launcher Used: ATLauncher
* Memory Allocated: 11000
* Server/LAN/Single Player:
* Optifine Installed: Yes
* Shaders Enabled: No

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
As previously stated, Draconic Evolution is not part of this pack.
