### ISSUE TITLE
Matter Overdrive crashing my server on startup

### ISSUE THREAD

**Issue by FarmerMisShelley** [DarkPacks/SkyFactory-4#1439]
My server is crashing with an issue with NBTTags on startup when its trying to load Matter overdrive. Please help!

I'm posting the crash report here
[](https://pastebin.com/LcfLiBBF)

Not good at these posts so sorry if I used a wrong format

**Comment by justinrusso** [comment]
Thank you for reporting an issue! But as stated in the issue template, any issues which don't follow the format will be closed.

We created the issue template to help us help you! Without that critical information, we can't help you or it may be much more difficult. So if you would like to report the issue, please re-create an issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
