### ISSUE TITLE
Achievement Glitch: Relocking?

### ISSUE THREAD

**Issue by Twofirstnamesandtrustable** [DarkPacks/SkyFactory-4#1443]
My game crashed twice-but I think that's just because of my computer. I'm only including this because I don't know if it's related to the bug.

I played yesterday and everything was fine, then today when I tried loading in my world, all of my achievements that I had unlocked weren't marked as unlocked. I had completely finished all but two of the tabs, the enchantment tab and the 'all the things' tab. 

Going back to the starting tab, even the 'getting started' achievement wasn't blue.

**Comment by sam-kirby** [comment]
Likely corrupted as a result of the system crashes. I suggest you restore from a backup. If you need assistance with this, I recommend you use the Discord server: https://discord.gg/darkosto
