### ISSUE TITLE
bonsai bug

### ISSUE THREAD

**Issue by olioliox** [DarkPacks/SkyFactory-4#1448]
when you delete your island and make a new one your old bonsais count we had 29 on are old one me and my friend are only allowed to place 1 bonsai on are new island to break the old ones we would have to build over 4k blocks away to are old base i dont know what do to all we can do really is to build 4k blocks away to break some bonsais

**Comment by sam-kirby** [comment]
What do you mean they "count"?

**Comment by olioliox** [comment]
as in theres a limit for bansais turns out its only my friend that cant place them i can place them fine its really wierd

**Comment by sam-kirby** [comment]
There is no limit on the number of bonsais. Are you playing on a server?
