### ISSUE TITLE
Cannot connect to my own minecraft server

### ISSUE THREAD

**Issue by asdfghjkl403622** [DarkPacks/SkyFactory-4#1449]
Hi!
I made my own Minecraft server on Debian so I can Play with my friends. Right now, I am just testing so I am connecting through localHost. So when I try and connect though, I get this error: 
`[21:49:49] [Server Connector #1/ERROR] [minecraft/GuiConnecting]: Couldn't connect to server
io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: localhost/127.0.0.1:25565
	at io.netty.channel.unix.Socket.finishConnect(..)(Unknown Source) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
Caused by: io.netty.channel.unix.Errors$NativeConnectException: syscall:getsockopt(..) failed: Connection refused
	... 1 more`
this was pulled directly from the logs. I don't know what this means, and when I try to search the error or parts of it, I either get nothing or a solution for something completely different.

**Comment by sam-kirby** [comment]
Far easier to answer this sort of thing on Discord - there isn't such a lag between messages.

When you post there, could you please give details on whether the server acknowledges the connection attempt and any output in the server console.

**Comment by asdfghjkl403622** [comment]
alright, I'll do that
