### ISSUE TITLE
Gunpowder duping

### ISSUE THREAD

**Issue by yakyakyakyak** [DarkPacks/SkyFactory-4#1452]
I made a basic mob farm with an IF Mob Crusher into a chest, then into a cyclic Item Transfer Node which would go into a filing cabinet in my simple storage system. I am getting thousands of gunpowder in my filing cabinet, but none is moving out of the item transfer node.

**Comment by helpfulchicken** [comment]
Yea there's a known duplication bug with "Cyclic" wireless Item Transfer Nodes sending items into "Real Filing Cabinets" filing cabinets. Same issue as #1088

**Comment by yakyakyakyak** [comment]
Thanks makes sense. Living up to your name.

**Comment by somebody3232** [comment]
There's a much bigger duping problem with the parabox

**Comment by sam-kirby** [comment]
Closed by dfd8dbb0ee9c226e9d0f0f4becf4bb5da0a5e766
