### ISSUE TITLE
Prestige mod issues

### ISSUE THREAD

**Issue by Skroeske** [DarkPacks/SkyFactory-4#1453]
First of all, great pack :).
Unfortunately i have some issues with the prestige mod. I finished the first page in the advancement book and spent a point to hopping bonsai trees. I've crafted some of the hopping bonsai's to automate my farm.
After a while i wanted to upgrade my bonsai farm, but then i noticed that i couldnt craft the hopping bonsai's anymore. I tried to reload the world, restarted minecraft and tried to disable the mod and enable it again but nothing worked. Hope someone can help me with this issue, if not i'm afraid to restart my world.

**Comment by helpfulchicken** [comment]
Pretty tough to tell what the issue might be without more info. I've seen on other tickets here that they're point people to their Discord for support. Hopefully you can find someone to discuss it with you there. https://discord.gg/darkosto
