### ISSUE TITLE
StartServer.Bat

### ISSUE THREAD

**Issue by ExpiredMilk** [DarkPacks/SkyFactory-4#1457]
hey im having a really hard time trying to run this program and it seems to be a common problem between me and my friends. We all click startserver.bat to start our server but we all have the problem where the command prompt shows for a short second and then its gone. I've changed the EULA to true so i am a little bit confused on what to do next 
it would be really appreciated from me and my mates if you have a fix for this :)

**Comment by sam-kirby** [comment]
Likely, you don't have the server component of the java runtime installed. The easiest way to get hold of it is to install the JDK, or alternatively remove `-server` from the start script.
