### ISSUE TITLE
Unable to Install Missing Addon #284139

### ISSUE THREAD

**Issue by WiseMack** [DarkPacks/SkyFactory-4#1458]
## Bug Report
Error Message when installing through twitch
     This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 284139

## Expected Behaviour
Proper instalation

## Steps to Reproduce (for bugs)
1.Attempt to install the pack trough Twitch's mod downloader

## Logs
The installer deletes the download folder in instances, no idea where twitch's logs are.

## World Information
Does not Apply

## Client Information

* Modpack Version: 4.1.0
* Tested with the "Included Java Version", I did not know this computer didn't have Java installed, and have played Sky Factory 3 less than an hour ago.
* Java Version: Version 8 Update 251 Tested with this a few minutes ago.
* Launcher Used: Twitch
* Memory Allocated: Does not Apply
* Server/LAN/Single Player: Does not Apply
* Optifine Installed: Does not Apply
* Shaders Enabled: Does not Apply

## Server Information
Does not Apply

**Comment by sam-kirby** [comment]
I've just tested this and the pack installed fine. This issue occurs periodically with the Twitch launcher and ordinarily trying again in a few hours results in a successful installation.

Alternatively you can download the pack through MultiMC or the ATLauncher.
