### ISSUE TITLE
more cauldrens stopped working 

### ISSUE THREAD

**Issue by CTLDragon19** [DarkPacks/SkyFactory-4#1459]
so i was trying to automate lava for smelters and when lava went into the xnet system my game crashed i had to install MCedit to delete the xnet controller but at first i thought it was the cauldron(it was a cobblestone cauldron)but i think i might have deleted something more and cant fix it I've updated the more cauldrons mod and xnet and the stuff for xnet and Inspirations to hopefully fix it but the cauldron still wont accept the cobblestone for lava

**Comment by sam-kirby** [comment]
The updated mods are likely incompatible with the scripting which adds the cauldron's recipes. I recommend you install a clean version of the pack and copy your world across into it.
