### ISSUE TITLE
Skyfactory4 crash:1 user:pigbull320 ,No known cause.

### ISSUE THREAD

**Issue by Pigbull320** [DarkPacks/SkyFactory-4#1466]
Crash on clicking lost cities cake for first time while raining, didn't happen again once world was loaded up and downfall was toggled. LAN was open. Game was using about >60% RAM allocated.

## Logs
* Crash Log:

<script src="https://gist.github.com/Pigbull320/cb15c61f555976f93237728c454cd50b.js"></script>

## World Information
Default world
* Preset:
Default preset
* Prestige: 
No
* Modpack Version world created in:
4.1.0
* Modpack Version:
4.1.0
* Java Version:
jre1.8.0_251 (not sure if thats the version or path)
* Launcher Used:
MultiMC 5
* Memory Allocated:
Min: 1024 MB
Max 6016 MB
PermGen: 512 MB

* Java Runtime
JVM arguements: -Dfml.readTimeout=240
//This is to avoid a bug that causes the game to crash while loading worlds. Works wonderfully, may be default on other launchers
* Server/LAN/Single Player:
Singeplayer with LAN open to allow cheats to toggle downfall for FPS issues
* Optifine Installed:
No
* Shaders Enabled:
No

* SECOND CRASH. WILL MAKE SEPERATE REPORT, JUST ADDING INCASE HELPFUL.
<script src="https://gist.github.com/Pigbull320/16f6bd85af312e0811a04b875dae908c.js"></script>

**Comment by Pigbull320** [comment]
I'm and idiot, thought it would embed automatically. Sorry. let me know if you need the gist link or something else, its public under the same name as title (skyfactory4 crash:1 user:pigbulll320).

**Comment by sam-kirby** [comment]
Open To LAN does not close successfully, we know this happens though I'm unsure whether anyone has looked into why. Generally it freezes indefinitely, here you have a CME, both imply there is some kind of race condition occurring which are some of the hardest bugs to determine the cause of, and as we do not support Minecraft's Integrated Server in general this will likely not be resolved.

**Comment by Pigbull320** [comment]
> Open To LAN does not close successfully, we know this happens though I'm unsure whether anyone has looked into why. Generally it freezes indefinitely, here you have a CME, both imply there is some kind of race condition occurring which are some of the hardest bugs to determine the cause of, and as we do not support Minecraft's Integrated Server in LAN mode in general this will likely not be resolved.

Ah so the bug is due to LAN? Not some ossue with my ram or a mod? I cant read logs, much thanks for taking a look and stuff.
