### ISSUE TITLE
Some of the items from Tinkers Construct are missing

### ISSUE THREAD

**Issue by SillyWilly01** [DarkPacks/SkyFactory-4#1470]
There are multiple items from Tinkers Construct missing. I am on 4.1.0 and trying to make a forge, but the controller and drains are missing

**Comment by sam-kirby** [comment]
You have neglected to fill out the requested information, so I'm going to take a wild guess. You're playing with Prestige enabled, though decided not to read the tooltip, or the welcome message, or the pack description, or anything else. The fact you didn't even read the issue template supports this, though hopefully you do read the rest of this comment.

You therefore don't realise that, by enabling prestige, you have chosen to lock certain items from certain mods (e.g. the Smeltery) until you purchase them using prestige points in the menu accessible by pressing `P`.

There are several ways to earn prestige points, including advancements and the parabox. Rewards you unlock will be available on all future single player prestige worlds you play on.
