### ISSUE TITLE
Like my 12th crash with this modpack...

### ISSUE THREAD

**Issue by Pigbull320** [DarkPacks/SkyFactory-4#1472]
Placed a mekanism enrichment chamber down, went to upgrades, clicked on the speed upgrades to remove them, clicked the remove/dump button, it removed the 5 upgrades, i was still spam clicking it, crashed.

## World Information
Default world
* Preset:
Default preset
* Prestige: 
No
* Modpack Version world created in:
4.1.0
* Modpack Version:
4.1.0
* Java Version:
jre1.8.0_251 (not sure if thats the version or path)
* Launcher Used:
MultiMC 5
* Memory Allocated:
Min: 1024 MB
Max 8960 MB
PermGen: 512 MB

* Java Runtime
JVM arguments: -Dfml.readTimeout=240
//This is to avoid a bug that causes the game to crash while loading worlds. Works wonderfully, may be default on other launchers
* Server/LAN/Single Player:
singleplayer with LAN CLOSED (not open)
* Optifine Installed:
No
* Shaders Enabled:
No

* crash log
https://paste.ee/p/DIjCz

theres the launcher log, and heres the file incase you need it:
[crash-2020-05-29_06.57.03-client.txt](https://github.com/DarkPacks/SkyFactory-4/files/4701395/crash-2020-05-29_06.57.03-client.txt)

**Comment by sam-kirby** [comment]
See mekanism/Mekanism#5625
