### ISSUE TITLE
Prestige not working (SF4)

### ISSUE THREAD

**Issue by ScrappysHyper** [DarkPacks/SkyFactory-4#1475]
prestige was not enabled on my Skyfactory 4 server and we played for a bit. But then I wanted to enable it. So i went into the prestige config and enabled it client side and on the server and told my friends to do it aswell. When we hop on the server, the prestige system is not locking items, everything is unlocked even though prestige is on. None of the items turn to unfirmiliar items like they're supposed to and I need help to apply prestige properly to the server. Please help  Thanks

**Comment by sam-kirby** [comment]
Prestige does not activate retroactively. There was no need to change anything on the clients.

Either start again or delete the playerdata (note this will also delete inventories/exp/etc.).

**Comment by ScrappysHyper** [comment]
> Prestige does not activate retroactively. There was no need to change anything on the clients.
> Either start again or delete the playerdata (note this will also delete inventories/exp/etc.).

Thank you so much this has been bothering me for so long. God bless<3
