### ISSUE TITLE
My single player world is stuck on "Loading world"

### ISSUE THREAD

**Issue by Juri03** [DarkPacks/SkyFactory-4#1481]
## Bug Report

I've been playing my single player world on Mac in Skyfactory 1.12.2 for over a month a I spend quite a lot of time in it so I don't want to lose my progress. I crafted a Mechanical Brewing Stand from Industrial Foregoing and I putted a glass bottle in every single slot of it to test how it works, when I putted the glass bottles in one of th else's the game crashed. When I restarted my game, I loaded my world but it was stuck on "Loading world"
Please help

## Expected Behaviour

When I'm trying to load the world, it keeps saying "Loading world" forever.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: SkyFactory4

* Prestige: I don't know how to enable/diasble it so it's the standard configuration

* Modpack Version world created in: 4.1.0

* Additional Content Installed: None

## Client Information

* Modpack Version: 4.1.0
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
You should probably just restore a backup

**Comment by Juri03** [comment]
Thanks for the help, I did that but it's still a bug if you put a water
bottle in the wrong slot in any of the Brewing things which are not from
the vanilla version the game crashes. I just found out in the latest
version. I hope youre trying to fix that
Thank you
Juri

Sam Kirby <notifications@github.com> schrieb am Di., 9. Juni 2020, 19:07:

**Comment by sam-kirby** [comment]
You cannot insert bottles into the correct side of the potion brewer at this time, we are aware of this issue and will look at resolving it in the next pack update.

**Comment by Juri03** [comment]
Ok thank you didnt expect such a big team behind the modpack and its bugs

Sam Kirby <notifications@github.com> schrieb am Di., 9. Juni 2020, 19:36:
