### ISSUE TITLE
When I try to use a tool when it's durability gets low it just doesn't break anything anymore.

### ISSUE THREAD

**Issue by Crazygamer255** [DarkPacks/SkyFactory-4#1484]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset:

* Prestige: 

* Modpack Version world created in:

* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
This is deliberate, your tools can be repaired by combining with the material they are constructed from in a crafting grid.
