### ISSUE TITLE
Potion brewer Destroyed my save

### ISSUE THREAD

**Issue by 0solair** [DarkPacks/SkyFactory-4#1485]
## Bug Report
When placing a water bottle in the wrong slot of a potion brewer my game crashed and would crash again any time i attempted to start the world up again, forcing me to revert to a backup.

## Expected Behaviour
I dont think that part of the potion brewer is supposed to do anything but i know for sure it aint supposed to make your world unplayable.

## Possible Solution
Only modification i have made to my game is allocating 6G of memory instead of 3k mb twitch launcher allocates

## Steps to Reproduce (for bugs)
https://i.imgur.com/5AKy3gz.mp4
1. Get a bottle of water
2. Open up a potion brewer
3. Place bottle into one of the empty slots near the fluid gauge
## Logs

* Client/Server Log: https://gist.github.com/0solair/6d07ef2f2393b9edece813226339fe24
* Crash Log: https://gist.github.com/0solair/764d77e3dd5123267277d3b00c6ef438

## World Information
* Preset: Skyfactory 4

* Prestige: Nope

* Modpack Version world created in: 4.1.0

* Additional Content Installed: none

## Client Information

* Modpack Version: 4.1.0
* Java Version:
* Launcher Used: Twitch
* Memory Allocated: 6G
* Server/LAN/Single Player: Single
* Optifine Installed: not on twitch
* Shaders Enabled: not on twitch

**Comment by sam-kirby** [comment]
You can use Forge's Remove Erroring Tile Entities option to recover your existing world, if you need detailed instructions on this please use the Discord: https://discord.gg/darkosto

**Comment by sam-kirby** [comment]
Closed by dfd8dbb0ee9c226e9d0f0f4becf4bb5da0a5e766
