### ISSUE TITLE
Server mods not loading

### ISSUE THREAD

**Issue by Bruhgang** [DarkPacks/SkyFactory-4#1486]
## Bug Report
Server crashes even though all mods works on client
I'm using the server files that you gave on curseforge

## Steps to Reproduce (for bugs)
start the server
[crash-2020-06-13_21.45.08-server.txt](https://github.com/DarkPacks/SkyFactory-4/files/4776290/crash-2020-06-13_21.45.08-server.txt)

## Logs
*Server Log: https://pastebin.pl/view/b6866f78
* Crash Log: https://pastebin.pl/view/8c9f0dbb

## World Information
does not needed (I hope).

## Client Information

* Modpack Version: 4.1.0
* Java Version: jre1.8.0_251
* Launcher Used: Crashes on server startup
* Memory Allocated: 6G
* Server/LAN/Single Player: server
* Optifine Installed: no
* Shaders Enabled: no

## Server Information
* Java Version: jre1.8.0_251
* Operating System: Windows 10
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
This is due to a language issue on the server. Cyclic is using localised names for properties, which is invalid. You must start the server using a language that does not contain characters that are invalid in NBT key names.

You can start the server in English by adding the following argument:
`-Duser.language=en`

To do this, open Settings.bat and add this to the end of the line that begins `set JAVA_PARAMETERS=`

**Comment by Bruhgang** [comment]
> This is due to a language issue on the server. Cyclic is using localised names for properties, which is invalid. You must start the server using a language that does not contain characters that are invalid in NBT key names.
> 
> You can start the server in English by adding the following argument:
> `-Duser.language=en`
> 
> To do this, open Settings.bat and add this to the end of the line that begins `set JAVA_PARAMETERS=`

Well, it didn't work. Still gives the same crash report.

**Comment by sam-kirby** [comment]
Can you please share the new crash report?

**Comment by Bruhgang** [comment]
Here you go: https://pastebin.pl/view/9c4c6791

**Comment by sam-kirby** [comment]
Your crash report says there are no JVM Flags. This means what I suggested isn’t actually being applied. How are you starting the server? Using StartServer.bat?

**Comment by Bruhgang** [comment]
I start the server using forge universal (1.12.2-14.23.5.2838)
Btw, should settings.bat close almost immediately after starting?

**Comment by sam-kirby** [comment]
Settings.bat isn't meant to be run directly.

If StartServer.bat is closing immediately, edit it and remove `-server`.

If you need further help with this, please use the Discord - https://discord.gg/darkosto
