### ISSUE TITLE
Sky Factory 4 achievements reset!

### ISSUE THREAD

**Issue by EyeoftheCyclops1** [DarkPacks/SkyFactory-4#1489]
All of my achievements in SF4 Reset. I've been trying to get them back by redoing all the achievements but now I'm stuck on Eat your heart out. Any ideas! I was thinking of just cheating and giving myself the achievements I lost but I can't find the achievement ID's online!!!

**Comment by sam-kirby** [comment]
Advancement ID's can be found using the folder structure and script names here: https://github.com/DarkPacks/SkyFactory-4/tree/master/src/config/triumph/script

The first folder becomes the resource location's domain (bit before the colon), further folders and the script name (minus extension) form the resource location's path (bit after the colon).

For example, the ID of Eat Your Heart Out is:
`sf4:age_enhancement/heartcontainer`

If this happens again in the future however, you'd be better off restoring a backup

**Comment by EyeoftheCyclops1** [comment]
Sorry I’ve been able to get all the achievements except this one, I tried the ID you gave me but it did not work, unless i’m using the command wrong. Do you mind typing thee full command, my ign is EyeoftheCyclops1 if that helps! Immanuel Isho From: Sam KirbySent: June 19, 2020 6:00 AMTo: DarkPacks/SkyFactory-4Cc: EyeoftheCyclops1; AuthorSubject: Re: [DarkPacks/SkyFactory-4] Sky Factory 4 achievements reset! (#1489) Advancement ID's can be found using the folder structure and script names here: https://github.com/DarkPacks/SkyFactory-4/tree/master/src/config/triumph/scriptThe first folder becomes the resource location's domain (bit before the colon), further folders and the script name (minus extension) form the resource location's path (bit after the colon).For example, the ID of Eat Your Heart Out is:sf4:age_enhancement/heartcontainerIf this happens again in the future however, you'd be better off restoring a backup—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
