### ISSUE TITLE
Can't get the achievement DarkToasto and Eat Your Heart Out!!!!

### ISSUE THREAD

**Issue by EyeoftheCyclops1** [DarkPacks/SkyFactory-4#1490]
I have tried multiple times to do the DarkToasto achievement! I have made it multiple times with no success! I have tried naming the BLT Sandwich, I have tried naming the End result to DarkToasto and I followed each ingredient correctly! As for the Eat Your Heart Out, my achievements got reset and I already had to many of the Heart Containers and cannot consume anymore. I have tried to find the ID for the achievement online with no luck, and when I got help last time the command he sent me didn't work. I may have been putting in the wrong command though. If you could give me the full command that would be amazing. My IGN is EyeoftheCyclops1 if that helps! Thanks!!!

**Comment by sam-kirby** [comment]
`/advancement grant @p only sf4:age_enhancement/heartcontainer`
