### ISSUE TITLE
Unable to create Magnesium Diboride Solenoid

### ISSUE THREAD

**Issue by darkmage0707077** [DarkPacks/SkyFactory-4#1494]
## Bug Report
When attempting to start Nuclearcraft, I'm unable to create the above Solenoids; the recipe appears to be broken.

![2020-06-23_13 08 55](https://user-images.githubusercontent.com/30854209/85433664-beb99300-b552-11ea-927a-841be80c2cc1.png)

![2020-06-23_13 03 15](https://user-images.githubusercontent.com/30854209/85433331-481c9580-b552-11ea-8109-e77f9bbff086.png)

## Expected Behaviour

![2020-06-23_13 06 16](https://user-images.githubusercontent.com/30854209/85433384-5ff41980-b552-11ea-861e-a915c4c6454b.png)

## World Information
* Preset: Skyfactory 4 (Default)
* Prestige: Yes
* Modpack Version world created in: 1.12.2
* Additional Content Installed: None

## Client Information
Modpack Version: 1.12.2
Java Version: 1.8.0.51
Launcher Used: Twitch
Memory Allocated: 6144M
Server/LAN/Single Player: Single Player
Optifine Installed: No
Shaders Enabled: No

**Comment by sam-kirby** [comment]
The two ingots in the centre of this recipe are supposed to be Tough Alloy, not Magnesium Diboride. It is a little unfortunate how close the texture is.
