### ISSUE TITLE
yellow dye

### ISSUE THREAD

**Issue by adamplant3** [DarkPacks/SkyFactory-4#1496]
## Context

 there is no way to get yellow dye when spawning in certain biomes, when playing my play through i got all the way to gold dust before realizing the only way to get it was through the flowers and despite using 3 stacks of bone meal the only flowers i got were blue orchids.

**Comment by sam-kirby** [comment]
You can:
  1) leave the swamp
  2) use Cyclic's magic beans which give you random seeds and dyes when harvested and can be crafted
