### ISSUE TITLE
Client crashing every 5-10 minutes.

### ISSUE THREAD

**Issue by aweb-01** [DarkPacks/SkyFactory-4#1503]
## Bug Description

The client crashes while playing every 5 or 10 minutes. I've tried both the Twitch and MultiMC launcher. I've also increased RAM allocation to 6GB, doesn't seem to help. Any ideas? This issue does not happen to other players on the server.

### Did this behavior use to work in the previous version?

Only tried on this version.

## Steps to Reproduce (for bugs)

1. Play Sky Factory 4 for a few minutes, then it'll crash randomly in a variety of scenarios.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:
I have two logs.
One from twitch launcher: https://pastebin.com/mH5gJiTS
One from multiMC launcher: https://pastebin.com/iX03UMe3

## World Information
* World Preset:
* Prestige Enabled: No
* Modpack Version world created in:
* Additional Content Installed:
Running 4.1.0 server. 

## Client Information
* Modpack Version: 4.1.0
* Java Version: v8 update 251
* Launcher Used: both Twitch and MultiMC
* Memory Allocated: default of 3.6something, and then I increased to 6128. No change.
* Server/LAN/Single Player: Server (beastnode, 4GB server)
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sam-kirby** [comment]
This crash is graphics driver related.

Are you expecting the game to be running on your Intel integrated GPU?

If so, make sure the driver is the latest available from Intel's website.

**Comment by aweb-01** [comment]
> This crash is graphics driver related.
> 
> Are you expecting the game to be running on your Intel integrated GPU?
> 
> If so, make sure the driver is the latest available from Intel's website.

Hmm, no, I’m expecting the game to be running on my Nvidia GTX 1660 Ti... is there a setting somewhere to force it to my GPU?

**Comment by aweb-01** [comment]
Forcing java runtime to use my Nvidia GPU fixed it, thanks!
