### ISSUE TITLE
Fix Sky orchads Saplings in hand or dropped in world

### ISSUE THREAD

**Issue by ZombieKonsti** [DarkPacks/SkyFactory-4#1504]
## Context

 As we know the textures of Sky Orchads Saplings are off if held in hand or dropped in the world. This file if placed in the right directory should fix it.

## Config/Script Details (if desired)
 Place this file into a new directory, being resources/sky_orchads/blockstates 
Note: the file needs to be renamed to json format, as json can't be uploaded here
[ore_sapling.txt](https://github.com/DarkPacks/SkyFactory-4/files/4871436/ore_sapling.txt)

**Comment by justinrusso** [comment]
I am a bit confused here. I just checked the blockstate JSON file from Sky Orchards and it appears to be the same as what you included in your text. Should there be a difference? I'm not sure what would be resolved otherwise by your suggestion.

```javascript
{
   "forge_marker":1,
   "defaults":{
      "textures":{
         "sapling":"sky_orchards:blocks/ore_sapling"
      },
      "model":"sky_orchards:ore_sapling"
   },
   "variants":{
      "stage":{
         "0":{
             "model":"sky_orchards:ore_sapling"
         },
         "1":{
             "model":"sky_orchards:ore_sapling"
         }
      },
      "inventory":[
         {
            "textures":{
               "sapling":"sky_orchards:blocks/ore_sapling"
            },
            "model":"sky_orchards:ore_sapling"
         }
      ]
   }
}
```

**Comment by sam-kirby** [comment]
```diff
23c23
<                 "model": "sky_orchards:item/ore_sapling"
---
>                 "model": "sky_orchards:ore_sapling"
```

**Comment by justinrusso** [comment]
Must not have been very awake this morning. Thanks, @sam-kirby 😄 . Turns out I had misspelled sky_orchards when testing.
