### ISSUE TITLE
Server crash when starting

### ISSUE THREAD

**Issue by Crawfort** [DarkPacks/SkyFactory-4#1510]
## Bug Description
I am trying to open a server on my own computer. First of all, I ran install.bat and the files were installed. Then the server start bat. I run, verify "eula" and run it again. After waiting a few minutes in the console, it gave a few errors and closed.

I do not know much about these issues and the problem may be caused by my computer. I tried them by downloading the latest version of server and minecraft files from Curseforge (4.1.0).

### Did this behavior use to work in the previous version?
Its my first time on this mode

## Steps to Reproduce (for bugs)
1.I am trying to open a server on my own computer. First of all, I ran install.bat and the files were installed. 
2. Then the server start bat. I run, verify "eula" and run it again. 
3. After waiting a few minutes in the console, it gave a few errors and closed.

## Logs
* Client/Server Log: https://pastebin.pl/view/3d0dd90f
* Crash Log: https://pastebin.pl/view/1a842da0

## World Information
* World Preset: -
* Prestige Enabled:  no
* Modpack Version world created in: 4.1.0
* Additional Content Installed: no

## Client Information
* Modpack Version: 4.1.0
* Java Version: Version 8 Update 251
* Launcher Used: twitch and atlauncher
* Memory Allocated: 6gb
* Server/LAN/Single Player: Server
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:  Version 8 Update 251
* Operating System: Windows 10
* Hoster/Hosting Solution: Myself
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Cyclic currently causes a crash if starting on a server whose operating system uses a language that makes use of characters that do not appear in ASCII. To override this without changing your whole OS language, you can add the argument `-Duser.language=en` to tell Java to use English for the server. This does not affect the client and you should still see everything that has translations in your chosen language when playing the game.

To add this argument using the included batch files, open `settings.bat` and find the line that begins `set JAVA_PARAMETERS=`. At the end of the line, add a space and then `-Duser.language=en`.
