### ISSUE TITLE
Full player invulnerability (including /kill), after falling into forgiving void with Cyclic's glowing chorus effect

### ISSUE THREAD

**Issue by Jack-McKalling** [DarkPacks/SkyFactory-4#1511]
## Bug Description

After falling into the void and landing safely back down on the ground _while_ under the effects of Glowing Chorus (from Cyclic mod), you will be completely invulnerable. Nothing will be able to damage or kill you. Using `/kill <player>` will report success but nothing actually happens.

I tested block suffocation, mobs attacking me, throwing ender pearls, falling too high, getting poison from a witch, even the kill command, but nothing hurts. Drinking milk to get rid of the (unused) flying time from the glowing chorus does remove this invulnerability, although I didn't test that thoroughly under as many circumstances as the bug.

### Did this behavior use to work in the previous version?

Don't know how to install previous version with ATLauncher / never played it

## Steps to Reproduce (for bugs)

1. Create new world; survival, allow cheats, disable prestige, default classic preset "Sky Factory 4"
2. Run `/give <playername> cyclicmagic:glowing_chorus` and eat it
3. Fall off the island into the void, and while falling back to it aim to touch ground
   > note you will not take damage as expected, due to glowing chorus preventing fall damage
4. Run  `/kill <playername>`
   > :x: You're still alive

## Logs

* Client/Server Log: https://gist.github.com/Jack-McKalling/af768b4860d4096b71c31856a71c16af (includes game booting)
* Crash Log:

## World Information
* World Preset: default classic Sky Factory 4
* Prestige Enabled: no
* Modpack Version world created in: 4.1.0
* Additional Content Installed: no

## Client Information
* Modpack Version: 4.1.0
* Java Version: 1.8.0_251
* Launcher Used: ATLauncher 3.3.5.2
* Memory Allocated: min 2.048MB; max 8.192MB; permgen: 128MB
* Server/LAN/Single Player: single player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by sam-kirby** [comment]
Updating Forgiving Void resolves this - probably fixed by this commit blay09/ForgivingVoid@a7688d20a3f89e50b192098aaf022f1f70b1577c

As this update is already in the development version of SF4, this issue will be closed.

**Comment by sam-kirby** [comment]
Resolved by dfd8dbb0ee9c226e9d0f0f4becf4bb5da0a5e766
