### ISSUE TITLE
Can't crafting! (CraftTweaker2)

### ISSUE THREAD

**Issue by Aezukla** [DarkPacks/SkyFactory-4#1514]
## Bug Description

This bug is very strange. I cant use recipes CraftTweaker2. Idk why.

### Did this behavior use to work in the previous version?

Idk. (Playing only on last version)

## Steps to Reproduce (for bugs)

No steps. It just bug.

## Logs

* Client/Server Log: i cant, i dont have pastebin pro, and cant upload logs. more 512 kilobytes.
* Crash Log: No crashes.

## World Information
* World Preset:Sky Factory 4 (No tutorial version)
* Prestige Enabled:Yes
* Modpack Version world created in: 4.1.0
* Additional Content Installed:No.

## Client Information
* Modpack Version: 4.1.0
* Java Version: Java 8 Edition
* Launcher Used: TLauncher. (The pirate launcher)
* Memory Allocated:2.5Gb
* Server/LAN/Single Player: Singleplayer.
* Optifine Installed: No.
* Shaders Enabled: No.

**Comment by sam-kirby** [comment]
This pack is not officially hosted on TLauncher. We do not control whatever files you have downloaded.

This issue is not present in 4.1.0 as released by us on Curseforge.
