### ISSUE TITLE
iron duplication gkitch

### ISSUE THREAD

**Issue by Minecraftslayer92** [DarkPacks/SkyFactory-4#1515]
## Bug Description

duplicate bucket

### Did this behavior use to work in the previous version?

 i dont know

## Steps to Reproduce (for bugs)

1. get dirt and cobblestone
2.get a iron bucket and water source
3.put it together, and you get 2 buckets!

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset: pacafist
* Prestige Enabled: yes
* Modpack Version world created in: latest
* Additional Content Installed: none

## Client Information
* Modpack Version: 1.12.2
* Java Version: what?
* Launcher Used: new
* Memory Allocated: what?
* Server/LAN/Single Player:single
* Optifine Installed: no
* Shaders Enabled:no

**Comment by sam-kirby** [comment]
Fixed in 4.2.0
