### ISSUE TITLE
Buckets disappearing

### ISSUE THREAD

**Issue by Chodingstudent** [DarkPacks/SkyFactory-4#1534]
I was once playing the modpack and I got some lava from the cobblestone cauldron. I used a clay bucket to pick up the lava in it and placed it back down, and then the bucket disappeared. I don't know if this is intentional, so I am reporting it.

**Comment by sam-kirby** [comment]
Clay buckets "burn" if you use them to transport a hot fluid. This is intentional.

**Comment by Chodingstudent** [comment]
ok thanks
