### ISSUE TITLE
Sky Factory Server Wouldn't Start (4.2.1)

### ISSUE THREAD

**Issue by EnderGodz** [DarkPacks/SkyFactory-4#1542]
## Bug Description
- Server 4.2.1 Will Not Load

### Did this behavior use to work in the previous version?
 Yes, the previous version in which this bug was not present was: 4.2.0

## Steps to Reproduce (for bugs)
1. Start Server

## Logs
https://bytebin.lucko.me/ARzpNEFxfx

## World Information
* World Preset:Copied old world file into directory prior to starting server for 1st time
* Prestige Enabled:Yes
* Modpack Version world created in:4.0.1
* Additional Content Installed:None

## Client Information
* Modpack Version:4.2.1
* Java Version:java version "1.8.0_261", Java(TM) SE Runtime Environment (build 1.8.0_261-b12), Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

* Launcher Used:Twitch
* Memory Allocated:6 GBs
* Server/LAN/Single Player:Server
* Optifine Installed:No
* Shaders Enabled:Disabled

## Server Information
* Java Version:4.2.1
* Operating System:Windows 10 
* Hoster/Hosting Solution:Local PC
* Sponge (Non-Vanilla Forge) Server:N/A

**Comment by justinrusso** [comment]
I believe this should be fixed in the [4.2.2 release](https://www.curseforge.com/minecraft/modpacks/skyfactory-4/files/3012798).
