### ISSUE TITLE
Stone Factory Villager Breeding?

### ISSUE THREAD

**Issue by AnimeNerdDJBROS** [DarkPacks/SkyFactory-4#1545]
I've been wondering a simple issue for the Stone Factory modpack, how do you register something as a village, if you are to know the issue with my setup please tell me [This setup is something I based off a tutorial from a couple years ago.

[The supposed village interior]
![2020-07-24_07 39 31](https://user-images.githubusercontent.com/42410080/88387698-09f8d880-cd81-11ea-9f27-60a38e5c0beb.png)
[The exterior of the village cross]
![2020-07-24_07 39 39](https://user-images.githubusercontent.com/42410080/88387794-3f9dc180-cd81-11ea-8582-41a9acdd2538.png)
[Bellow the cross in the main setup of the actual breeder
![2020-07-24_07 43 31](https://user-images.githubusercontent.com/42410080/88387964-94413c80-cd81-11ea-9a53-701dccbd8d1d.png)

[Screenie showing minecraft isn't recognizing it as a village] 
![2020-07-24_07 45 54](https://user-images.githubusercontent.com/42410080/88388104-da969b80-cd81-11ea-9f9f-07fa9c95e805.png)

Link to the old village tutorial I used: https://www.youtube.com/watch?v=CKdRozLCpQY

If someone could help, would be appreciated, I just wanted to make my nitwits useful instead of just killing them.

**Comment by sam-kirby** [comment]
In this version of Minecraft, villages are calculated based on there being an inside and an outside. The outside area must be able to see the sky.

As you are buried underground, it is likely not possible to form a valid village in this world type.

**Comment by sam-kirby** [comment]
For more details, see here: https://minecraft.gamepedia.com/index.php?title=Village/Mechanics&oldid=1138193

**Comment by AnimeNerdDJBROS** [comment]
That's a bit annoying, oof.

**Comment by AnimeNerdDJBROS** [comment]
So I just wasted my time and space on something I couldn't have accomplished anyhow.

**Comment by AnimeNerdDJBROS** [comment]
Thats great.

**Comment by sam-kirby** [comment]
Hey, it's not my fault you didn't spend two minutes reading so that you understood what you were building and decided to blindly follow a tutorial.

**Comment by AnimeNerdDJBROS** [comment]
Not saying its your fault, just a little annoying , sorry if it came off that way LUL
