### ISSUE TITLE
Topography doesn't work on server 

### ISSUE THREAD

**Issue by TRR-Slimer** [DarkPacks/SkyFactory-4#1550]
## Bug Description

when I go onto the server none of the topography commands are there. the latest one is installed on the server and in my mods. it works on my single player world just not on the server

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:sky factory 4
* Prestige Enabled:yes
* Modpack Version world created in:

## Client Information
* Modpack Version:
* Java Version:8
* Launcher Used:forge
* Memory Allocated:4096 gb
* Server/LAN/Single Player:server
* Optifine Installed:no
* Shaders Enabled:no

## Server Information
* Java Version:8
* Operating System:java
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Topography works fine on a server.

Are you certain the server is configured correctly? Did you use the files from Curseforge and did you follow the included setup guide?

Can you include a server log?

**Comment by TRR-Slimer** [comment]
i made sure the server is configured right and yes i used the curse forge server download 
here's the log
[latest.log](https://github.com/DarkPacks/SkyFactory-4/files/4977906/latest.log)

**Comment by sam-kirby** [comment]
You are running a vanilla Minecraft server. Topography is a mod, you must run a Forge server.
