### ISSUE TITLE
Registry mismatch server/client

### ISSUE THREAD

**Issue by TRR-Slimer** [DarkPacks/SkyFactory-4#1554]
## Bug Description

when I try to join the server I get kicked for **internal exception: com.google.common.util.concurrent.uncheckedexecutionexeption:java.lang.illegalstateexeption: recipe minecraft:wooden_door (net.minecraft.item.crafting.shapedrecipes@2ec23ec3) produces unregistered item minecraft:wooden_door (net.minecraft.item.itemdoor@4b475742)** I have reinstalled the server and forge and neither fix the problem 

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:https://paste.ubuntu.com/p/SgHkb4btPF/
* Crash Log:

## World Information
* World Preset:sky factory 4
* Prestige Enabled:yes
* Modpack Version world created in:

## Client Information
* Modpack Version:4.1
* Java Version:8
* Launcher Used:forge
* Memory Allocated:6gb
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:8
* Operating System:forge
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Could you please share in addition to this the crafttweaker logs from client and server?

They are **not** stored in the logs folder, but in the folder above.

**Comment by sam-kirby** [comment]
latest.log from your client would also be helpful.

**Comment by TRR-Slimer** [comment]
craft tweaker log
[crafttweaker.log](https://github.com/DarkPacks/SkyFactory-4/files/4990004/crafttweaker.log)

forge log
[latest.log](https://github.com/DarkPacks/SkyFactory-4/files/4990007/latest.log)

**Comment by sam-kirby** [comment]
Your client looks to be missing an awful lot of files. You are missing all recipes and custom items added through scripts on the client, you are missing textures, and further the config does not match the server's config (implying these were also missing so defaults are being used).

This looks like you've taken the mod list and assumed that's all you need to run the pack. This is not the case and your install is broken.

We cannot support you in installing the pack manually, so I suggest you use a modpack launcher. This pack is released on Twitch Launcher, ATLauncher and Curseforge (allowing you to use MultiMC).
