### ISSUE TITLE
I cant place water in the nether anymore

### ISSUE THREAD

**Issue by Skyfrostgaming** [DarkPacks/SkyFactory-4#1556]
## Bug Description
Basically, as title says my server is not letting me place water in the nether anymore, however singleplayer worlds are

## Steps to Reproduce (for bugs)
 no
* Modpack Version world created in: 4.1.0
* Additional Content Installed:
Iptifine

## Client Information
* Modpack Version: 4.1.0
* Java Version: 1.12.2
* Launcher Used: twitch
* Memory Allocated: about 7gb
* Server/LAN/Single Player: server
* Optifine Installed: yes
* Shaders Enabled: no

## Server Information
* Java Version: 1.12.2
* Operating System: windows 10
* Hoster/Hosting Solution:<!-- mcprohosting.com

**Comment by Skyfrostgaming** [comment]
Excuse what. I followed the template exactly

**Comment by sam-kirby** [comment]
You removed the Logs section. The bot is correct. If you edit your answer to follow the template, the bot will reopen the issue.

**Comment by sam-kirby** [comment]
Also the World Information section.
