### ISSUE TITLE
Access to the path 'C:\Users\HP\Twitch\Minecraft\Instances\SkyFactory 4\overrides\config\triumph\script\sf4\age_allthethingsomglol\cookiesingularityjar.txt' is denied.

### ISSUE THREAD

**Issue by Zilence123** [DarkPacks/SkyFactory-4#1558]
## Bug Description

Whenever i try to install Skyfactory 4 that problem happens .

### Did this behavior use to work in the previous version?

i didnt play previous versions, but even if i try to install it, problem is same.

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in: 1.12.2
* Additional Content Installed:

## Client Information
* Modpack Version: 4.2.2
* Java Version: 1.8.0.181 (64 Bit)
* Launcher Used: Minecraft Launcher
* Memory Allocated: 6400 MB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sam-kirby** [comment]
This sounds like an issue with file permissions on your computer, or an issue with the Twitch launcher. Neither of these are things we can help with.

You could try posting on the discord and seeing if anyone has had any similar issues, but you're probably better off approaching Twitch for support.


https://discord.gg/darkosto
