### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by hungreman** [DarkPacks/SkyFactory-4#1563]
[crash-2020-07-29_02.31.03-server.txt](https://github.com/DarkPacks/SkyFactory-4/files/4993024/crash-2020-07-29_02.31.03-server.txt)

## Bug Description
 The server crashes after a few seconds.

## Steps to Reproduce (for bugs)

1. Launch Forge.jar universal file
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by hacker104** [comment]
what's the version of the modpack

**Comment by hungreman** [comment]
What ever the newest version is i just downloaded both of them.
Im having another separate error where the Server is running out of memory but i allocated 10gbs for it so i dont understand that either but at 247mb its maxed out on read out on the server

**Comment by hacker104** [comment]
try using this 
`java -jar forge-1.12.2-14.23.5.2838-universal.jar`

**Comment by sam-kirby** [comment]
You are only giving the game 247MB of RAM. The SF4 server requires way more than this, on the scale of 3-4GB. The command given by hacker104 does not change this.

I suggest you use the provided start script,, which will properly set the RAM limits as defined in Settings.bat, or read more about Java and the available arguments available.
