### ISSUE TITLE
Connection to APEXminecrafthosting

### ISSUE THREAD

**Issue by MrSnizzle** [DarkPacks/SkyFactory-4#1566]
## Bug Description
Any time I try to load into my server that is running on APEXMINECRAFTHOSTING I get an error message saying the client has outdated mods than what is running on APEX.

### Did this behavior use to work in the previous version?
First time trying out SkyFactory

## Steps to Reproduce (for bugs)
1. Start blank server with minecraft 1.12.2 jar file
2. Stop the server after loaded and change to SkyFactory4 jar file
3. Change the server.properties to load the default settings for a normal game.
4. Start the server.
5. Try connecting with the BETA and the CURRENT versions in the Twitch Launcher.

## Logs
https://pastebin.com/fucxGczd

## World Information
* World Preset: generator-settings={"Topography-Preset":"Sky Factory 4"}
level-type=DEFAULT
* Prestige Enabled: true
* Modpack Version world created in: Only one available in APEXMINECRAFTHOSTING
* Additional Content Installed: None

## Client Information
* Modpack Version: 4.2.2 AND 4.1.0 (Current Release)
* Java Version:
* Launcher Used: Twitch
* Memory Allocated: Standard
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: N/A
* Operating System: N/A
* Hoster/Hosting Solution: APEXMINECRAFTHOSTING
* Sponge (Non-Vanilla Forge) Server: N/A

**Comment by sam-kirby** [comment]
Apex indicate they use the 4.2.2 server files. https://apexminecrafthosting.com/sky-factory-4/

Your log is from a 4.1.0 client.

If you cannot connect to the server using a 4.2.2 client you will have to contact Apex for assisstance. This is not our issue.
