### ISSUE TITLE
Missing Textures with Bonsai Trees

### ISSUE THREAD

**Issue by AlleinSoldat** [DarkPacks/SkyFactory-4#1573]
Version 4.2.2, Placed several Trees to be grown in Bonsai Tree Hoppers. I was using a resource pack prior to without any issues. However, with the resource pack removed, it appears some of the textures are missing. Attached is a screenshot I took.
![2020-08-02_17 36 58](https://user-images.githubusercontent.com/30380842/89136234-7a24fe00-d4e7-11ea-8b76-55abd48edeeb.png)

**Comment by sam-kirby** [comment]
This would likely be resolved by reloading the game.
