### ISSUE TITLE
Skyfactory Will Not Launch and Opens Outdated Launcher

### ISSUE THREAD

**Issue by wystera** [DarkPacks/SkyFactory-4#1575]
I am trying to download SF4 on Mac. I am using Twitch to do so. When I click play, it opens "Minecraft Launcher 1.6.91." And when I try to click play, it crashes. The first image is the launcher, and the second is the crash report.

<img width="909" alt="Screen Shot 2020-08-03 at 3 23 51 PM" src="https://user-images.githubusercontent.com/69169875/89223821-7788de00-d5a5-11ea-87cb-8fca4a22f8fa.png">
<img width="899" alt="Screen Shot 2020-08-03 at 3 31 53 PM" src="https://user-images.githubusercontent.com/69169875/89223865-88395400-d5a5-11ea-8ae5-ce72446bf12a.png">

**Comment by sam-kirby** [comment]
You are using a version of Java that is incompatible with Minecraft Forge for 1.12.2. Please either use Java 8, or switch to the native launcher in Twitch settings. For further assistance with this please use the Discord - https://discord.gg/darkosto
