### ISSUE TITLE
Cant Change Server World Type

### ISSUE THREAD

**Issue by Ticskter** [DarkPacks/SkyFactory-4#1591]
Hello all. I have a personal server that i am running of a Second PC for some friends and I to play on. currently it is a Sky Block world and my friends want it to be the "Traditional" type of world. i closed the server and modified the server.properties file and changed
generator-settings={"Topography-Preset":"SkyFactory4"} to
generator-settings={"Topography-Preset":"Default"}.
but when i connect to the server it still loads the existing world which is the sky block world. i dont know if it matters or not, but i've also changed the "level-type" setting from "DEFAULT" to "Default" as it says in the SkyFactory 4 Multiplayer Instructions.pdf

i do appologize if this has been posted before, but i was unable to find it

Thank, you,
Tick

**Comment by sam-kirby** [comment]
Changing the type of the world does not apply retroactively. New chunks you generate will follow the new settings.

You can either travel/teleport yourself far away from your old island, or delete/move your previous world by removing the world folder from the server.
