### ISSUE TITLE
This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 274456

### ISSUE THREAD

**Issue by rjvip111** [DarkPacks/SkyFactory-4#1593]
## Bug Description

when i try to install skyfactory it says This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 274456

### Did this behavior use to work in the previous version?

Yes it used to work in the previous version

## Steps to Reproduce (for bugs)

when i try installing skyfactory it says This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 274456

1.
2.
3.

## Logs

* Client/Server Log:its not installed yet
* Crash Log:This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 274456

## World Information
* World Preset:skyfactory isnt installed yet
* Prestige Enabled:skyfactory isnt installed yet
* Modpack Version world created in:skyfactory isnt installed yet
* Additional Content Installed:skyfactory isnt installed yet

## Client Information
* Modpack Version:1.12.1
* Java Version:idk
* Launcher Used:twitch
* Memory Allocated:skyfactory isnt installed yet
* Server/LAN/Single Player:skyfactory isnt installed yet
* Optifine Installed:before it was
* Shaders Enabled:skyfactory isnt installed yet

**Comment by random0931847** [comment]
I have the same problem

**Comment by sam-kirby** [comment]
What version of the pack are you trying to install? I have no idea what you're referring to with 1.12.1.

**Comment by sam-kirby** [comment]
The pack downloads and installs fine on my end (v 4.2.2).

Further, the ID referenced does not appear in our manifest.

This appears to be a recurring though occasional twitch issue, there is nothing we can do to resolve it. It usually resolves itself in a few hours.

You could try installing through another launcher if you can't wait that long though. Both MultiMC and ATLauncher are also supported.
