### ISSUE TITLE
cannot brake any block 

### ISSUE THREAD

**Issue by utsanslover16** [DarkPacks/SkyFactory-4#1601]
## Steps to Reproduce (for bugs)
 

1. Join a server on aternos
2. Try to barke any block 
3. And autoplaces back

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
If you are not an op on the server then you cannot break blocks around spawn due to Vanilla Minecraft's spawn protection.

Either make yourself an op using `/op <username>` on the server console or create a new island for yourself using the commands detailed in the wiki or server operators guide.

**Comment by utsanslover16** [comment]
thank you for nothing

**Comment by sam-kirby** [comment]
I answered your issue, there is no need to be rude.

**Comment by sam-kirby** [comment]
If there is more information that you need, you can just ask. There's no reason to get confrontational.

**Comment by utsanslover16** [comment]
okay sorry i got nervous anyways i'll check it out
