### ISSUE TITLE
chests on crafting station have the purple and black texture

### ISSUE THREAD

**Issue by yetyeeter1337** [DarkPacks/SkyFactory-4#1602]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by sam-kirby** [comment]
This will not be resolved:

https://github.com/SlimeKnights/TinkersConstruct/issues/3721
