### ISSUE TITLE
ReactorCraft modpack addition

### ISSUE THREAD

**Issue by Kjller12** [DarkPacks/SkyFactory-4#1603]
Dear darkosto, Blargerist, and Firstnecron,

      I would like to recommend that a whole mod pack named Reactor craft be added to Sky Factory 4 because it would add more content and has a big reactor in the ReactorCraft mod (Fusion Reactor).
     ReactorCraft modpack
https://www.curseforge.com/minecraft/mc-mods/reactorcraft, https://www.curseforge.com/minecraft/mc-mods/rotarycraft, https://www.curseforge.com/minecraft/mc-mods/dragonapi, https://www.curseforge.com/minecraft/mc-mods/electricraft.
And that is it from me if you accept it i would appreciate it.

From,
UEnchanter

**Comment by Kjller12** [comment]
you do need DragonAPI in order to use the rest that is how he set it up (the creator of the mods).

**Comment by sam-kirby** [comment]
We cannot use these mods due to licensing concerns.

**Comment by Kjller12** [comment]
That is understandable. Thank you for the explanation.
