### ISSUE TITLE
Duping glitch

### ISSUE THREAD

**Issue by zayyanabbas** [DarkPacks/SkyFactory-4#1613]
###  Bug Description
You can dupe any item to millions in minutes using just a filing cabinet, item sorter and a hopper.

### Did this behavior use to work in the previous version?
Didn't check, but it works on 4.1

## Steps to Reproduce (for bugs)
1. Put an item sorter on a filing cabinet with a folder containing the item you want to dupe
2. Make an exception on the item sorter allowing the item to pass through 
3. Put in the item you want to dupe in the hopper. If you put 1 of the item in, it goes at about 100 every few seconds, but the more items you put into the hopper the faster it goes. I think it can take 64 max due to item sorter's internal storage.

## Logs
N/A

## World Information
* World Preset: Classic
* Prestige Enabled: Disabled
* Modpack Version world created in: 4.1
* Additional Content Installed: N/A

## Client Information
* Modpack Version: 4.1
* Java Version: 1.12.2
* Launcher Used: Tlauncher
* Memory Allocated: 
* Server/LAN/Single Player: Singleplayer but works when opened to LAN
* Optifine Installed: N/A
* Shaders Enabled: N/A

**Comment by sam-kirby** [comment]
This is resolved in the latest release, 4.2.2. Please play that instead.

Ref: https://github.com/DarkPacks/SkyFactory-4/issues/1088#issuecomment-649228306
