### ISSUE TITLE
Can someone help me? I want to know how to make lava in the cauldrons of More Cauldrons and Inspirations Mod with Craft Tweaker

### ISSUE THREAD

**Issue by GabrielOsvair** [DarkPacks/SkyFactory-4#1617]

**Comment by GabrielOsvair** [comment]
Can someone help me set up Craft Tweaker on my modpack?

**Comment by sam-kirby** [comment]
This Github is for issue reports relating to the modpack SkyFactory 4. It is not a help desk for any single mod within the pack.

Crafttweaker has documentation on this topic, you should start there

https://docs.blamejared.com/1.12/en/Mods/Modtweaker/Inspirations/Handlers/Cauldron/

Should you require further support, Crafttweaker has a discord with support channels where you may be able to get help. I would not advise turning up without having read the documentation though, as that is a good way to waste everyone's time.

http://discord.blamejared.com/
