### ISSUE TITLE
Topography failing to load world.

### ISSUE THREAD

**Issue by GlowingUmbreon** [DarkPacks/SkyFactory-4#1622]
## Bug Description

Launching my main world appears to always error, I as not sure if this is due to world corruption, or if it was something I done which caused it so I've decided to make a bug report. My world currently has no machines other than a simple storage network that is connected to chests that bonsai hoppers automatically deposit into. The storage goes through multiple chunks.

### Did this behavior use to work in the previous version?

Unsure

## Steps to Reproduce (for bugs)

Unsure

## Logs

* Client/Server Log: https://gist.github.com/GlowingUmbreon/98843f5742bdf59709472b8740087af9
* Crash Log: https://pastebin.com/7f9WK4Ec

## World Information
* World Preset: Topography - Default (Sky Factory 4)
* Prestige Enabled: No
* Modpack Version world created in: 4.2.2
* Additional Content Installed: None

## Client Information
* Modpack Version: 4.2.2
* Java Version: ```java version "1.8.0_261" 
Java(TM) SE Runtime Environment (build 1.8.0_261-b12) 
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)```
* Launcher Used: Twitch
* Memory Allocated: 5120MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sam-kirby** [comment]
Topography is not the problem; your `level.dat` file is corrupted, Topography just happens to be the first thing to try and read it.

Restore a backup.
