### ISSUE TITLE
Remove non-prestige mode restrictions

### ISSUE THREAD

**Issue by TheSouthernSanta** [DarkPacks/SkyFactory-4#1632]
## Context

I believe that there should be no restrictions while playing non-prestige mode

By adding prestige mode to the game, you are essentially saying that skyfactory is not challenging enough. And that is understandable. However by locking many mods behind a "pay wall" for prestige, those who want to leasurely play the game as it is without messing with prestige are unable to do so. I know you have had this come up before over the past year or so, but I simply want to play without any restrictions, but the prestige system forces you to play by restrictions regardless if you play prestige or not. If you choose not to play prestige mode, you're permanently locked out from many mods. Otherwise if you play prestige, some basic mods get locked to you before you can access them with a long and repetitive points grind. Some people like playing like this, but I for one do not like restrictions. You may say there are no restrictions in your response, however I have checked that I am unable to use/access Project E in non-prestige mode, so I am sure there are some restrictions like that still in place.

**Comment by sam-kirby** [comment]
As you correctly stated, this has been addressed before. The position has not changed.

If prestige mode was not in the pack, then Project E would also have been excluded. It is deliberately disabled when playing non-prestige for reasons of balance.

It is false to state that many mods are disabled when playing non-prestige. Only Project E and Parabox are disabled. Parabox would be useless outside of prestige.

Nobody should be charging you for prestige points. We certainly don't. I believe to do so would be against Mojang's EULA.

**Comment by holly-hacker** [comment]
For people that got here through Google and just want to play the pack with ProjectE, you can change the unlock criteria in the config file. In your minecraft folder, check `config/prestige/rewards.json` and look for an entry with identifier `projecte_world`. There you can change the cost to 0 and remove it's `projecte` parent:
![image](https://github.com/DarkPacks/SkyFactory-4/assets/13605369/39996ca4-211c-430b-a41e-7b87b8a80c15)

Then, remove `projecte_world` as a child from `projecte`:
![image](https://github.com/DarkPacks/SkyFactory-4/assets/13605369/28586595-40ca-463c-a406-8ec99cadc8a1)

You can now buy the ProjectE world from any prestige world for 0 points. Use the <kbd>P</kbd> keybind to get there.

I understand the balancing reasons for which ProjectE is disabled, but I just want to try it out without having to invest hours into another save. I don't need a perfectly balanced game to have fun and an option that says "I know the balancing is off, just let me play this" would have been very much appreciated.

**Comment by sam-kirby** [comment]
That's an interesting approach; if I'm interpreting correctly it will unlock ProjectE only on that specific world type. If you want to enable ProjectE on an existing world, you can run `/gamestage add @p project_e`, or if you want to have ProjectE unlocked automatically on any non-prestige world you create in future add `stages.projectE` to the `addPrestigeDisabledGamestage` array at https://github.com/DarkPacks/SkyFactory-4/blob/master/src/scripts/crafttweaker/prestige.zs#L187-L215

**Comment by holly-hacker** [comment]
No, this will change the price for unlocking the ProjectE world preset, which would require unlocking ProjectE in a prestige world for 100 points, and then unlocking the world preset for another 250 points. This change removes the dependency on ProjectE and makes the preset unlock free. Nothing will change gameplay-wise to other worlds/saves/prestige modes. ProjectE is still only available in Prestige runs that have it unlocked, or on the specific ProjectE world preset.
