### ISSUE TITLE
out dated client

### ISSUE THREAD

**Issue by 113wasddsaw311** [DarkPacks/SkyFactory-4#1634]
#1458  Bug Description

it is using the 1.6.9 client

### Did this behaviour use to work in the previous version?

it worked fine until I tried to play sf3 as well

## Steps to Reproduce (for bugs)

I'm not 100% sure but I think this is how to reproduce it
1.download sf4 on twitch
2.download sf3 on twitch
3.play sf3
4.and both should be on the out dated client

## Logs

* Client/Server Log:-
* Crash Log:-

## World Information
* World Preset:-
* Prestige Enabled:-
* Modpack Version world created in:-
* Additional Content Installed:-

## Client Information
* Modpack Version:-
* Java Version:-
* Launcher Used:-
* Memory Allocated:-
* Server/LAN/Single Player:-
* Optifine Installed:-
* Shaders Enabled:-

**Comment by sam-kirby** [comment]
We have no control over the twitch launcher, please open a support request with them.
