### ISSUE TITLE
Applied Energistics 2

### ISSUE THREAD

**Issue by ENDERSTIXgaming** [DarkPacks/SkyFactory-4#1636]
I am trying to auto fuel nether star generators using nether stars in my ME system. I placed an import bus on the ME system and export buses on all the generators and cables connecting them all. I then placed nether stars in all the buses and nothing happened. I even connected an ME controller on all sides of it and still nothing. I tested in a creative world and even tried just moving nether stars from 1 chest to another and the items won't move. I even flipped the busses to see if I had it backwards and still nothing. I am 99% certain that something it wrong with the mod because everyone else I talk to is confused as well. either that or I'm missing something so can you please help. also I can't find a reference to any format if this is taken down please direct me to where the format is so I can follow it

**Comment by sam-kirby** [comment]
When you create an issue, there is a selection of templates to follow, see here: https://github.com/DarkPacks/SkyFactory-4/issues/new/choose

We do not accept issues that do not follow one of these templates.

This sounds more like an issue with your understanding of AE2. AE2 is primarily a storage mod, though it sounds like you're trying to use it as an advanced pipe. You can do this, replace your import bus with a storage bus and make sure you are supplying power to your "pipe" with an energy acceptor and it'll probably work. But you probably want to watch a few tutorials on the mod.

Further, you say you added a controller. This should not be possible in SF4, controllers are disabled. If you have deleted any configs or changed things, you probably want to reinstall the pack to revert these.

Please use the Discord server at https://discord.gg/darkosto if you have any further questions about how to play the game.
