### ISSUE TITLE
ProjectE Tlauncher problem

### ISSUE THREAD

**Issue by mcsmreceks** [DarkPacks/SkyFactory-4#1643]
## Bug Description

The ProjectE mod is not working on Tlauncher also on previous versions too all working but If I go to world singleplayer/multiplayer the mod dont have any items in the game but mod is in the modpack and loaded 

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:for first no then yes
* Modpack Version world created in:no

## Client Information
* Modpack Version:4.4.2
* Java Version:14.0.2
* Launcher Used:Tlauncher
* Memory Allocated:
* Server/LAN/Single Player:singleplayer/multiplayer
* Optifine Installed:yes
* Shaders Enabled:no

**Comment by sam-kirby** [comment]
This pack has not been released on the TLauncher. Whatever you're playing, it's not our responsibility.

**Comment by Vampireking171** [comment]
sam-kirby i have the same problem but for curseforge what is it?

**Comment by sam-kirby** [comment]
ProjectE is the final reward for prestige and is not unlocked any other way - even if you play without prestige. The modpack was not balanced around it and in our opinion it is not enjoyable to have it from the start. Should you disagree, you can enable it using cheats; I think the command is `/gamestage add @p project_e`
