### ISSUE TITLE
Add RandomPatches

### ISSUE THREAD

**Issue by Awakened-Redstone** [DarkPacks/SkyFactory-4#1644]
## Context

RandomPatches is a mod that add a patch to server timeout, it allows to set a max LivingTick timeout (Client side), Login timeout (Client side) and the LivingTick delay (when on server side)
By setting LivingTick timeout and login timeout I stopped having issues to login on the server, and I never got timed out again on server login.

## Mod Details
* Name: RandomPatches
* CurseForge Link: [https://www.curseforge.com/minecraft/mc-mods/randompatches](https://www.curseforge.com/minecraft/mc-mods/randompatches)

**Comment by Thornstromb** [comment]
Seconding this, as i had to manually add this to the pack in order to log into my single-player world due to sheer delay while loading the world.
