### ISSUE TITLE
Advancements have disappeared

### ISSUE THREAD

**Issue by loockeeer** [DarkPacks/SkyFactory-4#1655]
## Bug Description
After restarting my SkyFactory4 while the parabox was online, i realized that all the advancements have disappeared : 

![advancementsPage](https://i.ibb.co/YZnTY9p/image.png)

### Did this behavior use to work in the previous version?
We didn't use the parabox in the previous version

## Steps to Reproduce (for bugs)
1. Start the parabox
2. Restart the server

## Logs

No logs

## World Information
* World Preset: Classic
* Prestige Enabled: yes
* Modpack Version world created in: 4.1.0
* Additional Content Installed: Roost + Chickens + More Chickens + Iron Chests + WorldEdit + Optifine

## Client Information
* Modpack Version: 4.2.2
* Java Version: 8 (jre 1.8.0)
* Launcher Used: twitch
* Memory Allocated: 4 GB
* Server/LAN/Single Player: Server
* Optifine Installed: yes
* Shaders Enabled: no

## Server Information
* Java Version: 8 (jre 1.8.0)
* Operating System: linux
* Hoster/Hosting solution: BoxToPlay
* Sponge (Non-Vanilla Forge) Server: Only forge

**Comment by loockeeer** [comment]
I also can't craft a lot of items : pig seeds (and animal seeds in general), gas storage component (and storage components in general)

It really ruins the game

**Comment by sam-kirby** [comment]
Can you please upload your crafttweaker log from the server - you'll find it in the server's root directory named `crafttweaker.log`

**Comment by sam-kirby** [comment]
The latest log asked for in the template would also be helpful.

**Comment by loockeeer** [comment]
crafttweaker.log -> https://hastebin.com/ubemovokuj.md
debug.log -> https://hastebin.com/uqayoguxis.md
latest.log -> https://hastebin.com/elikuqoruv.sql

This is all the logs I have

**Comment by sam-kirby** [comment]
These logs are all incomplete and as a result not much use. It seems you're hitting a limit of hastebin - try using https://gist.github.com or https://paste.ubuntu.com - both have much more generous limits.

**Comment by loockeeer** [comment]
Mhh, no, they are complete

**Comment by sam-kirby** [comment]
They really aren't.

They are all exactly 2000 lines long. Both latest.log and debug.log should begin by printing information about Forge, instead latest begins during item registration whilst debug begins after a world has loaded. Both should begin something like the following:

```
[03:11:08] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[03:11:08] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[03:11:08] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[03:11:08] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_251, running on Mac OS X:x86_64:10.15.5, installed at /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
```

Meanwhile, crafttweaker.log should start with a list of patreons. Instead it begins about 80% of the way through at unification. If you want answers, please provide the information requested.

**Comment by loockeeer** [comment]
Oh sorry! I took the logs from a web interface, I didn't realize it was truncated at the beginning :/
https://gist.github.com/loockeeer/98ea317144dfdde6a4bad85f936c9cd2
