### ISSUE TITLE
Possible Crafttweaker issue

### ISSUE THREAD

**Issue by Juju8901** [DarkPacks/SkyFactory-4#1662]
## Bug Description
good Evening, I'm an admin on a new SF4 server trying to figure some things out. The crafting recipe for the dirt sapling isnt working, as well as the recipe for the crushing tub; and im also having problems with the dirt acorn not turning into a petrified acorn. Any help would be appreciated.
[23/9/2020 23:09:22 PM] [Client thread/ERROR]: Could not find any matching ingredients to remove: 1xtile.tconstruct.rack@0 tconstruct:rack
this is as much as i could find regarding this kind of error

*** I know This is Identical to an issue you closed out this morning, but we Reenabled Mystcraft and everything else is the same. I'm still encountering the same issue. Thank you for your time, and sorry about the trouble!***

I've also attached the new Crafttweaker.log

### Did this behavior use to work in the previous version?
N/A I havent played a previous version of SF4

## Steps to Reproduce (for bugs)
If i try to Craft a Crushing tub, it will not work
2.If i try to craft a Dirt sapling, it will not work.
If i try to make Dirt Acorns in to Petrified Acorns using a tinkers construct drying rack, it will not work.

## Logs
LOGS ATTACHED
CRAFTTWEAKER.LOG
[message (2).txt](https://github.com/DarkPacks/SkyFactory-4/files/5279512/message.2.txt)

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
World Preset:Survival
Prestige Enabled: yes
Modpack Version world created in:4.2.2
Additional Content Installed:N/A
Client Information
Modpack Version:4.2.2
Java Version: 8 update 261
Launcher Used: Twitch/ Curse
Memory Allocated: 10GBs
Server/LAN/Single Player:Server
Optifine Installed: no
Shaders Enabled:no

## Server Information
Operating System: LUbuntu

Hoster/Hosting Solution: Self Hosted

Sponge (Non-Vanilla Forge) Server: Hybrid

**Comment by sam-kirby** [comment]
This time you've disabled weirding gadgets.

**Comment by Juju8901** [comment]
> This time you've disabled weirding gadgets.

Okay, Instead of Making another ticket, can I send you the new file here on the new ticket?

**Comment by sam-kirby** [comment]
Sure

**Comment by Juju8901** [comment]
> Sure

[message (3).txt](https://github.com/DarkPacks/SkyFactory-4/files/5279624/message.3.txt)

Thank you again for helping me out

**Comment by sam-kirby** [comment]
There is no error here. Have you tried to craft a dirt sapling since re-enabling weirding gadgets?

**Comment by Juju8901** [comment]
Hey man, 

I'm an idiot. The second we reenabled everything, it came back up. 
Sorry for the trouble. The owner just was really adamant about not having chunk loaders or mystcraft in.
Again, thank you for your time. Is there any advice you would give us on that front? im trying to get him to just ban the items.
