### ISSUE TITLE
Cannot craft items

### ISSUE THREAD

**Issue by Decodeq** [DarkPacks/SkyFactory-4#1666]
## Bug Description

 Recently I have started playing skyfactory 4 on a server that I made. I tried to craft basic items such as: dirt amber or crushing tub. I followed the exact recipe and the output was blank. 

### Did this behavior use to work in the previous version?

I only did start playing on 1.12.2 so there is not enough sufficient evidence to answer this question to you.

## Steps to Reproduce (for bugs)

1.Start a new game of Skyfactory 4 on a fresh server.
2.Start playing the game normally until you reach 16 dirt resin and 16 dirt acorns.
3.Try to craft Dirt amber or Crushing hub

## Logs

* Client/Server Log:https://pastebin.com/STXD6mBy (Main logs) https://gist.github.com/Decodeq/18c70714bf6dab5ac9e166d30b07324e (Server logs)
* Crash Log:N/A

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed: N/A

## Client Information
* Modpack Version:4.2.2
* Java Version:Version 8 Update 261
* Launcher Used:Twitch installer
* Memory Allocated:4GB
* Server/LAN/Single Player:Server
* Optifine Installed:Yes
* Shaders Enabled:No

## Server Information
* Java Version:Version 8 Update 261
* Operating System:Windows 10
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Please upload your crafttweaker log from the server. Use a site such as https://gist.github.com as it will be too long for Pastebin.

**Comment by Decodeq** [comment]
> Please upload your crafttweaker log from the server. Use a site such as https://gist.github.com as it will be too long for Pastebin.

https://gist.github.com/Decodeq/18c70714bf6dab5ac9e166d30b07324e

**Comment by sam-kirby** [comment]
Sorry, I probably should have been clearer - I asked for the crafttweaker log, which is the file called `crafttweaker.log` in the server's root directory, **not** the logs directory. Could you please upload that.

**Comment by Decodeq** [comment]
https://gist.github.com/Decodeq/f6651fccdc16120f963e24f868ff2656

**Comment by sam-kirby** [comment]
Your server is lacking the scripts that set up custom recipes, make sure you're uploading the `scripts` folder from the server zip.

Setup instructions are included with the server files.
