### ISSUE TITLE
infinite wand is easily put into recipe automatically and the

### ISSUE THREAD

**Issue by klugemonkey** [DarkPacks/SkyFactory-4#1668]
## Bug Description
Infinite Wand given in CompactSky seems to get used in recipe as stick without player knowing and is unavailable to re-craft.

### Did this behavior use to work in the previous version?
Unknown

## Steps to Reproduce (for bugs)
Try to craft a recipe using JEI that requires a stick with the wand in your inventory.

## Logs
N/A

## World Information
* World Preset: CompactSky with 16
* Prestige Enabled: False
* Modpack Version world created in: 4.2.2
* Additional Content Installed:

## Client Information
* Modpack Version: 4.2.2
* Java Version: 1.8.0_242-ea
* Launcher Used: MultiMC
* Memory Allocated: 6G
* Server/LAN/Single Player: Multi
* Optifine Installed: None
* Shaders Enabled: None

## Server Information
* Java Version: graalvm-ce-java8-20.1.0
* Operating System: debian
* Hoster/Hosting Solution: self
* Sponge (Non-Vanilla Forge) Server: N/A

**Comment by sam-kirby** [comment]
Sorry; the "wand" is just a stick that happens to glow. It has no other uses, but to be crafted into something else.

It was included as a joke, I believe as Darkosto was being asked to include an early game builders wand repeatedly, and did not want to do so.
