### ISSUE TITLE
SkyFactory 4 server on PC world not loading

### ISSUE THREAD

**Issue by CurlyFries11** [DarkPacks/SkyFactory-4#1674]
## Bug Description

Locally hosting a server on my PC so a friend and I can play. Everything works perfectly except the SkyFactory 4 topography map. Instead it loads into a normal world with all the mods. Have tried creating the world in singleplayer and transferring it over to the server but doesn't work properly.

### Did this behavior use to work in the previous version?

N/A

## Steps to Reproduce (for bugs)

1.Launch Server
2.Join Server
3.Cry

## Logs

* Client/Server Log:[19:49:23 ERROR]: Exception handling console input
java.io.IOException: The handle is invalid
	at java.io.FileInputStream.readBytes(Native Method) ~[?:?]
	at java.io.FileInputStream.read(FileInputStream.java:279) ~[?:?]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:290) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:351) ~[?:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:185) ~[?:?]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:326) ~[?:?]
	at java.io.BufferedReader.readLine(BufferedReader.java:392) ~[?:?]
	at nz$2.run(SourceFile:100) [minecraft_server.1.12.2.jar:?]
* Crash Log:

## World Information
* World Preset:SkyFactory 4
* Prestige Enabled: No
* Modpack Version world created in: 1.12.1
* Additional Content Installed: No

## Client Information
* Modpack Version: 1.12.1
* Java Version:
* Launcher Used: Twitch
* Memory Allocated: 6GB
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: 1.12.2
* Operating System: Windows 10
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Did you download the server files from https://curseforge.com/minecraft/modpacks/skyfactory-4 and did you follow the instructions to choose the world type included?

**Comment by CurlyFries11** [comment]
Originally I had downloaded the server files through the twitch app, however I have just tried that direct link and the same issue occurs. I follow every instruction to the t

**Comment by sam-kirby** [comment]
Can you upload your server.properties file to a site such as https://pastebin.com and link to it here?

**Comment by CurlyFries11** [comment]
https://pastebin.com/T87hRS3A

**Comment by sam-kirby** [comment]
Okay - that looks fine. Can you upload your complete server log - when players join, their IP may appear in the log so you should go through first and filter them out.

**Comment by CurlyFries11** [comment]
https://pastebin.com/Y4DNm6gs

**Comment by sam-kirby** [comment]
That is a vanilla server, make sure you are using either the provided start script or invoking the forge jar with the necessary command line arguments using your own startup solution. Launching the `minecraft_server.1.12.2.jar` will always launch a vanilla server.
