### ISSUE TITLE
purple/black block crafting station

### ISSUE THREAD

**Issue by jarn123** [DarkPacks/SkyFactory-4#1685]
## Bug Description
 i see an purple/black block in the crafting station if i put an normal vanilla chest inside (if you close the crafting station)

### Did this behavior use to work in the previous version?
 idk

## Steps to Reproduce (for bugs)
 put an normal chest in the crafting station

1.put an normal chest in the crafting station
2.close crafting station
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version: 4.2.2
* Java Version: idk 
* Launcher Used: minecraft launcher
* Memory Allocated:
* Server/LAN/Single Player: singleplayer 
* Optifine Installed: no 
* Shaders Enabled: no

**Comment by sam-kirby** [comment]
The chest has a special rendering system to allow for the chest to open. This cannot be represented on the crafting table and will not be fixed.
