### ISSUE TITLE
Automatic Crash, after player loads World.

### ISSUE THREAD

**Issue by C0D3-M4513R** [DarkPacks/SkyFactory-4#1692]
## Bug Description

The Server crashes after 60s of loading the world.
The Machine, on wich the server ran is not important, because this bug keeps happening, when hosting the server on my local machine.
~~I have tested the world itself in another Server (from the archive I used to create the first one), but the issue does not occur.~~ This is true for my Windows machine, however on the Linux server itself, a new Server doesn't change a thing. Furthermore: The contents of the config folder was not tuched in any way.

### Did this behavior use to work in the previous version?

N/A. The server only ran on version 4.2.2

## Steps to Reproduce (for bugs)

1. Start Server
2. Join World
3. Wait for 1 minute (a little more usually)
4. Get the Message Server closed on the client

## Logs

* Client/Server Log: The latest one is also in the linked gist. Prefixed with `crash- ` are the crash logs, Prefixed with `debug-` are the debug-logs and Prefixed with `log-` are the regular logs. The numbers after corrospond to the time, that the logs were from. [https://gist.github.com/C0D3-M4513R/fd5464a0be3b5bf203a8f7e6b467bd48](https://gist.github.com/C0D3-M4513R/fd5464a0be3b5bf203a8f7e6b467bd48)
* Crash Logs:  [https://gist.github.com/C0D3-M4513R/fd5464a0be3b5bf203a8f7e6b467bd48](https://gist.github.com/C0D3-M4513R/fd5464a0be3b5bf203a8f7e6b467bd48)

## World Information
* World Preset:Default/Sky Factory 4
* Prestige Enabled:NO
* Modpack Version world created in:4.2.2
* Additional Content Installed: There was Worldedit installed, but it is removed for this report

## Client Information
* Modpack Version:4.2.2
* Java Version:
```java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```
* Launcher Used: MutiMC
* Memory Allocated: 20480M 
* Server/LAN/Single Player: Server
* Optifine Installed: Yes 
* Shaders Enabled: No 

## Server Information
* Java Version:
```
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
```
* Operating System: Debian GNU/Linux 10
* Hoster/Hosting Solution: Virtual Root Server (Otherwise unknown)
* Sponge (Non-Vanilla Forge) Server: No

**Comment by C0D3-M4513R** [comment]
Note: At some point the crashes were generated using my local Computer, but all files were copied from the server to my machine using scp. After that timepoint, all crashes + logs are from my machine.
I can still access the server and could still reproduce the issue, with the original files.

**Comment by sam-kirby** [comment]
Something you have done with Integrated Dynamics is causing significant lag, resulting in the time the game takes to tick extending beyond the 1 minute default maximum - for reference, a game tick should take 50 milliseconds.

This isn't necessarily a bug; it depends on whether or not what you've done with ID is "reasonable".

I cannot determine this from the crash reports, and your steps to reproduce aren't any use.

To fix your world, you should disable the watchdog timer and then go in and remove the source of the lag. Disable the watchdog timer by going into `server.properties` and setting `max-tick-time=-1`
**Note that this is negative one**

Without the watchdog timer, the server will no longer crash, but will lag really badly. Work out which ID setup is causing the lag and disable or remove it.

If you believe what you've done is reasonable and shouldn't cause a crash, please open a new report here with specific details.

**Comment by C0D3-M4513R** [comment]
The problem ended up being 64 level 5 Cobblestone generators, each taking up to 2000µs/tick. If I disconnect the integrated dynamics network, they are hooked up to, they take between 500-600µs/tick.
