### ISSUE TITLE
Can't Interact With Anything and I Can't Die

### ISSUE THREAD

**Issue by MOSTWANTEDGamer1** [DarkPacks/SkyFactory-4#1704]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by sam-kirby** [comment]
Please stop posting the same issue with no information. We can't fix something we can't reproduce.
