### ISSUE TITLE
Journeymap

### ISSUE THREAD

**Issue by jarn123** [DarkPacks/SkyFactory-4#1707]
## Bug Description
 if i go on servers i see the journeymap of the other server

### Did this behavior use to work in the previous version?

 i don't know (because i know how to make a local host server but i don't know how to start it)

## Steps to Reproduce (for bugs)

1.go on server A
2.go fly on server A to load more of the minimap
3.go to server B and look on journeymap

## Logs

* Client/Server Log: -
* Crash Log: -

## World Information
* World Preset: idk servers are not from me
* Prestige Enabled: i think so on one server but idk on both server
* Modpack Version world created in: idk server are not from me
* Additional Content Installed: no

## Client Information
* Modpack Version: i think 4.2.2
* Java Version: idk
* Launcher Used: the normal minecraft launcher
* Memory Allocated: idk
* Server/LAN/Single Player: server
* Optifine Installed: no
* Shaders Enabled: no

## Server Information
* Java Version: idk
* Operating System: idk because the 2 servers are created with aternos
* Hoster/Hosting Solution: idk
* Sponge (Non-Vanilla Forge) Server:-

**Comment by sam-kirby** [comment]
JourneyMap identifies servers either by the name you give them when you choose "Add Server", or by their address if you use "Direct Connection"· Give them different names and you won't see the map from one server appear when connected to the other. Delete the `./journeymap/data/mp` folder to reset mapping for all servers.
