### ISSUE TITLE
illegal minecraft recipe

### ISSUE THREAD

**Issue by Derpatron111** [DarkPacks/SkyFactory-4#1711]
When i try to join my server this message pops up [Client thread/FATAL]: Error executing task java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Recipe minecraft:wooden_door (net.minecraft.item.crafting.ShapedRecipes@2552181d) produces unregistered item minecraft:wooden_door (net.minecraft.item.ItemBlock@50d05167)

I have only used the newest version on curseforge so i don't know

1.Download server pack
2.Copy and paste mods from server into .minecraft mods folder
3.Start up server
4. Attempt to join

* Client/Server Log:  https://pastebin.com/kjHWyQ7q
* Crash Log: no crash logs exist(not downloaded from twitch)

## World Information
* World Preset:IDK
* Prestige Enabled:IDK
* Modpack Version world created in:1.12.2
* Additional Content Installed: removed Project E

## Client Information
* Modpack Version:4.2.2
* Java Version:Newest
* Launcher Used: curseforge
* Memory Allocated:8gb
* Server/LAN/Single Player:server
* Optifine Installed:nope
* Shaders Enabled:nope

## Server Information
* Java Version:Newest
* Operating System:IDK what this means
* Hoster/Hosting Solution:IDK what this means
* Sponge (Non-Vanilla Forge) Server:This is Curseforge

**Comment by Derpatron111** [comment]
???

**Comment by sam-kirby** [comment]
This issue is a result of missing recipes and invalid configuration on your client. You can't just copy the mods and call it done.

The easiest thing to do is install the pack through a launcher. The pack is available on any of ATLauncher, MultiMC, GDLauncher or Twitch.

Also, removing ProjectE will lead to further headaches in the future - all custom recipes will be broken without further changes.

**Comment by Derpatron111** [comment]
Thx

**Comment by Derpatron111** [comment]
I have used a launcher but the server loaded like a regular world and not one block and a tree.

**Comment by Derpatron111** [comment]
I have fixed the issue with the world but this crash error occures
https://pastebin.com/vXdydLnM

**Comment by sam-kirby** [comment]
You have made a mistake on the `generator-settings` line of server.properties. Please make sure you have copied it correctly. If you continue to have issues please seek support on the Discord server - it should be quicker than asking here. (https://discord.gg/darkosto)
