### ISSUE TITLE
Hello, Im trying to download Sky factory on The ATLaucnher and keep getting this error

### ISSUE THREAD

**Issue by Professor21212** [DarkPacks/SkyFactory-4#1712]
Error downloading scala-reflect-2.11.1.jar from https://files.minecraftforge.net/maven/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar. . Copied to FailedDownloads folder & cancelling install!

**Comment by sam-kirby** [comment]
Not an issue we can help with unfortunately as it's not an issue with the pack. You could try a different launcher; multimc or Twitch for instance, or you can contact ATLauncher via their Github.
