### ISSUE TITLE
Files not appearing.

### ISSUE THREAD

**Issue by SemiUnorthodoxal** [DarkPacks/SkyFactory-4#1713]
When i downloaded the mod it wasn't in a .JAR form and it wouldn't registure, how do i fix this?

**Comment by sam-kirby** [comment]
SkyFactory 4 is not one mod, it is a collection of mods. The easiest way to install it is using a launcher such as ATLauncher, Twitch or MultiMC. If you need help with this you should ask on the Discord https://discord.gg/darkosto
