### ISSUE TITLE
infinite flight with supremium armor and ender orb

### ISSUE THREAD

**Issue by eefybeefy10** [DarkPacks/SkyFactory-4#1728]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by eefybeefy10** [comment]
you need to fly with supremium armor and then throw the ender orb and take off the armor then you can walk on air and jump for infinite flight

**Comment by Darkosto** [comment]
Okay, sounds cool!
