### ISSUE TITLE
I have a problem this modpack is too awsome. i cant stop playing it

### ISSUE THREAD

**Issue by FlamerGaming** [DarkPacks/SkyFactory-4#1744]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by Darkosto** [comment]
<3
