### ISSUE TITLE
Unable to login using a microsoft account

### ISSUE THREAD

**Issue by garrnyt** [DarkPacks/SkyFactory-4#1746]
Recently bought minecraft to join my friends on sky factory 4 but because Mojang have started only offering microsoft accounts instead of the mojang accounts I am unable to log in to join them because it doesn't recognize my authentication, is this an issue you can fix or is it something I would need to contact mojang/microsoft about?

**Comment by sam-kirby** [comment]
I can't currently test this as I still have a Mojang account.

Is there any more information you can provide as to why you are unable to join? Mojang seemed to indicate old versions of the game would continue working and we do nothing to change authentication.

**Comment by Darkosto** [comment]
I don't see how this would be a modpack issue and it's definitely something we have no control over.
