### ISSUE TITLE
Twilight Forest Hydra

### ISSUE THREAD

**Issue by aboood94** [DarkPacks/SkyFactory-4#1748]
## Bug Description

 as we all know there is some order for defeating bosses in the Twilight Forest .. but the problem is that i already killed the Lich so the Yeti's area and the ice queen's area were successfully opened for me .. i killed them and i killed also the knight .. but the area of the Hydra is not opened .. i even tried to kill the ur-ghast and i was able to fight him and defeat him and yet the Hydra's area still closed .. what should i do ??

### Did this behavior use to work in the previous version?

 i didn't try any other version before

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by Darkosto** [comment]
I would check the achievements and make sure they are completed? This is not really a pack issue as much as it is a mod issue. There's not a whole lot I can personally do except let you know to check the advancement page
