### ISSUE TITLE
Ore excavator not working after prestige turned off

### ISSUE THREAD

**Issue by RSNFreud** [DarkPacks/SkyFactory-4#1750]
## Bug Description

After forcing prestige on and off and rejoining the server I am unable to use ore excavator despite having the gamestage for it

### Did this behavior use to work in the previous version?

Unknown

## Steps to Reproduce (for bugs)

1. Join a server and force prestige mode on
2. Do a bunch of stuff on the server
3. Force prestige mode off
4. Try use ore excavator

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset: Sky Factory 4
* Prestige Enabled: Read above
* Modpack Version world created in: 1.12.2
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player: Server
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server: Yes

**Comment by sam-kirby** [comment]
Prestige mode is not setup such that it can be altered at runtime; you must decide if you are going to play with it enabled before first logging into the server. Setting which gamestages a player has access to is done on first login.

If you absolutely must change between the two, there are two workarounds:

  1. Delete player data from the server; initial login functions will therefore be rerun, but the world will be kept. Players can store items in e.g. chests to prevent loss.
  2. Run the function `triumph:classic_mode` for every player on your server who logged in before the switch. Note that they must be logged in for this to work.

**Comment by RSNFreud** [comment]
How do I run the function?

**Comment by sam-kirby** [comment]
This is vanilla functionality. See the `execute` (to run an arbitrary command as another player) and `function` (to run a function) commands.

**Comment by RSNFreud** [comment]
`Run the function triumph:classic_mode for every player on your server who logged in before the switch. Note that they must be logged in for this to work.`

It didn't work ore excavation still doesnt work....

**Comment by RSNFreud** [comment]
Tried remaking the world and it also didnt change anything

**Comment by RSNFreud** [comment]
> Prestige mode is not setup such that it can be altered at runtime; you must decide if you are going to play with it enabled before first logging into the server. Setting which gamestages a player has access to is done on first login.
> 
> If you absolutely must change between the two, there are two workarounds:
> 
> 1. Delete player data from the server; initial login functions will therefore be rerun, but the world will be kept. Players can store items in e.g. chests to prevent loss.
> 2. Run the function `triumph:classic_mode` for every player on your server who logged in before the switch. Note that they must be logged in for this to work.

Neither of these methods work. Where exactly is the data stored for prestige? Is it somewhere hidden inside the config files?

**Comment by sam-kirby** [comment]
No, it's all stored in the folder called `prestige` in the server's top directory.
