### ISSUE TITLE
helllllp

### ISSUE THREAD

**Issue by harrobe123** [DarkPacks/SkyFactory-4#1752]
## Bug Description

<i make compact chest from compachtedstorage mod that is a 24x12 chest i cant see the whole of the chest along with my inventory hot bar but when i make the window smaller it works and i can see it why is this happening

### Did this behavior use to work in the previous version?

<there is a previous version?

## Steps to Reproduce (for bugs)

1.load in world
2.
3.

## Logs

* Client/Server Log can’t be bothered to look
* Crash Log: can’t be bothered to look

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:electrobobs wizardry,loot bags

## Client Information
* Modpack Version:1.12.2
* Java Version:4.2.2
* Launcher Used:ATlancher
* Memory Allocated:
* Server/LAN/Single Player:single
* Optifine Installed:
* Shaders Enabled:

**Comment by harrobe123** [comment]
hello someone solve this

**Comment by sam-kirby** [comment]
Changing the GUI scale should help.

**Comment by sam-kirby** [comment]
GO TO THE OPTIONS MENU, THEN GO INTO VIDEO SETTINGS, THEN CHANGE THE GUI SCALE SLIDER
