### ISSUE TITLE
Wooden crates crashes server if taking items too fast

### ISSUE THREAD

**Issue by Awakened-Redstone** [DarkPacks/SkyFactory-4#1776]
## Bug Description
Wooden crates crashes servers if taking items too fast (2GB RAM server [Aternos server])

### Did this behavior use to work in the previous version?
Yes

## Steps to Reproduce (for bugs)
1. Fill a wooden crate
2. Spam right click on it.

## Logs

* Client/Server Log: No access/deleted
* Crash Log: No access/deleted

## World Information
* World Preset: Default
* Prestige Enabled: No
* Modpack Version world created in: 4.2.2
* Additional Content Installed: No

## Client Information
* Modpack Version: 4.2.2
* Java Version: 12
* Launcher Used: Curseforge (Overwolf)
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server
* Optifine Installed: Yes
* Shaders Enabled: No

## Server Information
* Java Version: No access
* Operating System: No aceess
* Hoster/Hosting Solution: Aternos
* Sponge (Non-Vanilla Forge) Server: No

**Comment by gkuba** [comment]
Server Readme.txt states at least 4gb of RAM is needed for servers as 2gb will have issues. Try bumping the server up to 4gb of RAM.

**Comment by Awakened-Redstone** [comment]
I can't, its Aternos
