### ISSUE TITLE
Certain commands not working

### ISSUE THREAD

**Issue by harrobe123** [DarkPacks/SkyFactory-4#1789]
## Bug Description

Certain commands not working

![image](https://user-images.githubusercontent.com/74988522/103464384-37cc4b00-4d2b-11eb-9820-6aa34698d2b9.png)

## Steps to Reproduce (for bugs)

1.type a command in survival world
2.done
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:no
* Modpack Version world created in:
* Additional Content Installed:lootbags and electrobobs wizardrey

## Client Information
* Modpack Version:1.12.2
* Java Version:4.2.2
* Launcher Used:ATlauncher
* Memory Allocated:
* Server/LAN/Single Player:single player
* Optifine Installed:
* Shaders Enabled:

**Comment by Kappamenhehe** [comment]
Well , its probably not modpack fault.And you are not opped.
What command are you trying to run?

**Comment by harrobe123** [comment]
ive got same problem as issue 520 but when i tried to do the fix it did this

**Comment by harrobe123** [comment]
> Well , its probably not modpack fault.And you are not opped.
> What command are you trying to run?

im trying toi run the command that is /gamestage add @p non_pacifist

**Comment by sam-kirby** [comment]
You need to have cheats enabled to be able to use the vast majority of commands.

You will get this error if you do not have cheats enabled.
