### ISSUE TITLE
My world is delayed

### ISSUE THREAD

**Issue by TheKingOmar** [DarkPacks/SkyFactory-4#1807]
### Did this behavior use to work in the previous version?
I was always in the same update

## Steps to Reproduce (for bugs)

1.I join and play normaly
2.i unplug my charger
3.the game lags
4.everything is delayed

## Logs

* Client/Server Log:
* Crash Log:https://gist.github.com/TheKingOmar/31ddecfb334ca19451b925983c3da1d4

## World Information
* World Preset:SkyFactory 4
* Prestige Enabled:false
* Modpack Version world created in:4.2.2
* Additional Content Installed:false

## Client Information
* Modpack Version:4.2.2
* Java Version:8,Update 271(latest version)
* Launcher Used:native launcher
* Memory Allocated:6174MB of ram (6.1GB)
* Server/LAN/Single Player:Single Player
* Optifine Installed:false

**Comment by sam-kirby** [comment]
It looks like you're running the game on an ultrabook class laptop or similar. These are typically designed to give long battery life, so when unplugged they deliver less power to the CPU. An inevitable consequence of this is that they run slower on battery.

You may be able to change this by setting Windows to high performance mode. However, it's probably best to just keep your laptop plugged in when you want to use it for games.

**Comment by sam-kirby** [comment]
Note also that you are using Java 1.8.0_51 - follow this guide if you'd like Minecraft to use the latest version of Java 8 you have installed:

https://github.com/Preocts/darko_java_help/blob/source/walkthru-pic.md

**Comment by TheKingOmar** [comment]
Ok but now i replugged it it's still not working

**Comment by sam-kirby** [comment]
Have you reloaded the world or restarted the game since unplugging? It's likely it can't catch up with the work it missed while unplugged.

**Comment by TheKingOmar** [comment]
> Have you reloaded the world or restarted the game since unplugging? It's likely it can't catch up with the work it missed while unplugged.

Yea i restarted the game several times

**Comment by TheKingOmar** [comment]
I thought that will fix the problem

**Comment by TheKingOmar** [comment]
Is there a fix?

**Comment by TheKingOmar** [comment]
> Have you reloaded the world or restarted the game since unplugging? It's likely it can't catch up with the work it missed while unplugged.

Can you please give me a fix my world is bugged even the time started goin back

**Comment by TheKingOmar** [comment]
i want to the fix please

**Comment by sam-kirby** [comment]
It's not clear to me what the fix for this issue is.

The only thing I know about the system you're using to play the pack is it's about 8 years old and a laptop.

This means you're probably on the very edge of being able to run the pack. So here's some general tips. 

1) Make sure you have allocated at least 2GB less than your total system RAM to Java so that your OS has enough left to operate.
2) The pack needs at least 4GB of RAM allocated to it, so if you have less than 6GB total then you aren't going to have a good time playing this pack.
3) Don't allocate more than 8GB, there's no point.
4) Close as many other programs as possible. If you need to use a web browser or Discord, do so from your phone if you can.
5) Make sure your laptop is using its high performance profile.

If heavily modded Minecraft is something you want to be able to play comfortably, you might want to consider upgrading your laptop at some point.

**Comment by TheKingOmar** [comment]
> It's not clear to me what the fix for this issue is.
> 
> The only thing I know about the system you're using to play the pack is it's about 8 years old and a laptop.
> 
> This means you're probably on the very edge of being able to run the pack. So here's some general tips.
> 
> 1. Make sure you have allocated at least 2GB less than your total system RAM to Java so that your OS has enough left to operate.
> 2. The pack needs at least 4GB of RAM allocated to it, so if you have less than 6GB total then you aren't going to have a good time playing this pack.
> 3. Don't allocate more than 8GB, there's no point.
> 4. Close as many other programs as possible. If you need to use a web browser or Discord, do so from your phone if you can.
> 5. Make sure your laptop is using its high performance profile.
> 
> If heavily modded Minecraft is something you want to be able to play comfortably, you might want to consider upgrading your laptop at some point.

i have 6GB OF RAM allocated
i play the pack with no other programs open
my laptop is using the high performance profile
the issue is not that i am lagging there was no problem at all in frames it's just the delay glitch i played bigger packs with no big problems i just wished that i can fix the problem
