### ISSUE TITLE
Multiplayer server not loading right

### ISSUE THREAD

**Issue by willascott** [DarkPacks/SkyFactory-4#1809]
okay, so I have just got Minecraft and I'm trying to create a server for me and my friends and I've done the server on atlauncher and its there but for some reason I don't start on a sky block I start in a normal world with all the mods which is fun but not what i want,, any help?????????

**Comment by sam-kirby** [comment]
Don't use the server files from ATLauncher; they are automatically generated and incomplete.

The default settings are correct in the server download from CF: https://www.curseforge.com/minecraft/modpacks/skyfactory-4/files/3012800
