### ISSUE TITLE
mob spawner not working

### ISSUE THREAD

**Issue by Rager10** [DarkPacks/SkyFactory-4#1810]
im over 50 blocks away from my mob spawner and its compleatly red "X" dark and still not spawning any mobs on hard mode. Someone plz help with this problem.

**Comment by Rager10** [comment]
WHAT! NOT FAIR I HAVE TO DEAL WITH IT MYSELF!

**Comment by sam-kirby** [comment]
Please try the #sf4-gameplay channel on https://discord.gg/darkosto
