### ISSUE TITLE
The game crashed whilst initializing game Error: org.lwjgl.LWJGLException: Pixel format not accelerated Exit Code: -1

### ISSUE THREAD

**Issue by TheKingOmar** [DarkPacks/SkyFactory-4#1816]
## Bug Description
The game crashed whilst initializing game
Error: org.lwjgl.LWJGLException: Pixel format not accelerated
Exit Code: -1
so i was having problems with an another modpack and the mods of that modpack said to update my drivers and i did but all my modpacks are now broken so i uninstalled the driver update and this what happened

### Did this behavior use to work in the previous version?
i didn't use any previous versions

## Steps to Reproduce (for bugs)

1.updates my graphics drivers
2.all my modpacks get broken
3.i uninstall them
4. even more broken?

## Logs

* Client/Server Log:
* Crash Log:https://pastebin.com/RLMJqXNs

## World Information
* World Preset:SkyFactory 4
* Prestige Enabled:false
* Modpack Version world created in:4.2.2
* Additional Content Installed:false

## Client Information
* Modpack Version:4.2.2
* Java Version:8,Update 271 (latest version)
* Launcher Used:native launcher
* Memory Allocated:6174MB,6G
* Server/LAN/Single Player:Singleplayer
* Optifine Installed:false
* Shaders Enabled:false

**Comment by sam-kirby** [comment]
Minecraft can't run without drivers for your GPU.

**Comment by TheKingOmar** [comment]
> Minecraft can't run without drivers for your GPU.

then why did it crash?
and i just listened to someones advice if didn't have a relate did my game crash

**Comment by TheKingOmar** [comment]
> Minecraft can't run without drivers for your GPU.

then what drivers i have to download

**Comment by TheKingOmar** [comment]
*don't worry about anything now i fixed it by resetting my laptop to
factory setting sadly i forgot to backup my world*
