### ISSUE TITLE
Missing file mods

### ISSUE THREAD

**Issue by V4nnix** [DarkPacks/SkyFactory-4#1818]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by V4nnix** [comment]
I can play it there are missing files on the Pack i cant start my Server

**Comment by sam-kirby** [comment]
No files are missing.
