### ISSUE TITLE
Error when loading in server after putting in ip into server.properties

### ISSUE THREAD

**Issue by Rlbgs** [DarkPacks/SkyFactory-4#1824]
## Bug Description

 Whenever I put a public IP it says cannot bind to a port and whenever I put an ipv4 into the server.properties I get an info code which says this: [11:13:21] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at java.lang.Thread.run(Unknown Source)

### Did this behavior use to work in the previous version?

No only on Skyfactory 4 servers

## Steps to Reproduce (for bugs)

1. Install a server normally
2. Add any ipv4 to get error code [11:13:21] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]:  at java.lang.Thread.run(Unknown Source)
Or use a Public IP to get Cannot bind to port

## Logs

* Client/Server Log:https://pastebin.com/xXm72ES4 Crafttweaker log: https://pastebin.com/L1bN7ZVM
* Crash Log:https://pastebin.com/3sFKLeqJ

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:4.2.2
* Java Version:V8 Update 281
* Launcher Used: CurseForge
* Memory Allocated:Default (4gb)
* Server/LAN/Single Player:server
* Optifine Installed:no
* Shaders Enabled:no

## Server Information
* Java Version:V8 Update 281
* Operating System:WIN 10
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Don't put a `server-ip` in server.properties unless you have multiple network adapters and only want the server to use one of them. And even then, you would use the adapter's local IP address.

Putting an IP address in this field causes the game to look for an adapter with that IP address on your system and attempt to bind to that adapter. You don't have an adapter with your public IP address as your computer is not directly connected to the internet; it is connected through your router.
