### ISSUE TITLE
FPS Drops

### ISSUE THREAD

**Issue by flookthenuke** [DarkPacks/SkyFactory-4#1825]
## Bug Description

 When I make a new singleplayer game, there are intense fps drops and it is not really playable. Is there anyway to disable some mods for better fps?

### Did this behavior use to work in the previous version?

 I do not know

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by sam-kirby** [comment]
There is nothing to go on here. Please ask this kind of question on Discord - https://discord.gg/darkosto
