### ISSUE TITLE
chunk

### ISSUE THREAD

**Issue by lemayor1** [DarkPacks/SkyFactory-4#1826]
## Bug Description

 the chunk does not charge 

### Did this behavior use to work in the previous version?

 i dont know

## Steps to Reproduce (for bugs)
https://www.mediafire.com/file/6s6xx8bp7gmkix2/image_2021-01-29_122546.png/file

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version: latest 
* Java Version: 1.12.2
* Launcher Used: Tluncher
* Memory Allocated: i dont know
* Server/LAN/Single Player: Single Player
* Optifine Installed: yes
* Shaders Enabled: yes

**Comment by sam-kirby** [comment]
We don't support pirate copies.
