### ISSUE TITLE
Crashes during startup.

### ISSUE THREAD

**Issue by siky112** [DarkPacks/SkyFactory-4#1827]
## Bug Description

I tried to load this modpack through MultiMC and it crashed.

### Did this behavior use to work in the previous version?
Not sure.

## Steps to Reproduce (for bugs)

Not sure.

## Logs

* Client/Server Log: I don't know where that is.
* Crash Log: https://paste.ee/p/i4W7M

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version: 4.2.2
* Java Version: 1.12.2
* Launcher Used: MultiMC
* Memory Allocated: 1024 MB max
* Server/LAN/Single Player: This is a bug during startup
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sam-kirby** [comment]
Not a bug; the game needs ~3GB of RAM just to launch. It works best with 6-8GB assigned.

Follow the suggestion of MultiMC and install a 64-bit version of Java 8, then assign more memory.
