### ISSUE TITLE
I can't create a new instance for sky factory 4

### ISSUE THREAD

**Issue by LiquidRO** [DarkPacks/SkyFactory-4#1831]
## Bug Description
When i try to create a new instance for a modpack (take skyfactory 4 for example) it loads up a bit an then it shows me this error: "Sky Factory 4 4.2.2 wasnt installed. Check error logs for more information."

### Did this behavior use to work in the previous version?
I played a while ago, I can't recall what version it was, and it showed me the same error.

## Steps to Reproduce (for bugs)
1.Start the launcher
2.Create a new instance for sky factory 4 4.2.2

## Logs
* Client/Server Log: https://pastebin.com/TZ9LDxFK
* Crash Log:

## World Information
* World Preset: Sky Factory 4
* Prestige Enabled: No
* Modpack Version world created in: 4.2.2
* Additional Content Installed: No

## Client Information
* Modpack Version: 4.2.2
* Java Version: 1.8.0_281
* Launcher Used: ATLouncher
* Memory Allocated: 5GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sam-kirby** [comment]
Your issue appears to be with ATLauncher, not our pack.

https://github.com/ATLauncher/ATLauncher/issues

Please note that our packs are released on multiple launchers; you can use any of these: MultiMC, GDLauncher, Curseforge, ATLauncher.

**Comment by LiquidRO** [comment]
> Your issue appears to be with ATLauncher, not our pack.
> 
> https://github.com/ATLauncher/ATLauncher/issues
> 
> Please note that our packs are released on multiple launchers; you can use any of these: MultiMC, GDLauncher, Curseforge, ATLauncher.

Actually, I tried to install an older version, I created a new instance for Sky Factory 4 4.1.0, and it worked, but I can't create one for 4.2.2 version, and I can't update the 4.1.0 version.
