### ISSUE TITLE
Disconnect from server when pulling stacks out of a barrel or crate fast.

### ISSUE THREAD

**Issue by zediious** [DarkPacks/SkyFactory-4#1840]
## Bug Description

 Players are experiencing a disconnect on my SkyFactory 4 server when taking stacks out of the crates/barrels from the "Barrels, Drums, Storage, and More" mod at a fast rate by hand.

### Did this behavior use to work in the previous version?

 I have yet to play/use a previous version of the pack.

## Steps to Reproduce (for bugs)

 
1. Place a barrel or crate from the "Barrels, Drums, Storage, and More" mod, and fill it with any item.
2. Spam left click on it to retrieve stacks at a time.
3. Disconnect to main menu, with error "A fatal error has occured, this connection is terminated"

## Logs

* Client/Server Log:https://pastebin.com/CkwFdLZb (The error seems to be more related to sponge, wanted to post in both places)
* Crash Log:

## World Information
* World Preset: default
* Prestige Enabled: false
* Modpack Version world created in: 4.2.2
* Additional Content Installed: SpongeForge with Nucleus, GriefDefender, LuckPerms, CatClearLag

## Client Information
* Modpack Version: 4.2.2
* Java Version: 8, happens to any player on the server.
* Launcher Used: GDLauncher
* Memory Allocated: 7gb
* Server/LAN/Single Player: Server
* Optifine Installed: false
* Shaders Enabled: false

## Server Information
* Java Version: 8
* Operating System: Linux
* Hoster/Hosting Solution: Ethera
* Sponge (Non-Vanilla Forge) Server: SpongeForge server

**Comment by sam-kirby** [comment]
Duplicate #1610
