### ISSUE TITLE
SkyFractory 4 is blurry in the gui

### ISSUE THREAD

**Issue by rebelAlliance09** [DarkPacks/SkyFactory-4#1846]
![image](https://user-images.githubusercontent.com/45608861/108402998-25906880-7216-11eb-99f3-755af8418dd8.png)

game gui is blurry. i did have smooth font installed, but when it was the crosshair and the inventory was blurry

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by sam-kirby** [comment]
Your high-res texture pack does not have icons for sky factory's unique items, so the default resolution textures are being used.

**Comment by rebelAlliance09** [comment]
> Your high-res texture pack does not have icons for sky factory's unique items, so the default resolution textures are being used.

i dont have any texture pack installed
