### ISSUE TITLE
Ex Nihalo mod not in modpack on curse forge

### ISSUE THREAD

**Issue by BYSTE1** [DarkPacks/SkyFactory-4#1858]
Help.  I can't use a sieve because the Ex Nihalo mod isn't in the modpack.  PLEASE HELP THIS IS DUMB.

**Comment by sam-kirby** [comment]
Ex Nihilo isn't supposed to be in the pack. You should probably read the description of a pack before you download it so you don't end up posting such silly issues.

> We've completely redesigned the resource gathering. Sieving for resources are a thing of the past. For a more immersive experience, Sky Orchards has been introduced. Resource Trees provides a built-in progression system and lets the player choose the resources they want to produce rather than a randomized system.
