### ISSUE TITLE
making lava with 4 cobbletone in a cauldron doesnt work

### ISSUE THREAD

**Issue by minkorono** [DarkPacks/SkyFactory-4#1862]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by sam-kirby** [comment]
Seems to work for me; try reinstalling.
