### ISSUE TITLE
Cannont download modpack.

### ISSUE THREAD

**Issue by hussam67** [DarkPacks/SkyFactory-4#1868]
I cannot download this mod pack. Every time I try it fails saying that it could not download a mod in the pack.

**Comment by sam-kirby** [comment]
This is a long standing caching issue with the Curseforge launcher. It affects all packs. This pack is fine, and there is nothing we can do to fix it.

It will resolve itself after some time (generally a few hours), however if you want to start playing sooner you can download the pack through another launcher. GDLauncher, MultiMC and ATLauncher are all great options and supported.
