### ISSUE TITLE
Cant launch

### ISSUE THREAD

**Issue by Berrysverry** [DarkPacks/SkyFactory-4#1870]
### Did this behavior use to work in the previous version?

[crash-2021-03-19_09.25.40-client.txt](https://github.com/DarkPacks/SkyFactory-4/files/6169709/crash-2021-03-19_09.25.40-client.txt)

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log: [crash-2021-03-19_09.25.40-client.txt](https://github.com/DarkPacks/SkyFactory-4/files/6169709/crash-2021-03-19_09.25.40-client.txt)

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:newest
* Launcher Used:
* Memory Allocated:7000
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by sam-kirby** [comment]
Your graphics driver is probably out of date, you probably can't launch vanilla 1.12.2 either. See Mojang's help article on this here:

https://help.minecraft.net/hc/en-us/articles/360029643932-Problematic-frame-or-pixel-format-not-accelerated
