### ISSUE TITLE
Missing items from mods or something else is completely wrong

### ISSUE THREAD

**Issue by Anew522** [DarkPacks/SkyFactory-4#1874]
I can't use or find items that are within the mods that I am trying to use. The smeltery stuff is a good example of the problem. I have no way to cook the actual alloys in the smeltery since I don't have a controller, only a compact forge. I figured the issue had to do with the prestige stuff so I disabled that but nothing that I need showed up afterwards. I restarted the game and looked through most of the items that are available to use. I can't properly smelt or use bonsai pots efficiently.

**Comment by sam-kirby** [comment]
If you start a game with prestige on there is no easy way to disable it later. It's simplest to start again.

If that's not an option for you, try asking for help on the discord.
