### ISSUE TITLE
there is a mod called cyclic and there is an item called item extraction cable and the bug is that its ignore list and an allowed list which does not work if being under an hopper above being hopping bonsai pot with an tree inside. The bug makes my auto manyullyn farm gets clogged up. The way it gets clogged that the trees grow giving you leaves, resins, acorns, saplings, sticks and logs but I ONLY NEED RESINS AND ACORNS and it clogs my auto-crafter.

### ISSUE THREAD

**Issue by markandtheslime** [DarkPacks/SkyFactory-4#1880]
## Bug Description
A clear and concise description of the problem...
<there is a mod called cyclic and there is an item called item extraction cable and the bug is that its ignore list and an allowed list which does not work if being under an hopper above being hopping bonsai pot with an tree inside. The bug makes my auto manyullyn farm gets clogged up. The way it gets clogged that the trees grow giving you leaves, resins, acorns, saplings, sticks and logs but I ONLY NEED RESINS AND ACORNS and it clogs my auto-crafter. I don't really think its a bug but the bug is that hoppers give items to (item cables-item extarctaction cables) and that clogs my auto manyullyn farm>

### Did this behavior use to work in the previous version?
<(I can't play any other version of this)>
<skyfactory 4 does not let you change the version if you download it from curse forge app>
<I was playing on 1.12.2 skyfactory 4 from the curseforge app

<please if any non-bug fixers read this then this bug can be fixed but is way more hard to make any auto bonsai tree (metal-crystal) farms>
1.please make so hoppers don't give anything to (item cables-item extarctaction cables) at least hoppers count as hoppers without being able to give anything.

* Client/Server Log:<I didn't know what I was supposed to do in the skyfactory 4 server and I think it lagged a bit>
* Crash Log:<I think it lagged once or it didn't even lag>

## World Information
* World Preset: skyfactory 4 tutorial (this bug can work on any other preset
* Modpack Version world created in:<1.12.2>
* Additional Content Installed:<(nothing)>

## Client Information
* Modpack Version:<1.12.2>
* Java Version:< I was playing in this version>
* Launcher Used:<minecraft launcher>
* Server/LAN/Single Player:<singleplayer>
* Optifine Installed:<no>
* Shaders Enabled:<no>

**Comment by sam-kirby** [comment]
The hopping bonsai pot pushes its items into the pipe; the pipe has no say over what it gets.

Perhaps add a trash can filtered to take the items you don't want going to your autocrafter?
