### ISSUE TITLE
The fertile dirt does not exist

### ISSUE THREAD

**Issue by DABABYDADDY** [DarkPacks/SkyFactory-4#1883]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by sam-kirby** [comment]
If you are playing in prestige mode I recommend you read the description for that game mode.

Can't tell as you gave zero information.

As far as I can tell, this is not an issue with the pack.
