### ISSUE TITLE
Caught exception from AE2 Stuff (ae2stuff) on server start

### ISSUE THREAD

**Issue by NathanSehn** [DarkPacks/SkyFactory-4#1891]
## Bug Description

Caught exception from AE2 Stuff (ae2stuff) 
ServerStart.bat will fail when trying to load the recipe changes. 
Command line stack trace: https://pastebin.com/TsvupjCS  

### Did this behavior use to work in the previous version?

N/A first time trying to run the server

## Steps to Reproduce (for bugs)

1. Extract Files
2. Run install.bat and ServerStart.bat
3. Set EULA to true
4. Run ServerStart.bat a second time 
5. *Crash*

## Logs

* Client/Server Log: https://pastebin.com/jYe91eR7 
* Crash Log: https://pastebin.com/g2770zEA 

## World Information
* World Preset: N/A
* Prestige Enabled: N/A
* Modpack Version world created in: 4.2.2
* Additional Content Installed: None

## Client Information
N/A

## Server Information
* Java Version: Version 8 Update 281 (build 1.8.0_281-b09)
* Operating System: Windows 10 
* Hoster/Hosting Solution: Hoster
* Sponge (Non-Vanilla Forge) Server: N/A

**Comment by sam-kirby** [comment]
Try reinstalling from scratch - this looks like one of the libraries needed to run the server is corrupted (specifically the Scala standard library).
