### ISSUE TITLE
not reall a client bug its just i can download mostly every mod execept this one 

### ISSUE THREAD

**Issue by AstraIGunZone** [DarkPacks/SkyFactory-4#1897]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by sam-kirby** [comment]
There's no information here..
