### ISSUE TITLE
Skyfactory 4 crashes on startup

### ISSUE THREAD

**Issue by Xioverze** [DarkPacks/SkyFactory-4#1901]
## Bug Description
SkyFactory 4 crashes on startup quoting an error that will be found in the crash report

## Steps to Reproduce (for bugs)

1. Download from overwolf
2. Without making any edits try to open skyfactory 4
3. You should have the error

## Logs

* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version: Latest
* Java Version: In Crash report
* Launcher Used: Overwolf/Minecraft launcher
* Memory Allocated: 4028 Megabytes
* Server/LAN/Single Player: Singeplayer
* Optifine Installed: Fresh Install
* Shaders Enabled: Fresh Install

**Comment by Xioverze** [comment]
[crash-2021-05-07_15.12.20-client.txt](https://github.com/DarkPacks/SkyFactory-4/files/6443850/crash-2021-05-07_15.12.20-client.txt)
logs didnt send for some reason

**Comment by sam-kirby** [comment]
Have you tried reinstalling?

It looks like one of the mods (InControl) is corrupt. We don't distribute the mods themselves, the launcher downloads a manifest which lists the mods needed and downloads them separately. Reinstalling will cause it to download all mods again.

**Comment by Xioverze** [comment]
> Have you tried reinstalling?
> 
> It looks like one of the mods (InControl) is corrupt. We don't distribute the mods themselves, the launcher downloads a manifest which lists the mods needed and downloads them separately. Reinstalling will cause it to download all mods again.

thanks i reinstalled it and it works
