### ISSUE TITLE
World is not loading.

### ISSUE THREAD

**Issue by Saniok126** [DarkPacks/SkyFactory-4#1902]
When trying to start single player or connect to the server game stops to responce and die. 
Have this logs in dev console. Any suggestions? 

[Log.txt](https://github.com/DarkPacks/SkyFactory-4/files/6454297/Log.txt)

**Comment by sam-kirby** [comment]
This pack has never and will never officially be uploaded to TLauncher - whatever you’ve downloaded is not our pack and not our problem to fix.
