### ISSUE TITLE
Crash when loading one specific singleplayer world

### ISSUE THREAD

**Issue by ItsBradBois** [DarkPacks/SkyFactory-4#1908]
I am receiving the message below when I try to play my single-player world, I am able make a new world and play that one so it seems to be specifically the one world. is there anything I can do to fix this?

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Topography (topography)

**Comment by sam-kirby** [comment]
Without more context it is difficult to say; however this message usually indicates `level.dat` is corrupt. You can either try loading with the backup level.dat file Minecraft automatically creates, or restore a world backup created by the included mod AromaBackup.

If you need help with this, I suggest asking on the Discord: https://discord.gg/darkosto

**Comment by ItsBradBois** [comment]
@sam-kirby Thank you so much! that worked!
