### ISSUE TITLE
Crash When Loading One Specific Single Player World

### ISSUE THREAD

**Issue by ItsBradBois** [DarkPacks/SkyFactory-4#1909]
## Bug Description

I am receiving the message below when I try to play my single-player world, I am able make a new world and play that one so it seems to be specifically the one world. is there anything I can do to fix this? thank you for your help!

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Topography (topography)

### Did this behavior use to work in the previous version?

 No idea

## Steps to Reproduce (for bugs)

 open Curseforge
1. Load Modpack
2. Try to join world
3. Error Code

## Logs

* Client/Server Log: [crash-2021-05-20_14.24.57-server.txt](https://github.com/DarkPacks/SkyFactory-4/files/6518441/crash-2021-05-20_14.24.57-server.txt)
* Crash Log: [crash-2021-05-20_14.24.57-server.txt](https://github.com/DarkPacks/SkyFactory-4/files/6518441/crash-2021-05-20_14.24.57-server.txt)

## World Information
* World Preset: Sky Factory 4
* Prestige Enabled: yes
* Modpack Version world created in: 4.2.2
* Additional Content Installed: none

## Client Information
* Modpack Version: 4.2.2
* Java Version: 1.12.2
* Launcher Used: CurseForge
* Memory Allocated: 6 GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sam-kirby** [comment]
Please see my comment on your previous issue: https://github.com/DarkPacks/SkyFactory-4/issues/1908#issuecomment-845423841
