### ISSUE TITLE
[RAM LEAK] SkyFactory 4 has an issue with a RAM leak using Shaders.

### ISSUE THREAD

**Issue by ImKatz** [DarkPacks/SkyFactory-4#1915]
## Bug Description
I have tested SkyFactory 4 with no Optifine or Shaders and there was no RAM leak.

Testing SkyFactory 4 with Optifine, but no Shaders also fails to produce a RAM leak.

However, adding a Shaders pack such as SEUS or BSL Shaders, when unfocusing the Minecraft window, your RAM begins to increase dramatically passing your maximum allocated until you are left with no RAM.

I wasn't finding any post about this online so I've decided to make one.

This RAM leak occurs using either MultiMC or Curseforge launcher. I have 10GB of RAM allocated.

Specs:

CPU: AMD Ryzen 5900x

GPU: NVIDIA 3080

RAM: 32GB 3800CL14

### Did this behavior use to work in the previous version?
Optifine: Tested on latest G5 file and previous F5 file for 1.12.2

Modpack: Not Tested. Running Latest Version of Modpack.

## Steps to Reproduce (for bugs)
1. Download Optifine
2. Download any Shaders
3. Drag Optifine into mods folder
4. Head to config, topography, SF4, (the world you are using).txt, edit in notepad, add "//" before sky, night, and day lines to unblur Shaders, save.
5. Launch SkyFactory 4
6.  Open Shaders folder and drag Shaders into folder.
7. Click Shaders, allow Minecraft time to switch.
8.  Load into a Single-player world.
9. Alt-tab or unfocus Minecraft, watch RAM get eaten.

## Logs
No crash if you force close Minecraft, maximum RAM on PC can be exceeded and lead to restarting the computer.

## World Information
* World Preset: Any
* Prestige Enabled: No
* Modpack Version world created in: 4.2.2
* Additional Content Installed: Optifine + Shaders

## Client Information
* Modpack Version: 4.2.2
* Java Version: jre1.8.0_291
* Launcher Used: MultiMC and Curseforge
* Memory Allocated: 10GB!
* Server/LAN/Single Player: Single Player
* Optifine Installed: Yes
* Shaders Enabled: Yes

**Comment by sam-kirby** [comment]
Optifine is closed source and not a component of this pack. We cannot see what changes they make to the rendering engine and are unable to support issues that occur when using it.

That being said there are a few things I can suggest you try.

1. Restart the game after turning on shaders.
2. The memory leak is not occurring in Java code as the JVM would catch it and throw an OOM exception. This means it is occurring in one of the native libraries. Check your graphics driver is up to date.
3. Plenty of people have successfully used shaders with this pack, perhaps ask them if they needed to do anything to avoid this issue. The support discord would be a good place to start https://discord.gg/darkosto 

Sorry I can't be more help, but there is only so much we can do in the face of a mod that makes such huge changes to Minecraft without making those changes available for others to inspect.

**Comment by ImKatz** [comment]
> Optifine is closed source and not a component of this pack. We cannot see what changes they make to the rendering engine and are unable to support issues that occur when using it.
> 
> That being said there are a few things I can suggest you try.
> 
> 1. Restart the game after turning on shaders.
> 2. The memory leak is not occurring in Java code as the JVM would catch it and throw an OOM exception. This means it is occurring in one of the native libraries. Check your graphics driver is up to date.
> 3. Plenty of people have successfully used shaders with this pack, perhaps ask them if they needed to do anything to avoid this issue. The support discord would be a good place to start https://discord.gg/darkosto
> 
> Sorry I can't be more help, but there is only so much we can do in the face of a mod that makes such huge changes to Minecraft without making those changes available for others to inspect.

1. I went ahead and tried this out without success. Turning on the Shaders, closing the game out, then relaunching it still caused a memory leak when un-focusing MC.
2. I reinstalled my graphic drivers, but problem continues to present itself.
3. That is my main reason for sharing this bug as I know for a fact people have used Shaders successfully with this pack. I'll try and join the discord and see if they can provide any support.

**Comment by sam-kirby** [comment]
Closing as nothing we can do at this time from the pack side.

**Comment by sam-kirby** [comment]
Should you identify a mod incompatibility with Optifine, please open a new issue requesting specific changes.

We do not have the resources to provide general support for Optifine.

**Comment by nopeless** [comment]
Had same issue. Easiest way to avoid it is to just go windowed before tabbing out
