### ISSUE TITLE
how  can i change the verson on aternos because i can only play the 4.1 verson

### ISSUE THREAD

**Issue by escadaking** [DarkPacks/SkyFactory-4#1920]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Aternos only allow you to play specific versions of certain modpacks which they provide installers for. You do not get scp/ftp access to the host and so you cannot upload a custom pack as far as I'm aware.

This is an Aternos limitation that we cannot get around. Your best course of action is to contact them and ask for a more up to date version of the pack to be provided.
