### ISSUE TITLE
Damage animation

### ISSUE THREAD

**Issue by HotrodNZ** [DarkPacks/SkyFactory-4#1921]
When taking damage there isnt the camera shake that indicates that you have taken damage. as I rely on this to know when I have taken damage this confuses me. i have looked through my video settings and cant find anything. is there a mod option I can turn off to fix this or is it a glitch?

**Comment by sam-kirby** [comment]
There is a mod in the pack called "Hurt Animation Remover". I believe this was added as the hurt animation makes Darkosto feel unwell.

Remove this mod from your instance and you should be good to go. If you need any help with this, please contact us on the Discord server: https://discord.gg/darkosto
