### ISSUE TITLE
When prestige is disabled the mods that are locked behind it are unavailable, I think it should be changed.

### ISSUE THREAD

**Issue by Ghost4576** [DarkPacks/SkyFactory-4#1922]
## Context
I believe that you should be able to toggle what mods you have if you have prestige disabled in world creation so that mods like Project e (which break the game) can be enabled/disabled.

**Comment by sam-kirby** [comment]
The only mod affected is ProjectE.

This behaviour will not be changed. If you wish to use it bypassing prestige you just need to run a single command.

Modifying the menu would take much more effort on our part.
