### ISSUE TITLE
Can't find Manganese Ore, or a recipe.

### ISSUE THREAD

**Issue by PigSuit** [DarkPacks/SkyFactory-4#1932]
I must be missing something. I can't seem to find Manganese to make manganese dioxide.
![2021-06-26_02 03 01](https://user-images.githubusercontent.com/86509547/123503837-792b1c80-d623-11eb-8cf4-adf6fc6d3290.jpg)

This is all I have, with the JEI running me around in circles trying to find it.

Thanks for any help.

**Comment by nathanfranke** [comment]
https://ftb.fandom.com/wiki/Manganese_Oxide
