### ISSUE TITLE
Mekanism Generators dependency errors

### ISSUE THREAD

**Issue by OrangeTurtle197** [DarkPacks/SkyFactory-4#1933]
## Bug Description

When starting the pack, Mekanism: Generators doesn't detect it's parent mod, Mekanism, and therefore errors out and halts the startup process.

### Did this behavior use to work in the previous version?

It worked last time I played, which was a month or two ago.

## Steps to Reproduce (for bugs)

https://youtu.be/eCwXPavrHWc

## Logs

* Client/Server Log:https://gist.github.com/OrangeTurtle197/08c67b17f58260e56155077fe2467c26#file-latest-log
* Crash Log:N/A

## World Information
* World Preset:N/A
* Prestige Enabled:N/A
* Modpack Version world created in:A world was not created
* Additional Content Installed:No

## Client Information
* Modpack Version:4.2.2
* Java Version:Java 8 (Bundled with ATLauncher; Java 16 was incompatible)
* Launcher Used:ATLauncher
* Memory Allocated:128 mb minimum, 4096 mb maximum
* Server/LAN/Single Player:Singleplayer (Client startup process)
* Optifine Installed:No
* Shaders Enabled:No

**Comment by sam-kirby** [comment]
I count at least 9 corrupt mods in this install, including Mekanism. This is either an issue with your storage device or with your internet connection during the download.

```
[12:32:16] [main/ERROR]: Unable to read the jar file Mekanism-1.12.2-9.8.3.390.jar - ignoring
java.util.zip.ZipException: error in opening zip file
```

As this is not an issue with the pack, I'm going to close this issue. If you need support, please use the Discord server's dedicated channels: https://discord.gg/darkosto
