### ISSUE TITLE
Prestige is not locking its features

### ISSUE THREAD

**Issue by Facu8104** [DarkPacks/SkyFactory-4#1935]
## Bug Description
I created a default world in Aternos, a free server hosting website that automatically installs the modpack in the server, using its default configuration, so Prestige was not enabled initially. Then, I forced Prestige with the `/prestige force enabled` command (because Aternos don't let their users change the .cfg files) and I was able to open the Prestige menu. The problem is that mods or items like the hopping bonsai pot are enabled (I can interact with them, craft them, or see them in the JEI menu), even if I haven't unlocked them yet, like if Prestige was disabled.
I've been playing for a while and I don't want to restart the world at this point, but I figured that maybe by creating a Singleplayer world with Prestige enabled, then uploading it to Aternos, and then using the `/prestige force enabled` command in the console would work, because that world was created with Prestige enabled,  and the server will try to disable it when it's loaded. I read in other issues that enabling and disabling Prestige, or vice versa doesn't work, and that's makes my idea more viable for me.

### Did this behavior use to work in the previous version?
This is my first time using this modpack

## Steps to Reproduce (for bugs)
1. Create a new world without Prestige enabled
2. Enable Prestige with the `/prestige force enabled` command
3. Notice that the mods and items are still visible

## Logs
* Client/Server Log: These are the server logs of the latest time I played on it: https://mclo.gs/Py1OZ71
* Crash Log: None

## World Information
* World Preset: Sky Factory 4
* Prestige Enabled: Not initially
* Modpack Version world created in: 4.2.2
* Additional Content Installed: OptiFine

## Client Information
* Modpack Version: 4.2.2
* Java Version: 8 (Update 291)
* Launcher Used: TLauncher (Version 2.8)
* Memory Allocated: 7 GB
* Server/LAN/Single Player: Server
* Optifine Installed: Yes (1.12.2 HD U G5)
* Shaders Enabled: No

## Server Information
* Java Version: No idea
* Operating System: No idea
* Hoster/Hosting Solution: Aternos
* Sponge (Non-Vanilla Forge) Server: No

**Comment by sam-kirby** [comment]
If you are able to delete files, then deleting your player’s game stage data will likely solve your issue.

If not, you really need to find a better host as this one sounds incredibly limiting.
