### ISSUE TITLE
I have no sound at all

### ISSUE THREAD

**Issue by Albus931** [DarkPacks/SkyFactory-4#1936]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by sam-kirby** [comment]
Check the volume slider? That's all the advice I can give based on zero information.
