### ISSUE TITLE
Mob Spawners spawning wrong?

### ISSUE THREAD

**Issue by FrijDom** [DarkPacks/SkyFactory-4#1937]
## Bug Description

Mobs spawn in seemingly random spaces, and not at all inside mob farm.

### Did this behavior use to work in the previous version?

Not that I know of.

## Steps to Reproduce (for bugs)

1. Create 5-block tall mob farm (3 tall inside)
2. Place zombie/skeleton/spider/creeper spawner in roof and cover so it doesn't let light in.
3. Walk away a distance, and watch as the mobs spawn only outside of the farm, if they spawn at all.

## Logs

* Client/Server Log: https://gist.github.com/FrijDom/5ede5d606d588df1d2f47d0100359b97
* Crash Log:

## World Information
* World Preset:Material Girl in a Material World
* Prestige Enabled:Yes
* Modpack Version world created in: 4.2.0
* Additional Content Installed: Inventory Tweaks, Edited Crafttweaker due to typo in Prestige

## Client Information
* Modpack Version: 4.2.2
* Java Version: 1.8
* Launcher Used: Twitch/CurseForge
* Memory Allocated: 7008 MB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sam-kirby** [comment]
Putting the spanner in the roof basically guarantees mobs will only spawn on the roof.

> mobs spawn with their legs at either the same layer as the spawner block, one block above it, or one block below it.

They cannot spawn in the block below or at the same level as the roof is in the way and all mobs require 2 blocks vertical space to spawn from a spawner.

See: https://minecraft.fandom.com/wiki/Spawner#Mechanics

**Comment by sam-kirby** [comment]
Also, would you mind telling us what the typo is so we can fix it for everyone?

**Comment by FrijDom** [comment]
Ah, I see. That being the case doesn't make a lot of sense, but I do understand what you mean. Thank you.

As for the typo, from my explorations into the code, it's due to the Prestige mod being built for older versions of Crafttweaker. In older versions, MCPotionEffect.class was misnamed MCPotionEfect.class, and was called as such throughout the rest of the mod. I've so far been unsuccessful in my attempts to recode the Prestige mod to use the newer versions of Crafttweaker.

**Comment by FrijDom** [comment]
https://gist.github.com/FrijDom/bc597a9e4d622e4dc535eab9859a1d28

One of the crash reports of the error in progress. My temporary fix was to simply rename the class file in Crafttweaker, but that obviously breaks the rest of the potion functionality in the mod.

**Comment by sam-kirby** [comment]
> Ah, I see. That being the case doesn't make a lot of sense, but I do understand what you mean. Thank you.

You can blame Mojang for spawner logic. There are plenty of online tutorials that show how to get the most mob spawns using them. Essentially you want a 9x9 (internal area) column with the spawner at least 1 block off the floor and at least 5 blocks high inside (more if spawning something tall like endermen).

Mobs spawned by a spawner don't need ground to spawn on, so you can put the spawner high up and have them take fall damage. If you do this, you'll want to put blocks on top of the spawner to stop any mobs from getting stuck on top of it and staying there.

> As for the typo, from my explorations into the code, it's due to the Prestige mod being built for older versions of Crafttweaker. In older versions, MCPotionEffect.class was misnamed MCPotionEfect.class, and was called as such throughout the rest of the mod. I've so far been unsuccessful in my attempts to recode the Prestige mod to use the newer versions of Crafttweaker.

Okay, this is way outside what I was expecting. Unless we find a bug in the current Crafttweaker or a new feature we want to use from a new version, we have no compelling reason to update.

We can refactor and recompile prestige then if necessary.
