### ISSUE TITLE
No smeltery controller

### ISSUE THREAD

**Issue by AinSophAu** [DarkPacks/SkyFactory-4#1938]
## Bug Description

 No smeltery controller even if in creative. Tried enabling and disabling prestige and it's still like this.

## Steps to Reproduce (for bugs)

1.Download Skyfactory-4 4.2.2 on curse forge (latest version)
2.Search Smeltery Controller in creative or recipe browser
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:Tutorial
* Prestige Enabled:Disabled
* Modpack Version world created in:4.2.2
* Additional Content Installed:None

## Client Information
* Modpack Version:4.2.2
* Java Version:
* Launcher Used:Curse forge
* Memory Allocated:
* Server/LAN/Single Player:Single player
* Optifine Installed:No
* Shaders Enabled:No

**Comment by sam-kirby** [comment]
If you start with prestige enabled, you cannot later disable it without taking additional steps to unlock the content it locks access to.

Running the command `/function triumph:classic_mode` should get you most of the way there.
