### ISSUE TITLE
"Eating Dirt" advancement description does not match requirements

### ISSUE THREAD

**Issue by Jason7wastaken** [DarkPacks/SkyFactory-4#1940]
## Bug Description
<"Eating dirt" advancement requirements DO NOT match the description>

## Steps to Reproduce (for bugs)
1. Cook any acorn other than dirt
2.advancement not granted
3.advancement description says "any acorn"
4.Cook dirt acorn and get advancement

## World Information
* World Preset:<Skyfactory 4>

## Client Information
* Modpack Version:<4.2.2>
* Java Version:<1.12.2>
* Launcher Used:<curseforge launcher>
* Server/LAN/Single Player:<single>

**Comment by sam-kirby** [comment]
The title and picture tell you what to do; the description is a more general tip. It does not say cook any acorn to get this advancement. It says eat dirt; any acorn can be cooked to improve its nutritional value.
