### ISSUE TITLE
Inscriber on SkyFactory 4.2.2 is not working

### ISSUE THREAD

**Issue by GlacieredSteven** [DarkPacks/SkyFactory-4#1943]
Hi there I'm having a problem with the inscriber i have all the items put in just like in the link below and even have wireless power going to it and still nothing. Is it something im doing wrong?

https://github.com/Darkosto/SkyFactory4Issues/issues/463

**Comment by sam-kirby** [comment]
https://github.com/DarkPacks/SkyFactory-4/issues/463#issuecomment-491092347

The chisel is no longer part of the recipe, so if you’re doing exactly as in the screenshot it’s no surprise it’s not working.

Use JEI to help you get the recipes right.

**Comment by GlacieredSteven** [comment]
Ya did not use the right link i was using a cast but found out if a just us a combustible generator instead of wireless power it works fine
