### ISSUE TITLE
Serverstart.bat crash

### ISSUE THREAD

**Issue by notoriousjdog** [DarkPacks/SkyFactory-4#1944]
![image_2021-07-20_133318](https://user-images.githubusercontent.com/40730694/126257845-b688e512-ad4f-48e7-a301-325191e700df.png)
## Bug Description
When launching the ServerStart.bat for the first time, it crashes instantly.

### Did this behavior use to work in the previous version?
I am not downloading the server

## Steps to Reproduce (for bugs)
1. Extract zip
2.  use install.bat 
3. run serverstart.bat

## Logs
Can not reach 

## World Information
#Minecraft server properties
#Mon Apr 15 23:38:58 BST 2019
spawn-protection=0
max-tick-time=60000
generator-settings={"Topography-Preset"\:"Sky Factory 4"}
force-gamemode=false
allow-nether=true
gamemode=0
broadcast-console-to-ops=true
enable-query=false
player-idle-timeout=0
difficulty=1
spawn-monsters=true
op-permission-level=4
pvp=true
snooper-enabled=true
level-type=DEFAULT
hardcore=false
enable-command-block=true
max-players=20
network-compression-threshold=256
resource-pack-sha1=
max-world-size=29999984
server-port=25565
server-ip=
spawn-npcs=true
allow-flight=true
level-name=world
view-distance=10
resource-pack=
spawn-animals=true
white-list=false
generate-structures=true
online-mode=true
max-build-height=256
level-seed=
prevent-proxy-connections=false
enable-rcon=false
motd=\u00A7d\u00A7oSkyFactory 4\: Server\u00A7r - \u00A74v4.2.2

## Server Information
* Java Version: latest 64-bit
* Operating System: windows
* Hoster/Hosting Solution: my own server
* Sponge (Non-Vanilla Forge) Server: forge-1.12.2-14.23.5.2854

**Comment by sam-kirby** [comment]
Forge for Minecraft 1.12.2 is only compatible with Java 8.
