### ISSUE TITLE
Ctrl-Z Achievement Bug

### ISSUE THREAD

**Issue by Daneb1** [DarkPacks/SkyFactory-4#1945]
## Bug Description

 The Ctrl-Z achievement didn't trigger when I crafted an "Uncrafting Grinder" from the Cyclic mod
Edit: The achievement triggered when I exited and reopened the world with the uncrafting grinder in my hotbar

### Did this behavior use to work in the previous version?

 I am unsure. I only recently began playing Skyfactory 4. 

## Steps to Reproduce (for bugs)

1. Craft/spawn in an uncrafting grinder.
2. Check "Age of Power" achievement page
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset: Sky Factory 4 - Classic world type
* Prestige Enabled: Yes
* Modpack Version world created in: 1.5-High
* Additional Content Installed: None

## Client Information
* Modpack Version: 1.5-High
* Java Version: JRE 8 update 231
* Launcher Used: Technic Launcher
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sam-kirby** [comment]
This pack has never been released on the Technic launcher and 1.5-High does not correspond to any version we've released elsewhere.

We cannot help with issues occurring in a clone of our pack.
