### ISSUE TITLE
Can not get port to open when hosting a server

### ISSUE THREAD

**Issue by notoriousjdog** [DarkPacks/SkyFactory-4#1946]
## Bug Description
Whenever I try to use Hamachi to host a server opened to on LAN as my friend connects my internet will crash, I will hear him speak for a couple seconds and he can not hear me.

### Did this behavior use to work in the previous version?
No, even when hosting a minecraft server the port would only remain open for a certain amount of time after I joined my own server. 

## Steps to Reproduce (for bugs)
1. Open ServerStart.bat
2. Server will start
3. Port will remain closed on https://www.yougetsignal.com/tools/open-ports/ even after joining myself

## Logs
https://pastebin.com/LQh0fpRH
file was too large so could only include ending

## World Information
* World Preset:{"Topography-Preset"\:"Sky Factory 4"}
* Prestige Enabled:false
* Modpack Version world created in: lat4est
* Additional Content Installed: none

## Client Information
* Modpack Version: latest
* Java Version:java 8
* Launcher Used: curseforge
* Memory Allocated:12GB
* Server/LAN/Single Player: Server
* Optifine Installed:yes
* Shaders Enabled:yes

## Server Information
* Java Version:java 8
* Operating System:Windows
* Hoster/Hosting Solution: Java
* Sponge (Non-Vanilla Forge) Server: forge-1.12.2-14.23.5.2854

images of port-forward settings and firewall can be included

**Comment by sam-kirby** [comment]
Am I understanding correctly that you are having issues configuring your network to allow traffic to your server?

This Github issues page is for reporting bugs or making feature requests for SkyFactory 4. I don't see anything like that in your report.

If you need help with network configuration you'd be better off asking on the appropriate channel on Discord; https://discord.gg/darkosto
