### ISSUE TITLE
mob models are not working/existing

### ISSUE THREAD

**Issue by himiii** [DarkPacks/SkyFactory-4#1950]
## Bug Description

 mob models can't be created, when I try to click on it to see the recipe it doesn't pop up. The simulation chamber has
the same problem as if these mob models are something that can only be dropped, I soon realized this problem, by the way
i searched on youtube and found the recipes of them but they still don't work

### Did this behavior use to work in the previous version?

 I don't know I recently joined so all of this is new to me.

## Steps to Reproduce (for bugs)

1. ----
2. ----
3. ----

## Logs

* Client/Server Log:  -----
* Crash Log:  -----

## World Information
* World Preset: ----
* Prestige Enabled: no
* Modpack Version world created in: Version 1.12.2
* Additional Content Installed:  no

## Client Information
* Modpack Version: Version 1.12.2
* Java Version: 1.8.0
* Launcher Used: Tlauncher
* Memory Allocated: ----
* Server/LAN/Single Player: Single Player
* Optifine Installed: no
* Shaders Enabled: no

**Comment by sam-kirby** [comment]
We provide no support for modified or redistributed versions of the pack.
