### ISSUE TITLE
java.lang.ClassCastException Error at Startup

### ISSUE THREAD

**Issue by fairilights** [DarkPacks/SkyFactory-4#1951]
## Bug Description

 Whenever I start the server I get a java.lang.ClassCastException error. 

### Did this behavior use to work in the previous version?

 I am able to play the modpack in singleplayer but on each version of the modpack I try to load a server on, I get the same issue.

## Steps to Reproduce (for bugs)

1. Download server
2. Run Install.bat
3. Run ServerStart.bat- creating a crash
4. Edit the ServerStart.bat to add pause instead of exit 

## Logs

* Client/Server Log: https://pastebin.com/Vezw6615
* Crash Log: N/A

## World Information
* World Preset: DEFAULT
* Prestige Enabled: no
* Modpack Version world created in: 4.2.2
* Additional Content Installed: N/A

## Client Information
* Modpack Version: N/A
* Java Version: N/A
* Launcher Used: N/A
* Memory Allocated: N/A
* Server/LAN/Single Player: N/A
* Optifine Installed: N/A
* Shaders Enabled: N/A

## Server Information
* Java Version: Version 8 Update 301
* Operating System: Windows
* Hoster/Hosting Solution: 
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
You are not using Java 8. Java 8 has no concept of modules yet the error you are having mentions them: `(jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap'`

You are therefore using Java 9+.

Your report implies you also have Java 8 installed so doing any one of the following should resolve your issue:

1) Remove the later version of Java if you have no need of it.
2) Update the %PATH% environment variable such that Java 8 appears first.
3) Use an absolute path in the start script - i.e. Replace `java` with `"C:\Program Files\Java\jre1.8.0_301\bin\java.exe"` (assuming Orcale's Java in the default location - if you installed another vendor's Java or installed to a custom location, you will have to figure the path out). You must include the `"`.
