### ISSUE TITLE
hellllllllllllllllllllllllllllllllllllllppppppppppppppppppppppppppppppppppppppppppppppp

### ISSUE THREAD

**Issue by harrobe123** [DarkPacks/SkyFactory-4#1968]
## Bug Description

wont let me play a bunch of mods NOT sky factory 4

## Steps to Reproduce (for bugs)

1.uhhhhhhhh dont know
PLEASE HELP

2.
3.

## Logs

* Client/Server Log:attached
[2021-09-02-5.log](https://github.com/DarkPacks/SkyFactory-4/files/7100560/2021-09-02-5.log)

* Crash Log:

**Comment by harrobe123** [comment]
why?

**Comment by harrobe123** [comment]
i used the template

**Comment by sam-kirby** [comment]
You didn't complete the template. The bot is very sensitive.

However, if you're not playing SkyFactory 4 why would you report a bug to SkyFactory 4?

**Comment by harrrobe** [comment]
> You didn't complete the template. The bot is very sensitive.
> 
> However, if you're not playing SkyFactory 4 why would you report a bug to SkyFactory 4?

Sorry for that I don't know I think it was sky factory 4 but I tried to say something not sure anyway it's not a problem anymore
