### ISSUE TITLE
Make "Toasted Bread" from Tiny Progressions count as "toast", enabling Cooking for Blockheads' "Toaster"

### ISSUE THREAD

**Issue by matt-zb** [DarkPacks/SkyFactory-4#1970]
## Context

 I believe that the category "toast" should be applied to "Toasted Bread" from Tiny Progressions. As of right now, the Toaster block from Cooking for Blockheads is entirely useless, as it does not count "Toasted Bread" as "toast". Seeing as there are no other items in the pack that qualify as "toast", it seems like a simple change.

[Toaster: Cooking for Blockheads Wiki](https://blay09.net/mods/cookingforblockheads/toaster.html#crafting)

## Config/Script Details (if desired)
 N/A

**Comment by sam-kirby** [comment]
Given there is no support for CraftTweaker from Cooking For Blockheads we'd have to write a mod who's sole purpose is to make this change.

It would be better to request this from Tiny Progressions.

**Comment by matt-zb** [comment]
Thank you for your reply, I will post the request there.
