### ISSUE TITLE
Can't craft redstone sapling 

### ISSUE THREAD

**Issue by Pupubow** [DarkPacks/SkyFactory-4#1973]
## Bug Description

I born in swampland. I can't get any red dye. I feel very upset.

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by sam-kirby** [comment]
You can use Beetroot in place of red dye; you can get beetroot seeds from breaking grass.
