### ISSUE TITLE
Advancments dont work in multyplayer server PLEASE FIX THIS

### ISSUE THREAD

**Issue by WeGood123** [DarkPacks/SkyFactory-4#1974]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
They absolutely do work in multiplayer. This has been tested extensively.

Without further details of your setup there is nothing I can do to support you.
