### ISSUE TITLE
my game crashes when loads

### ISSUE THREAD

**Issue by big-cum-gamer** [DarkPacks/SkyFactory-4#1977]
## Bug Description
<only my main server is crashing as i open it every other server is fine this are all singe player servers>
<it said error code -1 >

### Did this behavior use to work in the previous version? 
<i do not know i dint play the previous version>

## Steps to Reproduce (for bugs)

* Client/Server Log:<
[latest.log](https://github.com/DarkPacks/SkyFactory-4/files/7278167/latest.log)
>
* Crash Log:<
[crash-2021-10-04_15.50.03-server.txt](https://github.com/DarkPacks/SkyFactory-4/files/7278152/crash-2021-10-04_15.50.03-server.txt)
>

## World Information
* World Preset:<idk>
* Prestige Enabled:<yes>
* Modpack Version world created in:<4.2.2+>
* Additional Content Installed:<no>

## Client Information
* Modpack Version:<4.2.2>
* Java Version<1.12.2>
* Launcher Used:<curseforge>
* Memory Allocated:<no>
* Server/LAN/Single Player:<single player>
* Optifine Installed:<no>
* Shaders Enabled:<no>

## Server Information
* Java Version:<1.12.2>
* Operating System:<windows 10>
* Hoster/Hosting Solution:<no>
* Sponge (Non-Vanilla Forge) Server:<no>

**Comment by sam-kirby** [comment]
Looks like level.dat is corrupted. This usually occurs when the server is improperly shutdown.

Restoring a backup is the simplest fix.

**Comment by big-cum-gamer** [comment]
how do i restroe my simplex file?
