### ISSUE TITLE
pls help?

### ISSUE THREAD

**Issue by harrobe123** [DarkPacks/SkyFactory-4#1996]
## Bug Description

not getting enough of one item in packeger coming from filing cabinet

## Steps to Reproduce (for bugs)

1.put a filing cabinet with any sapling on top[as long as its one from the bonsai mod] with a hopping bonsai pot [as long as its one from the bonsai mod 
2.put filing folders in for acorn and resin and link up the itemducts with servo and filter to a packeger
3.watch as the packager gets over filled with one thing

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:sky factory 4
* Prestige Enabled:no
* Modpack Version world created in: minecraft
* Additional Content Installed:electro bobs wizardry, lootbags

## Client Information
* Modpack Version:4.2.2
* Java Version:launcher deafult
* Launcher Used:ATlauncher
* Memory Allocated:?
* Server/LAN/Single Player:single player
* Optifine Installed:no
* Shaders Enabled:wishes

**Comment by harrrobe** [comment]
#2050
