### ISSUE TITLE
crash immediately when loading world

### ISSUE THREAD

**Issue by glag15** [DarkPacks/SkyFactory-4#1997]
## Bug Description

using atlauncher the game loads up to the menu then when i create a new world or try to log in a server the game tried to load the crash to launcher

### Did this behavior use to work in the previous version?

yes tried 4.2.2 4.1.0 4.0.1 all behaved the same

## Steps to Reproduce (for bugs)

1.load skyfactory 4 
2.enter a world\server
3.crash

## Logs

* Client/Server Log:
* Crash Log:
[latest.log](https://github.com/DarkPacks/SkyFactory-4/files/7542306/latest.log)

## World Information
* World Preset:default/ topography-skyfactory4 
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:4.2.2
* Java Version:build 1.8.0_292-b10
* Launcher Used:atlauncher
* Memory Allocated:6gb
* Server/LAN/Single Player:all
* Optifine Installed:no
* Shaders Enabled:no
using linux/manjaro

**Comment by sam-kirby** [comment]
Your log does not show the game crashing; either it is truncated or something external is killing the game.

Are you running the game with enough memory overhead?

**Comment by glag15** [comment]
i have 16gb on my system so it should be fine (i pretty much always have 4-5 gb mem left when trying to run it)
thing is i can run other modpacks with the same java version and same launcher

**Comment by sam-kirby** [comment]
Which version of Java? Your log shows you're using a different version to what you expect. Your log shows you're using 1.8.0_202.

```
[03:54:02] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_202, running on Linux:amd64:5.13.19-2-MANJARO, installed at /home/gal/.local/share/atlauncher/runtimes/minecraft/jre-legacy/linux/jre-legacy
```

In the instance folder, is there a file called `hs_err_pid<number>.log`?

**Comment by glag15** [comment]
weird when i type in terminal java -version this is what i get
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

also there wasn't a hs_err_pid<number>.log

**Comment by glag15** [comment]
ok thanks for the help.
reinstalling java 11 and the other program seems to solve it
