### ISSUE TITLE
see this

### ISSUE THREAD

**Issue by harrobe123** [DarkPacks/SkyFactory-4#2001]
## Bug Description

cant pull out polymer clay outof auto crafter unless going in auto crafter

## Steps to Reproduce (for bugs)

1.place down auto crafter and put in recipie for polymer clay
2.put in item extraction thing 
3.link it up to thingy machine from the mod that has the deep learner

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by harrrobe** [comment]
Didn't have the item duct on the right side nor I didn't have a servo
