### ISSUE TITLE
Skyfactory 4 Server problem

### ISSUE THREAD

**Issue by federico-de-iaco** [DarkPacks/SkyFactory-4#2003]
## Bug Description

Suddenly the server doesnt't work properly. When i run "ServerStart.bat" it seems like everything is ok, but when i open minecraft the server is unreachable showing a timeout. 

### Did this behavior use to work in the previous version?

I just tried it in this version, so i don't know. However the first and the second time i started the server i could play with my friends.

## Steps to Reproduce (for bugs)

I don't know:
1)Just run the server
2)Play for a while
3)Shut down the server
4)Turn off your PC
5)Turn on your PC
6)Restart the server and it shouldn't work
But, for example, this happened to me the third time i restarted my pc after few days.

## Logs

* Server Log: https://gist.github.com/federico-de-iaco/dc1eb0a579cc0364e50243696b515647

## World Information
* World Preset: standard
* Prestige Enabled:
* Modpack Version world created in: SkyFactory-4_4.2.2
* Additional Content Installed:

## Client Information
* Modpack Version: SkyFactory-4_4.2.2
* Java Version:
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)
* Launcher Used: curseforge
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)
* Operating System: Windows 10 64 bit
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
There is no evidence in the server log that you have attempted to connect.

This suggests something in your network setup has probably changed. Note that both internal and external IP addresses are usually dynamically allocated and subject to change.

As this doesn't appear to be an issue with the server, it would be more appropriate to seek support through Discord. There is a #sf4-server-support channel at https://discord.gg/darkosto

**Comment by federico-de-iaco** [comment]
I set static IP on my PC and on my router before setting up the server (the server is running in the same pc where i play), but on the game it can't connect after a couple of days in which it worked (for me i connect through my local IP, while for my friends i send them an address translated by a DNS service, so for them my IP is not important since they use a "string" to connect).

**Comment by sam-kirby** [comment]
To clarify - you are not able to connect while using a client on the same machine using either your local IP address or local loopback? (Local loopback is usually on 127.0.0.1 or `localhost`)
