### ISSUE TITLE
I can't connect to a multiplayer server

### ISSUE THREAD

**Issue by LeJoker747** [DarkPacks/SkyFactory-4#2023]
## Bug Description

When I'm on the screen of the multiplayer server, in the top left corner I see I'm not online so I try to re-login but it say my account is migrated, I think it's because I migrated my account to Microsoft but I don't know how to fix it.

### Did this behavior use to work in the previous version?

Yes In all version.

## Steps to Reproduce (for bugs)

1.
![image](https://user-images.githubusercontent.com/84645528/147658882-9d89d48a-24e5-4624-a708-1c1504e512ab.png)

2.
![image](https://user-images.githubusercontent.com/84645528/147658854-ced98a14-1e1a-465d-8ed5-1b42f3da88b0.png)

3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:Normal
* Prestige Enabled:No
* Modpack Version world created in:4.2.2
* Additional Content Installed:No

## Client Information
* Modpack Version:4.2.2
* Java Version:
* Launcher Used:CurseForge
* Memory Allocated:7Gb
* Server/LAN/Single Player:Server
* Optifine Installed:No
* Shaders Enabled:No

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
As stated in my reply to your previous issue report, `ReAuth` does not support or understand Microsoft accounts, but it doesn't really matter as it won't stop you trying to connect. If you ignore it and try to connect to your server it should work.

You can remove the mod if you would prefer not to see the red cross.

**Comment by LeJoker747** [comment]
Oh it work, thank you.
