### ISSUE TITLE
I am trying to set up a personaly Sky Factory 4 server for myself and friends and it's Failing

### ISSUE THREAD

**Issue by gohaveaniceday** [DarkPacks/SkyFactory-4#2026]
![image](https://user-images.githubusercontent.com/81695121/147880952-18dba252-423d-4ab2-86ce-acaf7593c872.png)
I am trying to set up a Sky Factory 4 server for me and some friends of mine and I don't understand what I am doing wrong or even if I am doing something wrong. I use the "Install.bat" file, create a eula.txt file, add in the text and set it to true, I then use ServerStart.bat and then it just appears for a moment and then disappears with nothing else happening. I have also selected the generation in server.properties as well so I don't know what else I am supposed or could do.

I started the ServerStart bat in Powershell and these are the errors I am getting
![unknown](https://user-images.githubusercontent.com/81695121/147880962-c6f82b2c-59a5-4d9f-99dc-bca8ad604bca.png)

**Comment by sam-kirby** [comment]
This error is a result of using an unsupported version of Java; you must use Java 8, anything more modern is not supported due to a limitation of Forge for 1.12.2.

If you need help setting up Java 8, you can get support on the Discord server https://discord.gg/darkosto
