### ISSUE TITLE
[topography] Skygrid generating millions of blocks between islands

### ISSUE THREAD

**Issue by ryuujo1573** [DarkPacks/SkyFactory-4#2040]
## Bug Description

Island was created using `/topography island new <player>`.
I wish I can change the distance between skyblocks and remove the strange random blocks between them.
Thank you.

## Steps to Reproduce (for bugs)

1.  Use presets: 
```yml
generator-settings={"Topography-Preset":"Skygrid"}
level-type=skygrid

```
2. Type `/topography island new <player>`, then the <player>'s island will be generated at 1000 metres away.
3. there are tons of different blocks at around 500 metres.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset: Skygrid
* Prestige Enabled:
* Modpack Version world created in: 4.2.4
* Additional Content Installed: worldedit

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Skygrid is supposed to be an infinite grid of random blocks; it's generation is not managed by topography and the island command may be doing something unexpected here.

The world should generate as in the linked image:

https://media.forgecdn.net/attachments/193/166/2017-02-03_16.png

**Comment by sam-kirby** [comment]
On world types managed by Topography, you can change the dimension definition to alter island spacing.
