### ISSUE TITLE
Unplayable fps 

### ISSUE THREAD

**Issue by Breet11** [DarkPacks/SkyFactory-4#2047]
## Bug Description

 I am having very low fps  ( 5-20 ). And I hadn't even played the game, just created world and digged 1 whole tree. The settings are: everything on low and 7 chunks 
     Pc specs: 
CPU:R5 2600
GPU:RX 580 (8GB)
Ram: 16 GB DDR4 (3200 MHZ)

### Did this behavior use to work in the previous version?

 Haven't played on previous versions 

## Steps to Reproduce (for bugs)

1.Open the client 
2.Enter the world 
3.Having very low  (unplayable ) fps 

## Logs

* Client/Server Log:
* Crash Log: none 

## World Information
* World Preset: Didn't do anything just clicked create new world ( so it's  standart I assume) 
* Prestige Enabled: no 
* Modpack Version world created in: 4.2.3
* Additional Content Installed: none 

## Client Information
* Modpack Version: 4.2.3
* Java Version: latest 
* Launcher Used: Tlauncher 
* Memory Allocated: 10GB 
* Server/LAN/Single Player:
* Optifine Installed: didn't install anything else except just modpack 
* Shaders Enabled:

**Comment by sam-kirby** [comment]
We do not control what people upload to TLauncher using the name of this pack.

**Comment by Breet11** [comment]
I downloaded this modpack from curseforge than uploaded this in Tlauncher

**Comment by GanterPenguin** [comment]
Try to disable terrain animations. It may help on AMD GPU
