### ISSUE TITLE
itemducts!

### ISSUE THREAD

**Issue by harrobe123** [DarkPacks/SkyFactory-4#2050]
## Bug Description

well im trying to sort acorns and resins into packgers but they keep filling up with the file thats closest to the itemduct and distrputing the other item as much

### Did this behavior use to work in the previous version?

i dont want to check other versions

## Steps to Reproduce (for bugs)

1.get a filing cabinet fill it up with the files you need and what's giving it the items
2.link a itemduct up too it by the back
3.build a packger under the itemduct

## Logs

* Client/Server Log:it porbably dont need log
* Crash Log:its not a crash

## World Information
* World Preset:
* Prestige Enabled:forgot
* Modpack Version world created in:1.12.2
* Additional Content Installed:electrobobs wizardry, waystones,some other mods 

## Client Information
* Modpack Version:1.12.2
* Java Version:dunno
* Launcher Used:ATLauncher
* Memory Allocated:
* Server/LAN/Single Player:single player 
* Optifine Installed:no
* Shaders Enabled:no

**Comment by harrobe123** [comment]
add label type:bug

**Comment by Layarion** [comment]
1) make the cabinet feed the packager instead, or 2) use ender utilities pipes - they try to split the load or 3) use SimpleStorageNetworks's processing cable. It can be setup to put a ratio of items in, for every item it pulls out. So you can tell it to put 4 of something in for every 1 of other thing it pulls out.

**Comment by harrrobe** [comment]
> 1. make the cabinet feed the packager instead, or 2) use ender utilities pipes - they try to split the load or 3) use SimpleStorageNetworks's processing cable. It can be setup to put a ratio of items in, for every item it pulls out. So you can tell it to put 4 of something in for every 1 of other thing it pulls out.

I used the filter from the thermal dynamics mod that added itemducts I also found out about the purple ones that act as a servo filter hybrid which is cool
