### ISSUE TITLE
Running server on Raspberry Pi

### ISSUE THREAD

**Issue by oguldon** [DarkPacks/SkyFactory-4#2051]
Hello, 

I've seen a few a few modded minecraft servers running on a raspberry pi
just wanted to know if anyone got SF4 running on one? if so how?
i'm able to get the boring vanilla server running (its a laggy)

thank you in advance

**Comment by sam-kirby** [comment]
@oguldon You haven't said which RPi you're using, but I've tested with an RPi 4 (4GB).

A Raspberry Pi does not make the best host, but it can certainly do it with fairly good performance in the early game. There are a few things you need to consider however:

1) SD cards are far too slow for the server to run from. You must use a fast external USB disk for the server files. I used an old SSD in a USB3 enclosure.
2) You need to use a 64-bit OS to support allocating enough RAM, and for some performance improvements. I used Ubuntu Server for RPi (64-bit) available here: https://ubuntu.com/download/raspberry-pi
3) As with all Forge 1.12.2 servers, you need to use Java 8. This is `openjdk-8-jre-headless` on Ubuntu.

**Comment by oguldon** [comment]
Thank you for that, ill be trying it on an RPi 4 (8GB) 
thought it would be fun to try and something to do in this stinking melb heat

thank you again
