### ISSUE TITLE
Cant get past "Select amount" screen for me crafting

### ISSUE THREAD

**Issue by GenesisCD** [DarkPacks/SkyFactory-4#2060]
## Bug Description

 When trying to craft using the me crafting system clicking the "next" button on the "select amount" screen closes the menu

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset: Classic
* Prestige Enabled: No
* Modpack Version world created in: 4.2.4
* Additional Content Installed: Wireless crafting terminal

## Client Information
* Modpack Version:4.2.4
* Java Version:1.12.2
* Launcher Used:Curse Forge
* Memory Allocated:7096m
* Server/LAN/Single Player:Single Player
* Optifine Installed:N/A
* Shaders Enabled:N/A

**Comment by sam-kirby** [comment]
The menu will close if you do not have sufficient power in your ME network for all the operations you are trying to power. Make sure you have ME Cells and Dense Cells connected to the network.
