### ISSUE TITLE
Can't break the first tree

### ISSUE THREAD

**Issue by Lorddeamos8294** [DarkPacks/SkyFactory-4#2064]
## Bug Description
 ok I'm hosting a server using apex hosting, I've created the world and I spawn on the tree but I can't break anything, everytime I do it just comes back even when I go into creative mode and I'm not sure what to do

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
This sounds like vanilla spawn protection mechanics - a system designed to prevent non-operators from creating traps at world spawn for new players joining.

Make sure you are either:
1) an operator by doing `/op your_name` on the server console
2) turn off spawn protection by setting `spawn-protection=0` in the server.properties file
