### ISSUE TITLE
The Twilight Forest portal doesn't work

### ISSUE THREAD

**Issue by kamisama214** [DarkPacks/SkyFactory-4#2068]
## Steps to Reproduce (for bugs)

1.
![unknown (1)](https://user-images.githubusercontent.com/100639905/156071778-26eb229c-7094-4032-b6d6-8025238434e1.png)

2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by sam-kirby** [comment]
This could mean it can't find a safe place to spawn you in range, try building the portal somewhere a fair way away from where you are now.

**Comment by kingofstrike123** [comment]
I don't think you should build any portal, you have to use the twilight cake
