### ISSUE TITLE
Item Floating in the air

### ISSUE THREAD

**Issue by EchterTill** [DarkPacks/SkyFactory-4#2076]
## Bug Description
Sometimes if an item drops, it gets stuck in the air and cannot be picked up... It is moving up and down very quickly and is not spinning anymore...

### Did this behavior use to work in the previous version?
It already worked 2 years ago

## Steps to Reproduce (for bugs)
1. Play on a server
2. Break some blocks
3. Get Angry

## Logs
* Client/Server Log: No log
* Crash Log: No Log

## World Information
* World Preset: Default
* Modpack Version world created in: latest

## Client Information
* Modpack Version: latest
* Java Version: 8
* Launcher Used: CurseForge
* Memory Allocated: 8GiB
* Server/LAN/Single Player: Server
* Optifine Installed: Yes
* Shaders Enabled: No

## Server Information
* Java Version:8
* Operating System: Ubuntu 20
* Hoster/Hosting Solution: Rootserver
* Sponge (Non-Vanilla Forge) Server: Forge

https://user-images.githubusercontent.com/67326844/157877349-b69045a8-6285-49fd-830c-a7246b9e62b4.mp4

**Comment by TillVogelsang** [comment]
Ghost items are not modpack-related I guess
