### ISSUE TITLE
Unable to craft dirt

### ISSUE THREAD

**Issue by Yukkun** [DarkPacks/SkyFactory-4#2085]
## Bug Description

Unable to craft dirt, there is no crafting recipe for it at all. I tried different world types too, and the issue exists in all of them

### Did this behavior use to work in the previous version?

Yes, otherwise people wouldn't have played this pack succesfully.

## Steps to Reproduce (for bugs)

1. Create new world (I'm using the one with lava ocean)
2. Chop down tree
3. Struggle crafting dirt because the recipe does not exist

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset: The Floor Is Lava
* Prestige Enabled: Yes
* Modpack Version world created in: 4.2.4
* Additional Content Installed: Nope

## Client Information
* Modpack Version: 4.2.4
* Java Version: 
* Launcher Used: GDLauncher
* Memory Allocated: 8GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by sam-kirby** [comment]
This is a GDLauncher issue similar to DarkPacks/SevTech-Ages#4659.

Please use a different launcher to install this pack; working options are MultiMC, ATLauncher and CurseForge.
