### ISSUE TITLE
Crystals Seeds

### ISSUE THREAD

**Issue by MayorYT** [DarkPacks/SkyFactory-4#2107]
The Quarts Seeds and the other 2 seeds do not work on my single player world don't know why? i have Crystal speed thing and its supposed to be bubbling and growing in the water but nothings happening. The blocks are charged so yah don't know what the prob is but i cant get An Me system on my survival world pls tell me how to fix it, ive been waiting for like 20 mins for it to grow anything and it has not gown at all

**Comment by sam-kirby** [comment]
Nether Quartz seeds can be grown in the enrichment chamber; all other types of quartz are disabled. They are not required to progress with AE2. If you're seeing them in your game then either:
1) you've installed through GDLauncher, which is broken and doesn't install the pack properly
2) you've modified the pack and inadvertently broken the custom recipes
3) something went wrong during pack installation and custom recipes couldn't be loaded.

In any case, the simplest solution is to reinstall the pack using a supported launcher; MultiMC, ATLauncher and Curseforge are all good options.
