### ISSUE TITLE
cada ves que reclamo los puntos de prestigio me regresa al menu y cuando entro al mundo me desaparece construcciones

### ISSUE THREAD

**Issue by fran5754356** [DarkPacks/SkyFactory-4#2110]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by sam-kirby** [comment]
We do not support modified packs.
