### ISSUE TITLE
OreExcavater and Bonsai

### ISSUE THREAD

**Issue by tankietmcpe** [DarkPacks/SkyFactory-4#2120]
I cant use OreExcavater and my bonsai pot after place above the chest it didnt push the item down and the bosai pot still freeze 100%

**Comment by sam-kirby** [comment]
This sounds like you've chosen to play Prestige mode - in this mode you earn points by completing pages of advancements. These points allow you to unlock additional mods or functionality within mods.

Ore excavation is one of the earliest you can unlock, along with hopping bonsai pots (regular bonsai pots don't - and never have - deposit into chests).
