### ISSUE TITLE
Singleplayer/ LAN bug. Unable to use tombstone key on grave.

### ISSUE THREAD

**Issue by Glatis** [DarkPacks/SkyFactory-4#2121]
## Bug Description

The person playing on the server I am hosting via lan is unable to obtain their tombstone. Happened to me once, which I will put in the steps below..

### Did this behavior use to work in the previous version?

not sure

## Steps to Reproduce (for bugs)

1. Die
2. After dying, die again with the key in your inventory.
3. Boom.

## Logs

* Client/Server Log: 
* Crash Log: None

## World Information
* World Preset: Survival, open to LAN, cheats allowed. 
* Prestige Enabled: ??
* Modpack Version world created in: 4.2.4
* Additional Content Installed: Optifine 1.12.2 G4

## Client Information
* Modpack Version: 4.2.4
* Java Version: 1.12.2
* Launcher Used: CurseForge/Minecraft Launcher
* Memory Allocated: 16gb
* Server/LAN/Single Player: LAN
* Optifine Installed: Yes
* Shaders Enabled: No

## Server Information
* Java Version: 
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Crouch whilst standing on top of your grave.
