### ISSUE TITLE
Game crashes on loading the world

### ISSUE THREAD

**Issue by RavMarv** [DarkPacks/SkyFactory-4#2123]
## Bug Description

When the world loads the game crashes with this error message: 
![image](https://user-images.githubusercontent.com/104672026/174437796-6665eaf5-6ce5-4be4-b86d-cfdeba57dd03.png)

### Did this behavior use to work in the previous version?
Nothing similar happened to me before on any version

## Steps to Reproduce (for bugs)
I honestly don't know what caused that

## Logs
* Crash Log: [SkyfactoryCrash.txt](https://github.com/DarkPacks/SkyFactory-4/files/8933537/SkyfactoryCrash.txt)

## World Information
* World Preset: Default 
* Prestige Enabled: Yes
* Modpack Version world created in: Skyfactory 4 - 4.2.4
* Additional Content Installed: None

## Client Information
* Modpack Version: Skyfactory 4 - 4.2.4
* Java Version: 1.8.0_333
* Launcher Used: The normal (and "updated") Minecraft launcher
* Memory Allocated: 8Gb
* Server/LAN/Single Player: Single Player
* Optifine Installed: None
* Shaders Enabled: None

**Comment by sam-kirby** [comment]
Looks like a misbehaving Cyclic Builder - it may be possible to fix this by temporarily turning on `removeErroringTileEntities` in forge's config here: https://github.com/DarkPacks/SkyFactory-4/blob/master/src/config/forge.cfg#L62

Turn it on while the game is shutdown, start the game, load your world and clear up the builder. Stop the game and change the config value back to false.

**Comment by RavMarv** [comment]
Thanks ! but how do you do it ? sorry I don't know much about the files and all that stuff 😅

**Comment by RavMarv** [comment]
I changed it to true and loaded up my world but the game still crashes immediately on load... any more suggestions ?

**Comment by RavMarv** [comment]
> Looks like a misbehaving Cyclic Builder - it may be possible to fix this by temporarily turning on `removeErroringTileEntities` in forge's config here: https://github.com/DarkPacks/SkyFactory-4/blob/master/src/config/forge.cfg#L62
> 
> Turn it on while the game is shutdown, start the game, load your world and clear up the builder. Stop the game and change the config value back to false.

I changed it to true and loaded up my world but the game still crashes immediately on load... any more suggestions ?

**Comment by FR34DB3R** [comment]
well i have the same error but with (IFluxNetwork)
