### ISSUE TITLE
produces unregistered item minecraft:wooden_door

### ISSUE THREAD

**Issue by Slushy-man** [DarkPacks/SkyFactory-4#2142]
I get this error everytime I try to join my skyfactory 4 server I have tried reinstalling the mods and I have the exact same mods on client and server but it won't work
`java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Recipe minecraft:wooden_door (net.minecraft.item.crafting.ShapedRecipes@51c4992e) produces unregistered item minecraft:wooden_door`
![image](https://user-images.githubusercontent.com/62951825/180632535-23036791-372a-4375-9728-186936ed4b04.png)
I need help I have been trying everything

**Comment by sam-kirby** [comment]
This usually indicates that the server configs do not match the client configs; there is more to setting up a server than just checking it has the same mods, please follow the readme included in the server files from Curseforge.
