### ISSUE TITLE
It is Impossible to get Market Without red dye and you can't get red dye 

### ISSUE THREAD

**Issue by laterboi** [DarkPacks/SkyFactory-4#2145]
## here's some information
I would like it if you changed the Market recipe or made so I could get red dye more easily so all people have to worry about is getting emeralds because getting red dye should not take so much of a hassle and the some dyes might require the mystical agriculture essence but I even can't get any inferium essence because there's no possible way to get it

**Comment by sam-kirby** [comment]
Magic Beans are your friend.
