### ISSUE TITLE
The Between Lands

### ISSUE THREAD

**Issue by laterboi** [DarkPacks/SkyFactory-4#2146]
## Context
I would like to recommend that a mod called "The Betweenlands" should be added to the pack because it be really cool and immersive addition and kinda known mod it adds a new creepy and swamp dimension were the underground is darker than before and for people that are brave enough to wander/adventure on

## Mod Details
* [ANGRY PIXEL] The Betweenlands
* [Curseforge The Betweenland Link](https://www.curseforge.com/minecraft/mc-mods/angry-pixel-the-betweenlands-mod)

**Comment by sam-kirby** [comment]
The Betweenlands doesn't really fit with SkyFactory as its world generation is required for it to be completable.

We have included The Betweenlands in other packs, e.g. SevTech Ages, where it is more thematically appropriate.
