### ISSUE TITLE
uhh HELP

### ISSUE THREAD

**Issue by Shakyslime** [DarkPacks/SkyFactory-4#2149]
## Bug Description
GLitched items

### Did this behavior use to work in the previous version?
 i have no clue

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Closing as no information provided.
