### ISSUE TITLE
Item Dupe Using Big Pouch From Tiny Progressions

### ISSUE THREAD

**Issue by MrEggGaming1** [DarkPacks/SkyFactory-4#2161]
## Bug Description

 Using the Big Pouch You Are Able To Dupe Any Item or Block

### Did this behavior use to work in the previous version?

 I Do Not Know Have Not Tested It

## Steps to Reproduce (for bugs)

https://youtu.be/ZBF7riVwHIU
1. Open The Big Pouch
2. Place Block In The Pouch
3. Drop Pouch Without Exiting GUI
4. Take Blocks Out Of GUI
5. Open Pouch
6. Blocks/Items Are Still In The Pouch 

## World Information
* World Preset: Default
* Prestige Enabled: No
* Modpack Version world created in: 4.2.4
* Additional Content Installed: Nothing

## Client Information
* Modpack Version: 4.2.4

## Server Information
* Java Version: 8
* Hoster/Hosting Solution: Aternos

**Comment by TheoCGaming** [comment]
so it looks like I'm not the only one having issues with the local bots getting pissed for no reason.
