### ISSUE TITLE
Advancement Book Wiped and Prestige points system wiped

### ISSUE THREAD

**Issue by KingJay2189** [DarkPacks/SkyFactory-4#2163]
## Bug Description

Opened up the game and all the advancements and prestige points I had were gone.

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version: 4.2.4
* Java Version: 1.12.2
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player: Single Player
* Optifine Installed:
* Shaders Enabled:

**Comment by sam-kirby** [comment]
This is usually indicative of corruption, often caused by a power failure while the game is running or otherwise incorrectly stopping the game. You can restore a backup.

It can also happen when using a cracked launcher due to UUID changes. We offer no support for this.
