### ISSUE TITLE
Blocks do not break

### ISSUE THREAD

**Issue by LinkyMinky** [DarkPacks/SkyFactory-4#2168]
## Bug Description

 when me and my friend are playing the blocks don't break this is a new server btw.

### Did this behavior use to work in the previous version?

 idk

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:Atlauncher
* Memory Allocated:2 gigabytes
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Stop the server and check that `spawn-protection=0` is set in `server.properties`.

Try giving yourself operator status by running `/op <PlayerName>` in the server console.

**Comment by sam-kirby** [comment]
Or just create a new island away from world spawn by following the directions in the multiplayer instructions.

**Comment by LinkyMinky** [comment]
So a couple things first thanks for helping, how do I open the server console?

**Comment by LinkyMinky** [comment]
Also, I just did (spawn-protection=0) .

**Comment by LinkyMinky** [comment]
It did not work.

**Comment by LinkyMinky** [comment]
If it helps this is on a server.
