### ISSUE TITLE
Typo in achievement book

### ISSUE THREAD

**Issue by potato1234x** [DarkPacks/SkyFactory-4#2171]
## Bug Description
Typo in advancement book in the farming tab, sugar daddy achievement has spelled sand as snad

### Did this behavior use to work in the previous version?
Typo is always there

## Steps to Reproduce (for bugs)
look at it

## Logs
no nees

## World Information
no need

## Client Information
literally no need

**Comment by sam-kirby** [comment]
This is not a typo, the advancement wants you to place Snad and not Sand as Snad grows sugarcane fastest.
