### ISSUE TITLE
Dirt amber and Dirt share recipe

### ISSUE THREAD

**Issue by TheDerpu0ne** [DarkPacks/SkyFactory-4#2180]
Can't craft dirt since dirt amber's recipe is prioritised?
![image](https://user-images.githubusercontent.com/88974734/202564936-d130afc1-f9eb-46d8-a00e-66f6dcfd67f0.png)
impossible to progress rn it seems?

**Comment by sam-kirby** [comment]
They are different recipes... Swap your acorns and resin.

![image](https://user-images.githubusercontent.com/23245543/202568338-04610d28-97f0-4593-bf88-b038dd014555.png)
