### ISSUE TITLE
starting server errors with `no awt in java.library.path`

### ISSUE THREAD

**Issue by 1e1001** [DarkPacks/SkyFactory-4#2181]
## Bug Description

Starting the minecraft server errors with `java.lang.UnsatisfiedLinkError: no awt in java.library.path`

### Did this behavior use to work in the previous version?

I have no idea?

## Steps to Reproduce (for bugs)

1. setup a skyfactory 4.2.4 server
2. start it with ServerStart.sh
3. wait
4. it closes with an error

## Logs

* Client/Server Log:N/A
* Crash Log:https://gist.github.com/1e1001/dd295d787629a151e259bcd03cf01fd8

## World Information
* World Preset:N/A
* Prestige Enabled:N/A
* Modpack Version world created in:N/A
* Additional Content Installed:N/A

## Client Information
* Modpack Version:N/A
* Java Version:N/A
* Launcher Used:N/A
* Memory Allocated:N/A
* Server/LAN/Single Player:N/A
* Optifine Installed:N/A
* Shaders Enabled:N/A

## Server Information
* Java Version:openjdk 1.8.0_272
* Operating System:NixOS 22.11pre396557.5857574d459
* Hoster/Hosting Solution:my own computer
* Sponge (Non-Vanilla Forge) Server:no

**Comment by sam-kirby** [comment]
How have you obtained Java 1.8.0_272 on nixOS - according to the package list they provide 1.8.0_322. As I understand it, manually installing programs on nixOS is complicated by the non-standard library search paths, which seems to be the kind of issue you're running into.

**Comment by 1e1001** [comment]
i am using the `jdk8_headless` package

**Comment by sam-kirby** [comment]
This looks like a mod bug, code for handling colours is being loaded on the server. However, the mod in question is no longer updated on 1.12.2, and this isn't an issue on any other Linux distribution encountered so far - whether using headless or graphical packages - so I'm going to approach this as though it is a problem with your setup.

The simplest possible solution is to use `jdk8` instead; the missing library is the abstract window toolkit. In theory a headless version should be present (`libawt_headless.so`) but this might be completely disabled by the `--disable-headful` configure argument. I've looked at Arch and Ubuntu and neither change the way they build the Jdk between headless and graphical variants, just which files get included in the resulting package, so this looks like an important difference.

Looking at the build script, this shouldn't pull in any additional dependencies if you turn off `enableGnome2`. LibX11 already looks to be an input.

**Comment by 1e1001** [comment]
using `jdk8` fixed it, although i swear i've tried that before (maybe it was still using `jdk8_headless`?)
