### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by Keador** [DarkPacks/SkyFactory-4#2185]
After running Install.bat and having a successful install message in the install log, running ServerStart.bat has absolutely no effect. Cmd window pops up then closes and server never starts. There are no logs or crash reports for me to show. Any ideas?

**Comment by sam-kirby** [comment]
You probably have a newer version of Java installed than Forge supports. Forge for 1.12.2 only supports Java 8. If you have Java 8 installed, make sure it appears first on your path.

You can check this by running `java -version` -- Java 8 reports 1.8.

If you need further support with this, Discord is usually the best bet: https://discord.gg/darkosto
