### ISSUE TITLE
getting your stuff from a grave

### ISSUE THREAD

**Issue by Burritopug** [DarkPacks/SkyFactory-4#2188]
## Bug Description

 it wont let me get my stuff when i die

### Did this behavior use to work in the previous version?

 i'm new

## Steps to Reproduce (for bugs)

1. you die 
2. then you click on the grave or hold right click
3.then collect your stuff

i don't get this part
## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by Burritopug** [comment]
https://www.loom.com/share/e6cc778c0c4b42ca8b167311ef482496

**Comment by sam-kirby** [comment]
Stand on top of your grave and crouch (usually bound to `Shift`).
