### ISSUE TITLE
tombstones not opening

### ISSUE THREAD

**Issue by Toaster5** [DarkPacks/SkyFactory-4#2193]
## Bug Description
Unable to open tombstone.

### Did this behavior use to work in the previous version?
I don't know I just downloaded the most recent version which switched the tombstone mod

## Steps to Reproduce (for bugs)
1. Die

## World Information
* World Preset: default
* Prestige Enabled :unknown
* Modpack Version world created in: most recent
* Additional Content Installed: none

## Client Information
* Modpack Version: most recent
* Java Version: most recent
* Launcher Used: cursed forge
* Memory Allocated: unkown
* Server/LAN/Single Player: Single player
* Optifine Installed: no
* Shaders Enabled:no

**Comment by sam-kirby** [comment]
You're probably right clicking the tombstone? Try standing on it and crouching instead.

**Comment by Toaster5** [comment]
Yeah that was it thanks
