### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by siazihong** [DarkPacks/SkyFactory-4#2203]
## Bug Description

Server crashes upon startup.

### Did this behavior use to work in the previous version?

Unknown

## Steps to Reproduce (for bugs)

1.Start server from server host
2.Server crashes
3.

## Logs

* Client/Server Log:
* Crash Log:https://gist.github.com/siazihong/68ad9854a7bfbc19c3cc484affe7fb95

## World Information
* World Preset: Default
* Prestige Enabled: Default
* Modpack Version world created in:4.2.4
* Additional Content Installed:no

## Client Information: 
* Modpack Version:: n/a
* Java Version:: n/a
* Launcher Used:: n/a
* Memory Allocated:: n/a
* Server/LAN/Single Player:: n/a
* Optifine Installed:: n/a
* Shaders Enabled:: n/a

## Server Information
* Java Version:8
* Operating System:w10
* Hoster/Hosting Solution:no
* Sponge (Non-Vanilla Forge) Server:no

**Comment by sam-kirby** [comment]
> Start server from server host
Who is your server host?

Is the `server-ip` variable in server.properties set to a value? If so, leave it blank - i.e. `server-ip=`
