### ISSUE TITLE
veinminer wont work

### ISSUE THREAD

**Issue by harrobe123** [DarkPacks/SkyFactory-4#2204]
## Bug Description

when I load the world it pops up in the chat "veinminer client keybind disabled" i want to use veinminer and it wont work

## Steps to Reproduce (for bugs)

1.![2023-02-07](https://user-images.githubusercontent.com/74988522/217364723-013cda84-a70b-4f81-b1ed-d2ab504a6286.png)
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:sky factory 4
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:electrobobs wizardry, lootbags 

## Client Information
* Modpack Version:
* Java Version:1.12.2
* Launcher Used:ATLauncher
* Memory Allocated:
* Server/LAN/Single Player:single player
* Optifine Installed:no
* Shaders Enabled:no

**Comment by sam-kirby** [comment]
Veinminer is not a part of this pack; any issues you have integrating it are for you to solve.

It is worth noting that Ore Excavation, which fills pretty much the same role, is in the pack already, so it isn't overly clear why you're adding Veinminer in the first place.

**Comment by harrrobe** [comment]
> Veinminer is not a part of this pack; any issues you have integrating it are for you to solve.
> 
> It is worth noting that Ore Excavation, which fills pretty much the same role, is in the pack already, so it isn't overly clear why you're adding Veinminer in the first place.

Sorry I got sky factory after I saw a YouTuber playing it. I saw them using veinminer and tried to too. When I saw mine didn't have the veinminer mod I thought it was an error and installed it. Never of using the mod before I didn't know how to configure it

**Comment by OreExtractionIssue** [comment]
He's RIGHT

**Comment by OreExtractionIssue** [comment]
How did you guys edit the modpack and add something? I can't

**Comment by harrrobe** [comment]
> How did you guys edit the modpack and add something? I can't

depends what launcher you are on

**Comment by OreExtractionIssue** [comment]
Then how did you add the vein miner, or fix the issue?

**Comment by harrrobe** [comment]
> Then how did you add the vein miner, or fix the issue?
> […](#)

again depends what launcher your on, also I didn't fix the issue because veinminer isn't in sky factory so I can't ask the people in sky factory to fix it. it has its own version of veinminer called ore excavator. didn't need it anyway
