### ISSUE TITLE
The grave stones are bugged no matter how much I punch they don't break

### ISSUE THREAD

**Issue by Clone-Number-472** [DarkPacks/SkyFactory-4#2212]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by GhostIsBeHere** [comment]
This is working as intended. Don't punch them, crouch on top of them.
