### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by GabrielTuu** [DarkPacks/SkyFactory-4#2215]
## Bug Description
 
 I can not use any commands and I lost all of my items because I could not use the simple tomb restore command.

### Did this behavior use to work in the previous version?

 I do not know.

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:Yes
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by sam-kirby** [comment]
There is no command to restore simple tombs in this version of Minecraft unfortunately.

**Comment by sam-kirby** [comment]
An alternative solution would be to restore your world from a backup before you died.
