### ISSUE TITLE
SimpleTomb glitch

### ISSUE THREAD

**Issue by SomeGuyWithGithub** [DarkPacks/SkyFactory-4#2219]
For me, SimpleTomb is very glitchy. It takes often takes tens of times to open the tomb, and I can't get my stuff back right now. I usually die on half-slabs, but I died on a crushing tub this time. It just teleports me to the grave whenever I hold down right click. I have also tried removing the crushing tub underneath and replacing it with an oak wood plank, which didn't do anything. I have no idea how to get my stuff back, which is pretty annoying.

**Comment by sam-kirby** [comment]
Stand on top of the grave and crouch.
