### ISSUE TITLE
Cannot claim my item back after died

### ISSUE THREAD

**Issue by killjuicy** [DarkPacks/SkyFactory-4#2232]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by killjuicy** [comment]
I cant claim my item back after died by using keys but its only teleport me to the grave but not giving me the item. i already died 2 times still cant claim my item.

**Comment by sam-kirby** [comment]
Sneak whilst standing on top of your grave to claim your items - the key is only used to get back to the grave.
