### ISSUE TITLE
no crafting recipe for Resin+Acorn recipes in the crafting table

### ISSUE THREAD

**Issue by sebal123** [DarkPacks/SkyFactory-4#2233]
## Bug Description
 When I try to craft Dirt or any other resin+acorn recipe the recipe for the crafting table is missing

### Did this behavior use to work in the previous version?
I did not play any other versions 

## Steps to Reproduce (for bugs)

1. Start the Modpack
2. Create a new world or open any old one
3. open Inventory
4. Search for Resin
5. Rightclick any Random Resin you find
6.no Recipe for the Crafting table

* Client/Server Log: None
* Crash Log: None 

## World Information
* World Preset: Basic (Just tree and dirt)
* Prestige Enabled: No 
* Modpack Version world created in: 4.2.4 
* Additional Content Installed: No 

## Client Information
* Modpack Version: 4.2.4 
* Java Version: 1.8.0_361 
* Launcher Used: Curseforge 
* Memory Allocated: 12288 MB 
* Server/LAN/Single Player: Single Player 
* Optifine Installed: No 
* Shaders Enabled: No

**Comment by sebal123** [comment]
@sam-kirby any tips on how to resolve the problem?

**Comment by sam-kirby** [comment]
Upload `crafttweaker.log` from the modpack folder and I'll take a look at it.

You may receive a faster response on Discord though as I'm about to travel.

You can post your log to https://mclo.gs or similar and link it here or on Discord. Please include your log on discord or here.

https://discord.gg/darkosto

**Comment by sam-kirby** [comment]
Closing as no actionable issue
