### ISSUE TITLE
Simple Storage Network Closing Itself

### ISSUE THREAD

**Issue by APerchal** [DarkPacks/SkyFactory-4#2236]
## Bug Description
Simply put, using specifically a Storage Request Table from the Simple Storage Network mod is annoyingly difficult. For unknown reasons, opening the interface to try and access storage or craft is then closed very quickly after. The menu will close at random intervals, and crafting with this issue is very frustrating because it will take multiple attempts to craft one item.

### Did this behavior use to work in the previous version?
No, unless it just hadn't occurred to me up until something I built over time is what caused the issue. I use the CurseForge client to load and auto update the mod pack. I don't know what mods were updated recently, but this is a recent issue within the past few days after I've been playing the mod for months now.

## Steps to Reproduce (for bugs)
Unfortunately, the best steps are to simply try and use the Storage Request Table. It might close. It might not. Maybe this issue is unique to how my world is built, or maybe it's just from an update to a mod within the hundreds.

For the Logs I tried to paste it in but it was too long to post so I literally have to add it as a separate file. Link to the document:
https://drive.google.com/file/d/1FGJPETzd9Oi-bKKxmjW5wDpFzAxm6oL-/view?usp=sharing

## World Information
* World Preset: Sky Facotry 4 (Default)
* Prestige Enabled: Yes
* Modpack Version world created in: 4.2.4
* Additional Content Installed:

## Client Information
* Modpack Version: 4.2.4
* Java Version: Version 8 Update 371
* Launcher Used: CurseForge
* Memory Allocated: Like 6MB to 7MB using the CurseForge thing that lets you control that
* Server/LAN/Single Player: Single
* Optifine Installed: ngl I don't even know how to
* Shaders Enabled: No

**Comment by APerchal** [comment]
the template literally was pasted into the report so it must have been from formating- I guess I'll re report it???

**Comment by jeff00038** [comment]
did you ever solve this problem? for me, it seemed to happen when adding a second auto crafter to the system
