### ISSUE TITLE
Resource hogs breeding bug

### ISSUE THREAD

**Issue by DevilMayCryIfrit** [DarkPacks/SkyFactory-4#2250]
This may be a bug or on purpose but when breeding resource hogs the industrial foregoing animal feeder gives vanilla pigs and I need to breed them by hand to get the baby resource hog.

**Comment by DevilMayCryIfrit** [comment]
Never mind its just a chance to breed a resource hog.

**Comment by sam-kirby** [comment]
Yeah, no matter how you breed them there is a fifty percent chance of getting an ordinary pig.

https://github.com/Darkhax-Minecraft-Archived/Resource-Hogs/blob/master/src/main/java/net/darkhax/resourcehogs/entity/EntityResourceHog.java#L145
