### ISSUE TITLE
Bibliocraft Painting frames on servers

### ISSUE THREAD

**Issue by MeloMars** [DarkPacks/SkyFactory-4#2259]
I noticed not all items from the mod isn't in the mod pack, like the painting frames where we can put customs pictures. I'd really like to know why its not on there and if it can be on there. Thanks for reading!

**Comment by sam-kirby** [comment]
They were disabled, probably as they could be abused, and we need to stay below the block ID limit.

You can re-enable them by changing the linked configuration entry on both the server and clients while the game isn't running.

https://github.com/DarkPacks/SkyFactory-4/blob/master/src/config/bibliocraft.cfg#L30
