### ISSUE TITLE
crashing every time i open my world

### ISSUE THREAD

**Issue by Plaidevening88** [DarkPacks/SkyFactory-4#2262]
## Bug Description

i have been told by a helper at the curse forge discord server that it was a problem with the mod called topography 

### Did this behavior use to work in the previous version?
 1.12

## Steps to Reproduce (for bugs)

1.open sky factory 4
2. open your world 
3. crashes and puts up an error code of -1

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:1.12
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:1.12
* Launcher Used:curseforge/minecraft
* Memory Allocated:
* Server/LAN/Single Player:yes
* Optifine Installed:no
* Shaders Enabled:no

**Comment by sam-kirby** [comment]
This indicates your world is corrupt; you need to restore a backup:
1) Remove the existing world folder: .\saves\WORLDNAME
2) Create a new folder with the same name as WORLDNAME in .\saves
3) Navigate to .\backups\WORLDNAME and extract the most recent (working) backup to: .\saves\WORLDNAME

If you need further assistance with this, I suggest asking on the Discord server https:.//discord.gg/darkosto

**Comment by Alessio-King** [comment]
Bro stfu and go kys


Am So., 29. Okt. 2023 um 10:35 Uhr schrieb Sam Kirby <
***@***.***>:
