### ISSUE TITLE
Game Crashes with armor forge

### ISSUE THREAD

**Issue by ZashrafTheSniper** [DarkPacks/SkyFactory-4#2263]
## Bug Description

 Opening any armor forge Crashes the game

### Did this behavior use to work in the previous version?

 I played this pack a long time ago and it was not present

## Steps to Reproduce (for bugs)

1. Place an armor forge of any material
2. open it
3. game instantly crashes

## Logs

* Client/Server Log:
* Crash Log: https://pastebin.com/YcDnwLZe

## World Information
* World Preset: Any
* Prestige Enabled: Yes
* Modpack Version world created in: 4.2.4
* Additional Content Installed: None

## Client Information
* Modpack Version: 4.2.4
* Java Version:
* Launcher Used: Curseforge
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed: no
* Shaders Enabled: no

**Comment by sam-kirby** [comment]
This crash seems to be caused by the toggle sneak mod you have added. It looks like there is an update available for this mod that may fix your issue (3.3.4 -> 3.3.6), but I have not tested it.
