### ISSUE TITLE
hey, i tried seeing if there was a solution to this, but im unsure what exactly caused it.

### ISSUE THREAD

**Issue by daltronius27** [DarkPacks/SkyFactory-4#2267]
one day i dropped my keyboard and now the overlay that shows block names and timers or other information such as what resource hogs need vanished. i looked in the setting=s and in all the mod folders but couldn't figure out how to bring it back. please help

**Comment by sam-kirby** [comment]
I think the default hotkey to show and hide this overlay is Numpad 2; you can check in the keybinds area of settings under the `waila` or `hwyla` category.
