### ISSUE TITLE
(4.2.4) [Deep Mob Learning] Data Models Unable to Craft

### ISSUE THREAD

**Issue by Lieren-HuntGhosts** [DarkPacks/SkyFactory-4#2270]
## Bug Description
Now in 4.2.4 which I think was updated yesterday, you cant craft most of the Data Models from Deep Mob Learning mod, only the android and ender dragon, all others' crafting recipes are disabled, although the book still marks them as existant.

### Did this behavior use to work in the previous version?
Yes, the previous version in which this bug was not present was: 4.2.3

## Steps to Reproduce (for bugs)
Just try to craft any Data Model from Deep Mob Learning that its not Android or Ender Dragon, all others have lost the crafting recipe and capability of crafting them.

## Client Information
* Modpack Version: 4.2.4
* Java Version: No clue sry
* Launcher Used: ATLauncher
* Memory Allocated: 5GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No clue, Default modpack in ATLauncher.
* Shaders Enabled: No

**Comment by sam-kirby** [comment]
Why do you think 4.2.4 was updated yesterday? It was released two years ago.

Usually this indicates your gamestage information is corrupted. Specifically you're probably missing `non_pacifist` and maybe `forgiving_void`. You can add these back with the command `/gamestage add <player> <stage>` e.g. `/gamestage add steve-mcminecraft forgiving_void`
