### ISSUE TITLE
Add required libraries for the Wireless Crafting Terminal mod

### ISSUE THREAD

**Issue by tyush** [DarkPacks/SkyFactory-4#2275]
## Context

Many players making an ME system are used to the Wireless Crafting Terminal present in many other modpacks that use AE2, so often included that many believe it was a part of AE2 itself. To add to the confusion, the Wireless Universal Terminal recipe in JEI notes a crafting option for the wireless universal terminal, which is unable to be made since the Wireless Crafting Terminal mod is missing.

A wireless crafting terminal would also provide a justification to the player for the increased cost of an ME system compared to a Simple Storage Network, as right now, it is much more convenient to use a much cheaper Simple Storage Network with the Storage Remote instead of an ME system with a Wireless Terminal, since the Simple Storage Network allows crafting from within the terminal and is much less of an investment.

Adding these three mods would add a usable wireless crafting terminal.

[Wireless Crafting Terminal](https://www.curseforge.com/minecraft/mc-mods/wireless-crafting-terminal)
[AE2 Wireless Terminal Library](https://www.curseforge.com/minecraft/mc-mods/ae2wtlib)
[p455w0rd's Library](https://www.curseforge.com/minecraft/mc-mods/p455w0rds-library)

**Comment by sam-kirby** [comment]
There are no plans to add to this pack at this time; this mod has been requested and rejected previously.
