### ISSUE TITLE
I get a normal map and not the preset map on my server

### ISSUE THREAD

**Issue by TheSkyes2004** [DarkPacks/SkyFactory-4#2280]
## Steps to Reproduce (for bugs)

1.Installed the server pack
2. extracted the files
3. installed using the install.bat
4. started the minecraft-server.jar (the serverstart.bat doesn't work)
5. loaded in and did not spawn in the right world

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
You are launching the vanilla server which must be present for forge to modify; you must arrange for the forge jar to be launched either through the provided launch script or your own.

This requires a 64-bit variant of Java 8 to be installed. The included scripts expect this to be your default Java environment, but if it is not you can edit the script to use the absolute path of the Java runtime binary.

**Comment by TheSkyes2004** [comment]
Do you maybe have a tutorial on how to do it or where can i find to do it correctly?

**Comment by sam-kirby** [comment]
I'm afraid not, but it isn't too hard:

1) Install a 64-bit variant of the latest release of Java 8 (currently 1.8.0_401).
2) Edit the start script to point directly to this version by modifying it as follows:
```diff
--- ServerStart.bat
+++ ServerStart.bat
@@ -5,5 +5,5 @@
 :start_server
 echo Starting Sky Factory 4 Server...
-java -server -Xms%MIN_RAM% -Xmx%MAX_RAM% %JAVA_PARAMETERS% -jar %SERVER_JAR% nogui
+"C:\Program Files\Java\jre-1.8\bin\java.exe" -Xms%MIN_RAM% -Xmx%MAX_RAM% %JAVA_PARAMETERS% -jar %SERVER_JAR% nogui
 exit /B
```
3) Run the modified start script

If you still have problems, you could open a ticket on the Discord server at https://discord.gg/darkosto
