### ISSUE TITLE
Recipe/Progression Breakage with Community Edition of MO

### ISSUE THREAD

**Issue by MonfGeiger** [DarkPacks/SkyFactory-4#2282]
## Bug Description
Trying to replace the Legacy Edition of Matter Overdrive with the Community Edition so i can avoid whatever jank the legacy edition has.

### Did this behavior use to work in the previous version?
n/a

## Steps to Reproduce (for bugs)

1. Download the latest version of the community edition of Matter Overdrive
2. Place it in the mods folder
3. Either delete the legacy edition mod, or (in the case of certain launchers like MultiMC) disable the legacy edition mod

## Logs

* Client/Server Log: https://gist.github.com/MonfGeiger/fd4c513ed3db54eff59a27223749b8e9
* Crash Log:

## World Information
* World Preset: Default (With cheats enabled)
* Prestige Enabled: No
* Modpack Version world created in: 4.2.4
* Additional Content Installed: Matter Overdrive (Community Edition)

## Client Information
* Modpack Version: 4.2.4
* Java Version: jre1.8.0_351 (64-bit)
* Launcher Used: MultiMC
* Memory Allocated: Min: 2 GB, Max 9 GB
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by MonfGeiger** [comment]
Mostly related to the referenced issue below, but i tried my hand at attempting to get it working

#2083

**Comment by sam-kirby** [comment]
You need to make a very small adjustment to the scripts to make this pack work with CE. It looks like, in an effort to reduce block ID usage, the community edition switched to using metadata to distinguish decorative blocks. This means it isn't a drop in replacement.

Whilst testing this, I noticed their implementation of this is buggy; if shift clicking while crafting these items (Floor Tile(s)) then items can end up stacking with incomplete stacks that do not match the colour of the crafting recipe.

https://github.com/DarkPacks/SkyFactory-4/compare/master...matteroverdrive-ce#diff-e78992a898db742f9740fc81c9874070dc0b30fbf7119ea1e8d9ade7736754b8

**Comment by MonfGeiger** [comment]
.....you, absolute, glorious son of a **[REDACTED]**, it worked....i was dead **[REDACTED]** expecting the response i was gonna get was "dude.....this modpack has too much age to change anything about it, there's no real need to update it anymore, let it go", or something along the lines of it, but the recipes look normal again. resin, acorn, the rustic crushing tub doesn't need iron i wouldn't be able to get without cheating some more, etc....

bro.....thank you, like, fr fr, thank you
