### ISSUE TITLE
not authenticated with minecraft.net when trying to launch a skyfactory 4 server

### ISSUE THREAD

**Issue by cameron-80** [DarkPacks/SkyFactory-4#2283]
## Bug Description

not authenticated with minecraft.net

### Did this behavior use to work in the previous version?

unsure

## Steps to Reproduce (for bugs)

try to launch a server on sky factory 4
1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:skyfactory 4
* Additional Content Installed:

## Client Information
* Modpack Version:current
* Java Version:current
* Launcher Used:atlauncher
* Memory Allocated:
* Server/LAN/Single Player:server
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Couple of things could be at issue here;
1) you need to have bought Minecraft; if you haven't done that then you won't get any help with piracy here.
2) if you bought it more than a year or so ago you need to make sure you've migrated your Mojang account to a Microsoft account.
3) if you are sharing your account or launching multiple instances at once then only one person/instance will have a valid token at a time.
4) sometimes Microsoft's servers are offline and this prevents you accessing Minecraft servers until they are available again.

This doesn't sound like an issue with this modpack so I'm closing the issue, but if you need further support you can ask on Discord: https://discord.gg/darkosto
