### ISSUE TITLE
insane tick speed acceleration and getting modifiers randomly

### ISSUE THREAD

**Issue by Albator13000** [DarkPacks/SkyFactory-4#2289]
Me and my friend are doing a duo survival using essential (tell me if I have to move to single player problem because it's supposed to be singleplayers worlds) and my duo sudenly have 307 modifiers on each of their tinker tool and armor, he his the host so maybe that's why it only happend to him but we also have a really high tick speed that won't go down no matter how low we set it. we don't know for old versions but in 4.2.4 with essential there is that

1.No steps since it's happening at random

I don't have the information right now

 ## World Information
* skyfactory 4
* Prestige Enabled
* Modpack Version world created in: 4.2.4
* Additional Content Installed: Essential, akashic tome

 ## Client Information
* Modpack Version: 4.2.4
* Java Version: JDK 22
* Launcher Used: Curseforge
* Memory Allocated: 2G
* Server/LAN/Single Player: Essential singleplayer
* Optifine Installed: no
* Shaders Enabled: no

## Server Information
* Java Version: JDK 22
* Operating System: Unknown
* Hoster/Hosting Solution: none (my friend is the host)
* Sponge (Non-Vanilla Forge) Server: I don't know what this means tho

I am sorry I f my english is not good as I am from france, I just seek help for me and my friends, thank you in advence

**Comment by Albator13000** [comment]
bro where should I ask it's not in there ???

**Comment by sam-kirby** [comment]
The bot closed your issue automatically as you removed sections from the template. It's not telling you to go somewhere else, it's just trying to help us keep the noise down and remove issues that don't include sufficient information to diagnose and fix.

I always review the decisions made by the bot as sometimes it's unneccessarily restrictive. However, in this case there is simply not enough information for me to offer you any help. I've never heard of a case where the tick rate goes above 20 in Minecraft; the game is programmed to wait until the tick has lasted at least 50ms before starting processing the next one. Further, I don't know what setting you are changing to alter the tick speed or whether that could be causing issues.

Additionally, no issue similar to your Tinkers' issue has ever been reported and there is insufficient detail here for me to try and replicate it.
