### ISSUE TITLE
when i load into the server i dont load into a skyblock area 

### ISSUE THREAD

**Issue by natestories** [DarkPacks/SkyFactory-4#2292]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
Closing as no information; most likely explanation is you have set up a vanilla server.

**Comment by natestories** [comment]
how do I take it off vanilla ?

**Comment by sam-kirby** [comment]
I don't know what you've done, so here's a general guide to launching a SF4 server:-
1) Download the [latest server pack](https://www.curseforge.com/minecraft/modpacks/skyfactory-4/files/3565687)
2) Install Java 8 (64-bit). Note that later versions of Java won't work, and the 32-bit version isn't able to address sufficient memory. Where you get Java depends on your OS, on Windows go [here](https://www.java.com/en/download/) and get "Windows Offline (64-bit)". On Linux use your distribution's package manager.
3) Run the pack installer (Install.bat on Windows or Install.sh on other platforms).
4) Change any settings: set the world type, enable prestige if you want, etc. See the [Multiplayer Instructions](https://github.com/DarkPacks/SkyFactory-4/wiki/Multiplayer-Instructions)
5) Run the pack using ServerStart.bat or ServerStart.sh depending on your OS as above.

**Comment by natestories** [comment]
when i do ServerStart.bat it starts command log then closes and eula doesn't pop up either

**Comment by sam-kirby** [comment]
This usually indicates the default version of Java in use is not supported. You can either remove conflicting versions of Java or edit the start script to use Java 8 by absolute path, e.g. for Windows and the latest Oracle release of Java 8 you would change (by right clicking and selecting Edit) ServerStart.bat to match the following:

```batch
@echo off

call settings.bat

:start_server
echo Starting Server
"C:\Program Files\Java\jre-1.8\bin\java.exe" -Xms%MIN_RAM% -Xmx%MAX_RAM% %JAVA_PARAMETERS% -jar %SERVER_JAR% nogui
pause
exit /B

goto start_server
```

**Comment by sam-kirby** [comment]
If you continue to have an issue, please include the output you get when launching the modified start script.
