### ISSUE TITLE
Dirt block can be destroyed

### ISSUE THREAD

**Issue by hungnguyen2912** [DarkPacks/SkyFactory-4#2295]
## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by sam-kirby** [comment]
Issue title describes expected behaviour and no context is provided.
