### ISSUE TITLE
mods missing and world gen not working

### ISSUE THREAD

**Issue by elisathepossum** [DarkPacks/SkyFactory-4#2298]
## Bug Description

 After adding the required data to the server.properties file in the hosting service i'm using (scalacube) it doesn't make the world look like the one chosen, in this case, skiiilands. also modded items/blocks/books/potions are broken and missing textures.

### Did this behavior use to work in the previous version?

 i don't know, this is my first time trying this.

## Steps to Reproduce (for bugs)

1.
2.
3.

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:skiiilands
* Prestige Enabled: no
* Modpack Version world created in: 4.2.4 i think
* Additional Content Installed: none

## Client Information
* Modpack Version:4.2.4
* Java Version:1.12.2
* Launcher Used: curseforge
* Memory Allocated:
* Server/LAN/Single Player: server
* Optifine Installed: no
* Shaders Enabled: no

## Server Information
* Java Version: 1.12.2
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
I think you're probably better off contacting your hosting service to see if they can support you setting up a modded instance. The pack's server files haven't been changed for many years at this point and work fine.
