### ISSUE TITLE
very first achievement not triggering

### ISSUE THREAD

**Issue by superzombie150** [DarkPacks/SkyFactory-4#2301]
## Bug Description

i took a world file and put it onto a different computer and account, when i loaded in the world it was all fine but i had no achievements. the first tree of them depends on the first achievement you get simply by entering the world but i did not get that. 

## Steps to Reproduce (for bugs)

1. copy folder "[world name]" from saves folder
2. paste into saves folder on different computer
3. run Minecraft and open the world

## Possible Solution
this could probably be solved by just using a command to get it back but i don't know the exact name of the advancement to use the command, so if someone could tell me that my problem will likely be solved.

**Comment by sam-kirby** [comment]
The advancement ID is `sf4:age1/root`
