### ISSUE TITLE
Mouse Accelleration

### ISSUE THREAD

**Issue by Anna-Spanner** [DarkPacks/SkyFactory-4#2302]
## Bug Description

 Mouse Acceleration enabled, unable to disable

### Did this behavior use to work in the previous version?

Only used one version, the current one

## Steps to Reproduce (for bugs)

 https://youtu.be/XRMPshvz03g
1. Open any world
2. N/A
3. N/A

## Logs

* Client/Server Log: I'm unable to find a "twitch" folder or "ATLauncher" folder. There are crashlogs in Curseforge but they don't apply since this doesn't crash the game
* 
![image](https://github.com/DarkPacks/SkyFactory-4/assets/162382594/f0435c1c-e110-4061-8419-0c5a56709188)

* Crash Log:

## World Information
* World Preset: Sky Factory Tutorial
* Prestige Enabled: Disabled?
* Modpack Version world created in: latest (4.2.4)
* Additional Content Installed: Optifine (tested without, issue persists)

## Client Information
* Modpack Version: 4.2.4
* Java Version: 1.12.2
* Launcher Used: Minecraft launcher? Opened via Curseforge
* Memory Allocated: Set to 32096 in Curseforge, shows as 28530 when opening the game
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: Yes
* Shaders Enabled: Yes (Seus Renewed V1.0.1)

**Comment by sam-kirby** [comment]
I don't believe Minecraft 1.12.2 uses raw input and so the acceleration profile is the same as that used by the operating system. This means that you have to turn off mouse acceleration in Windows to disable it in the game. To do this press the Windows key and R together to open the Run dialogue and then enter `main.cpl` to open Mouse Properties. Go to the "Pointer Options" tab and uncheck "Enhance pointer precision".

Alternatively, there are some raw mouse input mods available for 1.12.2. I haven't tested any of them, but they may also resolve the issue for you.

**Comment by Nacian0** [comment]
use this 
https://www.curseforge.com/minecraft/mc-mods/raw-input-1-12-2

**Comment by KirinToru** [comment]
u dumb? or u just ignore the problem? THERE IS MOUSE ACCELERATION THAT THIS TRASH MODPACK ADDS. Raw input mod dont help for much cause after like 5 minutes of game mouse just stops working and u need to turn off raw input mod. if u paid someone to make this modpack and now cant contact him to ask why tf there is mouse acceleration so say it and dont hide like "oh i didnt chabge anything, must be ur game or smthing"
