### ISSUE TITLE
Server isn't working right

### ISSUE THREAD

**Issue by MrMcSkeetus** [DarkPacks/SkyFactory-4#2309]
## Bug Description
Everytime I try to load up a self made server it loads me into a normal world. I would almost be fine with it but it also doesn't give me any starter items like the dirt sapling.
I also don't have any achievements available in the achievement screen.

## Steps to Reproduce (for bugs)

1.I make the server
2.I load into server
3.It doesn't work

Honestly don't know how to fill in the rest, if someone could talk with me about it that would be great.
## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* Java Version:
* Launcher Used:
* Memory Allocated:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
You might find the discord server a better place for questions; I'm not exactly sure from this what you mean by not working.

https://discord.gg/darkosto

**Comment by MrMcSkeetus** [comment]
> You might find the discord server a better place for questions; I'm not exactly sure from this what you mean by not working.
> 
> https://discord.gg/darkosto

Thank you for the discord!

**Comment by MrMcSkeetus** [comment]
Well the discord is dead and no one answers so I'm going to reopen my problem here. I updated the entry with a little more detail

**Comment by MrMcSkeetus** [comment]
Figured it out myself
