### ISSUE TITLE
"Failed to launch modpack. An unexpected error occurred."

### ISSUE THREAD

**Issue by BlossomJidoja** [DarkPacks/SkyFactory-4#2321]
How do I solve this problem? I've updated everything. I even tried the Overwolf Support and still didn't help much. Does anyone know how to solve this. Im trying to launch Skyfactory 4 to play on a friends server. None of the other modpacks will work either, they say the same thing.

**Comment by sam-kirby** [comment]
There really isn't a lot of information in the error message you've provided and so I'm largely just guessing, but have you tried closing Curseforge, deleting its `Install` folder (`%USERPROFILE%\Documents\Curseforge\Install`) and then reopening it and asking it to redownload and install the components for Minecraft?

**Comment by BlossomJidoja** [comment]
> There really isn't a lot of information in the error message you've provided and so I'm largely just guessing, but have you tried closing Curseforge, deleting its `Install` folder (`%USERPROFILE%\Documents\Curseforge\Install`) and then reopening it and asking it to redownload and install the components for Minecraft?

I actually solved it, i just had to reinstall curseforge
