### ISSUE TITLE
Several recipes missing  

### ISSUE THREAD

**Issue by Forgefire85722** [DarkPacks/SkyFactory-4#2323]
## Bug Description

 Searching for several different recipes and the don't show up

### Did this behavior use to work in the previous version?

 No the recipes were fine

## Steps to Reproduce (for bugs)

 Several are missing, but I'll just name one
1.Lauch game 
2.Search for "Seared controller"
3.No recipe to be found

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:topography
* Prestige Enabled:yes
* Modpack Version world created in: Skyfactory 4 
* Additional Content Installed:

## Client Information
* Modpack Version:4.2.4
* Java Version:14.23.5.2860
* Launcher Used:2.28.11-1.11.6
* Memory Allocated:1.2GB
* Server/LAN/Single Player:single player
* Optifine Installed:
* Shaders Enabled:

**Comment by Forgefire85722** [comment]
The whole set of mulch is missing too

**Comment by sam-kirby** [comment]
If you want these recipes to be available immediately then you should play without prestige enabled. Else you need to unlock them through the prestige menu (usually bound to P).
