### ISSUE TITLE
ServerStart.bat can't access settings.bat

### ISSUE THREAD

**Issue by Cow-Cat-7** [DarkPacks/SkyFactory-4#2336]
## Bug Description

I installed curseforge and then installed the modpack and server pack. I unzipped the server pack and tried to run ServerStart.bat and it immediately closed itself. I then ran ServerStart.bat through command prompt to see what went wrong and it gave the error:
'settings.bat' is not recognized as an internal or external command,
operable program or batch file.
Starting Sky Factory 4 Server...
Error: Unable to access jarfile nogui"

## Steps to Reproduce (for bugs)

1. run ServerStart.bat

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* All default world information.
* Prestige Enabled:
* Modpack Version world created in:
* Additional Content Installed:

## Client Information
* Modpack Version:
* 4.2.4
* Java Version:
* Version 8 Update 421
* Launcher Used:
* curseforge
* Memory Allocated:
* Server/LAN/Single Player:
* Server
* Optifine Installed:
* No
* Shaders Enabled:
* No

## Server Information
* Java Version:
* Version 8 Update 421
* Operating System:
* Windows
* Hoster/Hosting Solution:
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
When running the script through command prompt you need to ensure your working directory is the extracted server folder or you will receive the quoted error.

That means running the server like:
```bat
cd "C:\Users\user\servers\SkyFactory 4"
.\ServerStart.bat
```
Instead of:
```bat
"C:\Users\user\servers\SkyFactory 4\ServerStart.bat"
```

**Comment by Cow-Cat-7** [comment]
Ah thank you. I now get a different error 
Error: missing \`server' JVM at `C:\Program Files (x86)\Java\jre1.8.0_421\bin\server\jvm.dll'.
Please install or use the JRE or JDK that contains these missing components.

Do I create this manually or is there a very specific version of java I have to install?

**Comment by sam-kirby** [comment]
Two issues here. First is the missing server JVM, which oracle removed from the standard JRE download a while ago. Just remove `-server` from the start script. Second is that you've got a 32-bit version of Java 8 installed, which won't be able to address enough memory to run the server (32-bit processes are limited to 3GB). You need to uninstall this version and install the 64-bit version. On oracle's Java download website this is labelled "Windows Offline (64-bit)"

**Comment by Cow-Cat-7** [comment]
Thank you so much! The server looks like it starts now. Have a nice day!
