### ISSUE TITLE
Prestige not working on one player if they got it before the host 

### ISSUE THREAD

**Issue by Ghost-codery** [DarkPacks/SkyFactory-4#2339]
## Bug Description

it just says "prestige is not enabled in this world" even thought it is enabled for everyone else, and i have achievements that should give me prestige

### Did this behavior use to work in the previous version?

I cant tell

## Steps to Reproduce (for bugs)

1.Make a mutiplayer server
2.Have one player who is not the host achieve any prestige giving achievements before the host gets it and while they are not online
3.Let the host get an achievement that activates prestige
4. Try to open the prestige menu

## Logs

* Client/Server Log:
* Crash Log:

## World Information
* World Preset:
* Prestige Enabled:Yes
* Modpack Version world created in:1.12
* Additional Content Installed:no

## Client Information
* Modpack Version:4,2,4
* Java Version:1.12
* Launcher Used:CursedForge
* Memory Allocated:
* Server/LAN/Single Player:Server
* Optifine Installed:no
* Shaders Enabled:no

## Server Information
* Java Version:1.12
* Operating System:
* Hoster/Hosting Solution:Aternos
* Sponge (Non-Vanilla Forge) Server:

**Comment by sam-kirby** [comment]
I don't think it's possible to use prestige mode as intended on an aternos server as it requires modifying a config file which can't be done on their platform. How are you enabling prestige and are any items actually locked for you?

**Comment by Ghost-codery** [comment]
The host did /prestige force enabled
We fixed the bug by doing it again
