### ISSUE TITLE
Mulch not rendering in bonsai hopper

### ISSUE THREAD

**Issue by darkphan** [DarkPacks/SkyFactory-4#32]
In 0.0.15 black mulch does not render in the bonsai hopper. I have not tested other variations of mulch.

**Comment by Demlou6** [comment]
+1

Adding on that my mulch renders but my trees do not from an imported save. (They still work though.)

**Comment by Demlou6** [comment]
My current .13 save is fine with this, my .15 save is not, and I haven't tried in a new world yet.

I can do that later if it has not been done by then.

**Comment by Demlou6** [comment]
https://gyazo.com/db5e9a0fee104feb35d87ef284e12392

I don't even know anymore....

**Comment by Demlou6** [comment]
This is fixed as far as I can tell.
