### ISSUE TITLE
Cannot view certain crafting recipies in JEI

### ISSUE THREAD

**Issue by LethalBoar70923** [DarkPacks/SkyFactory-4#520]
## Bug Report
Certain crafting recipes (mostly from the deep mob learning mod) cannot be seen in JEI.

## Expected Behaviour
When left clicking an item in JEI, you're given the crafting recipe, unless playing in prestige and the item is locked.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. open JEI
2. search and click on the simulation chamber from deep mob learning (other items are effected however this is used as an example)

## Logs
Server log: https://pastebin.com/kSJXNeNu

## World Information
* Preset: Classic
* Prestige: disabled
* Modpack Version world created in: SkyFactory 4 v4.0.1
* Additional Content Installed: none

## Client Information
* Modpack Version: 4.0.2
* Java Version: 1.8.0_201
* Launcher Used: Twitch
* Memory Allocated: 5 gigabytes
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: 1.8.0_201
* Operating System: Windows 10
* Hoster/Hosting Solution: Self Hosted
* Sponge (Non-Vanilla Forge) Server: No

**Comment by Revv1e** [comment]
Having the same issue, I already know the recipes but when I try to craft them it doesn't work either so... what's up with that?

**Comment by sk2048** [comment]
Run `/gamestage info` and tell me what the output is please?

**Comment by Revv1e** [comment]
forgiving_void, bonsai_trees, parabox

**Comment by hacker104** [comment]
i have the same problem
![image](https://user-images.githubusercontent.com/15986802/56791979-cbd0da00-6808-11e9-936b-32a2c5f94037.png)

**Comment by hacker104** [comment]
but prestige is disabled

**Comment by hacker104** [comment]
for my client
Memory Allocated: 9556MB

**Comment by sk2048** [comment]
Neither of you seem to have the non_pacifist game stage, please try running
`/gamestage add @p non_pacifist`
and let me know if it resolves your issue.

**Comment by hacker104** [comment]
i was solved for me
thanks

**Comment by JustJinxed** [comment]
> Neither of you seem to have the non_pacifist game stage, please try running
> `/gamestage add @p non_pacifist`
> and let me know if it resolves your issue.

I working on the underground caves / non-prestige mode .. came into this issue myself. The fix works, but this is still an ongoing issue for some areas it seems.

**Comment by harrobe123** [comment]
i did this command but i do not have permision

**Comment by harrobe123** [comment]
its the same for me though

**Comment by andrealcantara** [comment]
> its the same for me though

opens LAN and activates cheat mode.
