### ISSUE TITLE
Dupe Bug:  Filing Cabinets and Cyclic Item Transfer Node interaction

### ISSUE THREAD

**Issue by LezChap** [DarkPacks/SkyFactory-4#548]
## Bug Report
Transferring items into a Filing Cabinet from a Cyclic Item Transfer Node (Wireless) keeps the item it's trying to move, while also duping the item into the Filing Cabinet. 
Maybe related to https://github.com/Darkosto/SkyFactory4Issues/issues/495 ?  Unlike the previous report, this does not require a "locked" Filing Cabinet.

## Expected Behaviour
Items should be removed from the Transfer Node when moved into the Filing Cabinet.

## Steps to Reproduce (for bugs)
1. Set up a Filing Cabinet with Files for the item you want to dupe (tested with Wool and String).
2. Get a GPS Marker for the Filing Cabinet.
3. Place a Item Transfer Node, and insert the GPS Marker.
4. Place a single item in the Item Transfer Node.
5. Watch the count QUICKLY increase in the Filing Cabinet, but the item never leaves the Item Transfer Node.

**Comment by LezChap** [comment]
Links to mod's trackers: https://github.com/bafomdad/realfilingcabinet/issues/70 and https://github.com/Lothrazar/Cyclic/issues/1119

**Comment by Mattabase** [comment]
Can confirm

**Comment by Cavensite** [comment]
can confirm as well

**Comment by ThePadawan** [comment]
See #1234 and #1324

**Comment by sam-kirby** [comment]
Closed by dfd8dbb0ee9c226e9d0f0f4becf4bb5da0a5e766
