### ISSUE TITLE
Corail Tombstone engraving not working

### ISSUE THREAD

**Issue by huberer** [DarkPacks/SkyFactory-4#560]
![Untitled1](https://user-images.githubusercontent.com/11410381/56500075-682c7100-64d7-11e9-82a5-931f9e234522.png)

Trying to engrave a crafted tombstone from Corail Tombstone on an anvil from Apotheosis with an iron ingot doesn't work.

It is the only recipe in the game.

Maybe it checks for a vanilla anvil instead of the mod anvil?

**Comment by darkphan** [comment]
I am unable to replicate. You do need to type in the text box to change the inscription, if you do not do that you get the result in your screenshot. [Here](https://i.imgur.com/JLon25Z.png) is the result of my test.

**Comment by Alianaberry** [comment]
Hi I have the same problem with trying to engrave a crafted tombstone from Corail Tombstone.  I feel it may be a conflict with another mod. Our Server has a lot of mods. As you can see it will not let me use and iron ingot but will let me set the name plate without an iron ingot.  How ever once the tome stone is placed, there is nothing on it and reverts back to default name.

Please see screen shots.

![2024-07-18_10 34 44](https://github.com/user-attachments/assets/2ded4a03-49de-49aa-ad08-2289ff1e7303)
![2024-07-18_10 34 52](https://github.com/user-attachments/assets/d9a01b4f-095e-4c10-be4e-91b97899280c)
![2024-07-18_10 35 53](https://github.com/user-attachments/assets/0bc99123-8e9a-4862-9523-539b6b2654c3)
![2024-07-18_10 36 26](https://github.com/user-attachments/assets/21cf317a-d82f-4202-98a9-a97aa724552d)

**Comment by sam-kirby** [comment]
We were forced to remove Corail's Tombstone by the mod author, and as such we no longer support it.
