### ISSUE TITLE
Duping Items in SSN with Filing Cabinets and Hopping Bonsai

### ISSUE THREAD

**Issue by bretterer** [DarkPacks/SkyFactory-4#577]
## Bug Report
When using Simple Storage Networks along side of Filing Cabinets and hopping bonsai pots, When you go to shift click craft an item (tested with iron amber) it will take the full stack from SSN and place it in each item location. After shift clicking to craft, you can take the full stack and put each set back into the SSN network duping the items.

This MAY be a bug inside of SSN itself, and not SF4 config. Thought I would start here though.

## Expected Behaviour
Only have items stack to 64 in each item slot of crafting grid in SSN.   if canceling the craft (clicking the x) do not dupe items.

## Possible Solution
?

## Steps to Reproduce (for bugs)

1. Filing cabinet with iron bonsai tree
2. connect filing cabinet to SSN
3. wait until you have over 2500 items of each item to make iron amber
4. search in JEI from SSN to click iron amber into crafting grid
5. cancel the craft, and it will dupe the items. 
   - ie: you have 1200 acorns in inventory, it will put 1200 acorns in each spot avaialble for craft, cancel the craft, it will put 4800 acorns back into SSN

I have 33 filing cabinets witih bonsai hoppers on each.  folders inside include all drops for that type of tree (each cabinet has a folder for sticks and logs too)

These are in a 9x9 room with SSN storage link cables on each,  The cables are all attached in a loop under them and using the SSN cables, they go into the controller.

![Duping items](https://user-images.githubusercontent.com/1906920/56530529-84a0cb80-6520-11e9-832b-5fb32f89fcda.gif)

## Logs

* Client/Server Log: https://gist.github.com/bretterer/3e63b517cc03777dc02153a73e5f519b
* Crash Log: No Crash Log

## World Information

* Preset: Sky Factory 4

* Prestige:N

* Modpack Version world created in: 4.0.2

* Additional Content Installed: None

## Client Information

* Modpack Version: 4.0.2
* Java Version: build 1.8.0_211-b12
* Launcher Used: Twitch
* Memory Allocated: 8Gb
* Server/LAN/Single Player: Single Player
* Optifine Installed: N
* Shaders Enabled: N

## Server Information
* Java Version: build 1.8.0_211-b12
* Operating System: Mac 10.14.1
* Hoster/Hosting Solution: Single Player
* Sponge (Non-Vanilla Forge) Server:

**Comment by LezChap** [comment]
I couldn't replicate this in my system.  Do you have multiple Filing Cabinets/Bonsai Hopper Pots for Iron Saplings?  Is there a chance there are multiple Inventory Linking Cables going to the Iron Filing Cabinet?  I'm trying to figure out where the differences in our system might be.

**Comment by bretterer** [comment]
Let me get a few screenshots of setup.  Give me a few minutes

**Comment by bretterer** [comment]
Screenshots:

![2019-04-22_20 52 33](https://user-images.githubusercontent.com/1906920/56543933-f25cef80-6540-11e9-8ede-f18211838526.png)
![2019-04-22_20 52 47](https://user-images.githubusercontent.com/1906920/56543934-f25cef80-6540-11e9-98e0-ed7e154ec9f3.png)
![2019-04-22_20 53 00](https://user-images.githubusercontent.com/1906920/56543935-f25cef80-6540-11e9-998b-00d86ab745ed.png)
![2019-04-22_20 53 25](https://user-images.githubusercontent.com/1906920/56543938-f25cef80-6540-11e9-9e38-fca0e6918a19.png)


World download:
https://drive.google.com/file/d/1F0vdoNdQTlJY2qpUyJHnzYeaNj6VPJfV/view?usp=sharing

**Comment by bretterer** [comment]
After a little more investigation, it seems that the block coords the filing cabinets are at are messed up.  If I move the filing cabinet over one block (where another cabinet is not at, it works as expected.  Pretty sure this is not a SF4 issue so I am happy to move this over to, SSN repo?

this now works as expected:
![2019-04-22_21 14 40](https://user-images.githubusercontent.com/1906920/56544854-b11a0f00-6543-11e9-8711-bb97f0d00957.png)

**Comment by bretterer** [comment]
AHH..... The item frame causes this issue!   Will bug in SSN

**Comment by Caldico** [comment]
Maybe try replicating this but with a different storage container. maybe a compact chest? if that still happens then you know its SSN if not you will be better off reporting to both

**Comment by BanhMiDacBiet** [comment]
This issue is caused by the filing cabinet functioning as a locked cabinet due to the filter above it. Item frames work as filters and lock the other items within Simple Storage. 

Within AE2, the item frame above a cabinet works as intended where you can only pull the item above in the frame. 

This is similar to issue #495.
