### ISSUE TITLE
Cannot craft yoyos

### ISSUE THREAD

**Issue by Alexejhero** [DarkPacks/SkyFactory-4#655]
## Bug Report
I cannot craft yoyos. No materials can be used with the yoyo patterns, and the only vanilla crafting recipe I have access to is the cord (8 string) recipe.

## Logs
* Client Log: [latest.log](https://github.com/Darkosto/SkyFactory4Issues/files/3117963/latest.log) (cannot upload to pastebin, says maximum paste limit reached)

## World Information
* Preset: SkyFactory 4
* Prestige: enabled
* Modpack Version world created in: 4.0.2
* Additional Content Installed: [Rebind Narrator](https://minecraft.curseforge.com/projects/rebind-narrator)

## Client Information
* Modpack Version: 4.0.2
* Java Version: 1.8.0_51
* Launcher Used: Twitch
* Memory Allocated: 8040 MB
* Server/LAN/Single Player: singeplayer
* Optifine Installed: no
* Shaders Enabled: no

**Comment by FireJadian** [comment]
From your log:  java.nio.file.NoSuchFileException: C:\Users\user\Twitch\Minecraft\Instances\SkyFactory 4\mods\yoyos_1.12.2-1.2.2.20.jar

Didn't run into this when trying to test this out myself, may have just been an issue with your install?

**Comment by AlexejheroYTB** [comment]
The yoyo book item exists, but there are no materials listed under the "Yoyo materials" section

**Comment by Darkosto** [comment]
I'm unable to replicate this issue. I've gone through and built Yoyos with no problems and confirmed with others that it works for them. Are you still having the issue in the latest modpack update?

**Comment by AlexejheroYTB** [comment]
I still cannot craft yoyos in 4.0.5.

(Unrelated) Aditionally, the chicken feed required for the advancement has no recipe (all 9 crafting slots are empty in JEI)

**Comment by AlexejheroYTB** [comment]
## JEI
![](https://user-images.githubusercontent.com/32238504/57701791-646ab500-7665-11e9-8c15-ab2594c7f31f.png)
## Yoyos and You
![](https://user-images.githubusercontent.com/32238504/57701828-7c423900-7665-11e9-928c-408ac88980ae.png)
## Part Crafter
![](https://user-images.githubusercontent.com/32238504/57701855-8c5a1880-7665-11e9-9ca0-477146fb3906.png)
## Stone Material
![](https://user-images.githubusercontent.com/32238504/57701944-ae539b00-7665-11e9-93d5-ca70837a1668.gif)
## Mod Options
![](https://user-images.githubusercontent.com/32238504/57702191-346fe180-7666-11e9-822e-9779eea6356f.png)
![](https://user-images.githubusercontent.com/32238504/57702210-3df94980-7666-11e9-88f5-c2fcb8f9506e.png)

**Comment by Alexejhero** [comment]
I've decided I no longer care about yoyos
