### ISSUE TITLE
Add localization ability for achievements' titles

### ISSUE THREAD

**Issue by TimeConqueror** [DarkPacks/SkyFactory-4#691]
## Context
So, in the recent update you have added the localization for descriptions of the achievements. 
It would be great if the titles of these achievements could also be localized.

**Comment by sk2048** [comment]
For the moment we can't do this as the titles are used to generate the criteria names for certain advancements that depend on their predecessors, including the prestige mode tab completion advancements.

On servers, this resulted in advancement criteria being displayed as a translation key, which is bad for the end user and frankly looked horrible. And if you had already completed a tab you received free prestige for the reason I'll describe below. In single player, the criteria was semi-localised, however this is unexpected in Vanilla Minecraft, and the name change meant Minecraft considered them separate criteria. The end result of this was that if you changed your language after completing a tab, Minecraft would see these criteria as new and forget about the old ones. The advancement would trigger again every time the language changed. Not good.

We're hoping we can resolve this by changing how criteria are handled in Triumph entirely, but it's probably some way off yet. For the time being, hopefully you can get by with localised descriptions :)
