### ISSUE TITLE
Molten Emerald not going into Gem Cast Tinkers Complement

### ISSUE THREAD

**Issue by majhealth** [DarkPacks/SkyFactory-4#708]
## Bug Report
When using tinkers complement melter with a casting table using a gem cast molten emerald will not fill the cast completely. it pours in only a few mb then stops. No matter how much the faucet is clicked it appears as liquid drops but the cast never fills up past the original point.

## Expected Behaviour
when right clicking the faucet the gem cast should be filled with molten emerald.

## Possible Solution
No Idea...

## Steps to Reproduce (for bugs)
https://youtu.be/urB0jt2qaWg

## Logs
* Client/Server Log:
https://gist.github.com/majhealth/880339c2ffc3188b265c59140a88021a

* Crash Log:

## World Information

* Preset:{"Topography-Preset"\:"ObservaTree"}
* Prestige: Yes
* Modpack Version world created in: 4.0.3
* Additional Content Installed: No additional content installed

## Client Information
* Modpack Version: 4.0.3
* Java Version: V8 Build 201
* Launcher Used: Native/Twitch
* Memory Allocated: 8GB
* Server/LAN/Single Player: Server (Nodecraft)
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: NA
* Operating System: NA
* Hoster/Hosting Solution: Nodecraft
* Sponge (Non-Vanilla Forge) Server: Nope

**Comment by justinrusso** [comment]
Might be the redstone clock passing through the faucet? Its working fine for me.

**Comment by ArkavianX** [comment]
Was lapis also meant for the gem cast too?

**Comment by majhealth** [comment]
I tried removing all of the redstone clocks just to make sure none of them were affecting it. In the video i show there is no redstone clock there for emerald, but there is for the one beside it. Like i said though i tried it with none around. No idea whats causing it. Ill try moving it standalone and see if its still affected.

**Comment by Anaerin** [comment]
I have the same issue, using a client/server setup. Using a hardened fluiduct and servo won't put any Molten Emerald in a gem cast or casting basin (though it's extracted into the fluiduct just fine). Using redstone on a faucet does nothing, thought right-clicking a faucet adds ~6mb to the cast/basin then stops (virtually instant). If you have patience enough to click the many thousand times it takes to fill a gem cast or casting basin, it starts the solidification process and sticks at 99%. As this appears to be the only way to deal with molten emerald, I have a Cyclic Tank full of useless liquid.

**Comment by Darkosto** [comment]
Checked this and it works just fine in my world. I tested with a faucet and pipes. All had no problems pouring the liquid correctly and forming an emerald. If you are still experiencing this bug please create a new issue for version 4.0.8 and above.
