### ISSUE TITLE
[Duping] Filing cabinets and transfer node

### ISSUE THREAD

**Issue by KavinAVS** [DarkPacks/SkyFactory-4#722]
## Bug Report
When using cabinets and transfers nodes items duplicate.

## Expected Behaviour
The items should be transferred from input into the cabinets.

## Possible solution
different mod that does wireless transfer if the problem is with Cyclic.

## Steps to Reproduce (for bugs)
1. place a Item transfer node
2. place a cabinet with a folder for any item.
3. link the transfer node to the cabinet
4. put the same item as in the folder in the transfer node
5. this should start duping the items

* Modpack Version: 4.0.3
* Launcher Used: Twitch
* Memory Allocated: 6gb
* Server/LAN/Single Player: single
* Optifine Installed: Yes
* Shaders Enabled: No

**Comment by LezChap** [comment]
duplicate report: https://github.com/Darkosto/SkyFactory4Issues/issues/548

**Comment by sam-kirby** [comment]
Closed by dfd8dbb0ee9c226e9d0f0f4becf4bb5da0a5e766
