### ISSUE TITLE
Legendary Ranged Androids do not spawn

### ISSUE THREAD

**Issue by Aronicus** [DarkPacks/SkyFactory-4#782]
Hello, I am currently attempting to get one of the legendary weapons that Matter Overdrive adds as part of legendary ranged androids drops, however none seem to spawn in either vanilla spawning mechanics or through animal crops and other such spawning methods in the over world. I am wondering if this is an intended feature or if there is a dimension that they would spawn in.

**Comment by Gavin123-code** [comment]
Im having this issue with FTB revelation that i added matter overdrive to they spawn but its  like IMPOSSIBLE to get their parts And since I basically play a creative Minecraft world the true question for me at least is how do I get legendary range android parts
