### ISSUE TITLE
[Suggeston] Sound Device Options

### ISSUE THREAD

**Issue by cookta2012** [DarkPacks/SkyFactory-4#785]
## Context

This is more of a quality of life mod that I found please consider. It adds the ability to switch the output device of sound without a texture reload.

## Mod Details
* Name: Sound Device Options
* CurseForge Link: https://minecraft.curseforge.com/projects/more-sound-config

**Comment by Vercalos** [comment]
Huh.  I've never noticed such an issue..  I just plug/unplug my headphones, and my computer switches audio outputs accordingly

**Comment by cookta2012** [comment]
Bluetooth Headphones, or wireless usb ones
