### ISSUE TITLE
"Chest-Slab meets Wrench"-Bug

### ISSUE THREAD

**Issue by Hedrauta** [DarkPacks/SkyFactory-4#816]
## Bug Report

Did hit my Chest-Slab with the Thermal-Foundation-Wrench. Chest rotated, looked into the chest itself, and was not amused, that it went empty. ( idc the inventory... it's just..... frustating 😉 )

## Expected Behaviour

Chest does rotate and keep the items.

## Possible Solution

No idea... i'm not a programmer ;)

## Steps to Reproduce (for bugs)

1. Place a Chest-Slab from "Slab machines" on the lower half ( upper tested: same issue ) and place some items in it
2. Hit the Slab with a Wrench from "Thermal Foundations" to rotate it.
3. Look inside and get happy with an empty Chest Slab 😄 

## Logs

* Client/Server Log:
As the log exceeds the 512kB-Limit, i can't upload it to Pastebin and i'm not experienced in gist, so i picked my cloud for that ;)
https://cloud.fphst.de/index.php/s/aDfaqnzknzNkpLc
PS: i can't say, when it happened "excactly" ... but it had to beween 5 and 7 ;) sorry for that lazy time ;) didnt watched the clock when it happened.

## World Information

* Preset: SkyFactory4

* Prestige: Nope

* Modpack Version world created in: 4.0.2 (updated to 4.0.3)

* Additional Content Installed: None ( Changed Stamina-usage on ore-excavation to 0 )

## Client Information

* Modpack Version: 4.0.3
* Java Version: 1.8.211
* Launcher Used: Yes
* Memory Allocated: 8GB
* Server/LAN/Single Player: MP, dedicated Root, created with AMP (Cubecoders.com)
* Optifine Installed: doesnt work, crash on startup, i don't really care 😉 
* Shaders Enabled: nah

## Server Information
* Java Version: 1.8.211
* Operating System: Windows Server 2016 v1607
* Hoster/Hosting Solution: Cubecoders AMP-Webpanel
* Sponge (Non-Vanilla Forge) Server: Sponge works with forge?

**Comment by Mrbysco** [comment]
Can this be reproduced without Sponge? As sponge is known to cause issues with Slab machines

**Comment by Hedrauta** [comment]
> Can this be reproduced without Sponge? As sponge is known to cause issues with Slab machines

did you read my last line? i didn't even know, that sponge works on FML 🙄

**Comment by Hedrauta** [comment]
as i explained in my report: Classic FML-Server... no additional files or mods... AMP is just an extended control-panel

**Comment by Mrbysco** [comment]
Was my mistake as I saw `org.spongepowered.asm.launch.MixinTweaker` mentioned in the log but that appeared to just be the mixin that malisiscore uses.

**Comment by Hedrauta** [comment]
for better view: my settings from the panel:
https://i.imgur.com/nAGjrVG.png

**Comment by Mrbysco** [comment]
Will see what I can do. I have no clue why the chests even respond to the wrench. (They shouldn't)

**Comment by Hedrauta** [comment]
;) just take your time... i'm building the AE2-ME-System right now  ;) no need for chest then anymore 😄

**Comment by vadis365** [comment]
#732 is the same thing.

I have no idea if the TE's code has this - but it will fix issues with inventories and NBT being reset when the TE is wrenched:

@Override public boolean shouldRefresh(World world, BlockPos pos, IBlockState oldState, IBlockState newState) { return oldState.getBlock() != newState.getBlock();
}

**Comment by Mrbysco** [comment]
I've fixed this in 1.0.6 https://github.com/Mrbysco/Slab-Machines/commit/be2343ce45692d55c0f49980cdc57ea8b1570474
