### ISSUE TITLE
2 Nuclearcraft fusion bugs/issues

### ISSUE THREAD

**Issue by Uriah-Heep** [DarkPacks/SkyFactory-4#832]
## Bug Report
Surprised to not see anything on the tracker so I may just be dense... Advancement says to make a 24X24X24 Nuclearcraft fusion reactor which they can only be made in odd sizes since the connectors have to go out from the core in equal lengths, built and operated a max size 24 toroid reactor and nothing registered. The other fusion advancement requires to generate at least 3.333 million RF/Tick and have had the reactor to about 3.5 million on a deuterium/tritium combo fuel and that advancement does not trigger either.

## Possible Solution
Change advancement text to state a 24 toroid fusion reactor and trigger the first advancement (Go Big or Go Home) when the reactor is operating and the UI is accessed, trigger the second advancement (Third Time's the Charm) when the reactor is generating over 3.33 million rf/tick and the UI is opened.

## Steps to Reproduce (for bugs)

1. Read the text for the advancement for a 24x24x24 Nuclearcraft fusion reactor.
2. Go insane scouring online how to build such a thing
3. Give up and try building a max size 24 toroid reactor
4. Pull out remaining hair when quest does not trigger
5. Give up and use your shiny new reactor to fulfill the power generation quest
6. Quietly curl up in a ball and cry to yourself when that fails to work as well
7. Add bug report to issue tracker

## Logs

* Client/Server Log:
* Crash Log:

## World Information

* Preset: Observatree

* Prestige: No

* Modpack Version world created in: 4.0.1

* Additional Content Installed: none

## Client Information

* Modpack Version: 4.0.3
* Java Version: Java 8 update 211
* Launcher Used: Twitch
* Memory Allocated: 8G
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: Java 8 Update 211
* Operating System: Windows 10
* Hoster/Hosting Solution: in home dedicated box
* Sponge (Non-Vanilla Forge) Server:

**Comment by Uriah-Heep** [comment]
Never mind, I figured out you have to right click on the bottom center block of the core from underneath... both of the achievements triggered now. Something more in the description to note this would be nice and the description of the fusion reactor dimensions still needs to change...

**Comment by kbigliar** [comment]
You can build a 25 toroid reactor. So why does it have to be a "max 24 toroid" reactor for the quest to be completed? Also, the power generation quest doesn't want to work even with the workaround of clicking the bottom middle block on the 25 toroid reactor core.

**Comment by dtroitskiy** [comment]
Worked for me after right-clicking fusion core from underneath, but yeah, this is definitely weird, as well as incorrect advancement description text. +1 to changing it into "24 toroid size reactor".
