### ISSUE TITLE
Pills extremely hard to make

### ISSUE THREAD

**Issue by Kekstastisch** [DarkPacks/SkyFactory-4#845]
## Context

Make the matter overdrive pills craftable with NuclearCrafts Lithium Dust

Else you would need a lot of mashines to get the pill

**Comment by darkphan** [comment]
Honestly, the machines are not that hard to make, and the red pill shouldn't be something super easy to get.

**Comment by LeSwede** [comment]
Yeah I think its fine as is.

**Comment by dsielert** [comment]
its not even obtainable in the recent version .. theres no recipie and running lithium trough the mekanism machines gives you the nuclearcraft stuff

**Comment by sk2048** [comment]
@dsielert fixed for next release, but please don't hijack other issues in future - that should have been its own issue.

**Comment by Darkosto** [comment]
Fixed in 4.0.7, now available in Beta.
