### ISSUE TITLE
Compact HuntingDimension spawn location is inside the bedrock and you die

### ISSUE THREAD

**Issue by cpw** [DarkPacks/SkyFactory-4#847]
## Bug Report

When using the cake for hunting dimension from a compact machine world, you spawn inside the bedrock surrounding the space, rather than in the space, and therefore suffocate. Respawning after death puts you on top of the world (see #409).

![2019-05-05_11 40 22](https://user-images.githubusercontent.com/1217211/57197964-49989200-6f3b-11e9-9093-f6a550e17199.png)

## Expected Behaviour

I would hope to go into the dimension and not die.
## Possible Solution

Probably need to move the spawn location up a few blocks -it's unclear where I spawned in, but it was clearly well below the floor.

## Steps to Reproduce (for bugs)

1. Make the hunting dimension cake in a compact sky world.
2. Use it.

## World Information

* Preset: CompactSky

* Prestige: No

* Modpack Version world created in: 4.0.1

* Additional Content Installed: None

## Client Information

* Modpack Version: 4.0.5
* Java Version: j8u201
* Launcher Used: MultiMC
* Memory Allocated: 10G
* Server/LAN/Single Player: Single
* Optifine Installed: no
* Shaders Enabled: no

**Comment by cpw** [comment]
Update: the spawn location persists and you will die if you use the cake again, it's not a first time only thing.. Here is where you spawn.

![2019-05-05_13 45 22](https://user-images.githubusercontent.com/1217211/57198017-1a365500-6f3c-11e9-8cda-013b77a365b7.png)

**Comment by sk2048** [comment]
Hi, in 4.0.5 the hunting dimension and lost cities compact machines dimensions were expanded. This is not working as intended on existing worlds (see #846)

Was this a world where you had previously visited the hunting dimension or was this your first visit?

**Comment by cpw** [comment]
First visit..
