### ISSUE TITLE
Getting to an End City or Finding Elytra in 

### ISSUE THREAD

**Issue by RudiHansen** [DarkPacks/SkyFactory-4#863]
## Bug Report
It does not seem possible to get an Elytra if you are playing on the Stone Factory map.

I can get to the end, but there are no portals to the End City like if you play on a normal map.
And there is also no Final Portal, so resummoning the Dragon seems to not be an option.

So what's the deal here?

I did try to go into creative and oreescavate most of the end stones in a rather big area, just to check for end portals, but found no ones.

## Expected Behaviour
That I could get an Elytra in some way.

## World Information

* Preset: Stone Factory

* Prestige: Yes

* Modpack Version world created in: Hmm actually not 100% sure but think its 4.0.3

* Additional Content Installed:

## Client Information

* Modpack Version: 4.0.5
* Java Version: 1.8.0_51
* Launcher Used: Twitch
* Memory Allocated: 3500
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by RudiHansen** [comment]
Am I not going to get any help on this issue at all?????

**Comment by sk2048** [comment]
I'm not overly sure what kind of help you are expecting - you've flagged a specific issue with the pack (for which we are grateful); that the elytra are unobtainable on certain presets. Either a recipe will be added to make them obtainable or the Stone Factory preset will be altered so the advancements no longer require you to obtain one.

Until that is done, the issue remains. You personally are able to use commands to either obtain the advancement or give yourself elytra. The former would be 

`/advancement grant @p only sf4:age_exploration/elyta`

The latter follows a similar format to the below:

`/give @p virtue:patience`

but I don't know the Elytra's resource location off the top of my head, and wouldn't want to give you false information.

**Comment by RudiHansen** [comment]
Hi sk2048, well something like you just said, is good enough for me.
I probably misunderstood the system here, since I got no feedback at all on the issue I just assumed it was not picked up.

Thanks for your fast reply.

**Comment by Wolf68k** [comment]
It's not just Stone Factory that has this issue. CompactSky has it too, only worse since there's no where to go.

**Comment by Darkosto** [comment]
Fixed in 4.0.7, currently available as beta.
