### ISSUE TITLE
Chunk being "chunkloaded" for no reason

### ISSUE THREAD

**Issue by ApolloMCC** [DarkPacks/SkyFactory-4#869]
I am hosting skyfactory 4 and some chunks are being chunkloaded and they ignore the ticket system. I think they might be phantom chunkloading. 

Here's a photo of the tile entities and entities https://pasteboard.co/IdxgLhY.png

I've also noticed my clear lag plugin clearing items, in chunks that are not populated. 

I've used profiles that check if something chunkloads a chunk and they cannot find anything, I even turned everything to 0 in forgechunkloading. 

* Modpack Version world created in: 4.0.1

## Server Information
* Java Version: 8
* Operating System: UBUNTU
* Sponge (Non-Vanilla Forge) Server: sponge

**Comment by DerSoftwerker** [comment]
Have a similar issue on a forge server, one block that is causing it for sure is the cauldron - but there are more.

https://github.com/Darkosto/SkyFactory4Issues/issues/887

**Comment by Orichlol** [comment]
We seem to be experiencing this issue right now on a 4.2.0 community server.

**Comment by sam-kirby** [comment]
The cauldron issue was resolved in 4.2.0, if you have information about what other blocks may be causing chunks to stay loaded then please open a new issue.
