### ISSUE TITLE
Cant make sap

### ISSUE THREAD

**Issue by Arkhorse** [DarkPacks/SkyFactory-4#973]
## Bug Report

Sap doesnt seem to have a recipe. Need it to progress.
## Expected Behaviour

Needs recipe.
## Possible Solution

Add recipe to JEI
## Steps to Reproduce (for bugs)

1. Open JEI
2. Search for "Sap"
3. Right click it
4. No recipe

## Logs

* Client/Server Log: N/A
* Crash Log: N/A

## World Information

* Preset: Observetree

* Prestige: no

* Modpack Version world created in: 4.0.5

* Additional Content Installed: None

## Client Information

* Modpack Version: 4.0.5
* Java Version: yes
* Launcher Used: MultiMC
* Memory Allocated: 6GB
* Server/LAN/Single Player: Server (Local, PC setting behind me)
* Optifine Installed: No
* Shaders Enabled: No

## Server Information
* Java Version: 1.8.0_191
* Operating System: Ubuntu
* Hoster/Hosting Solution: N/A
* Sponge (Non-Vanilla Forge) Server: No

**Comment by woshikie** [comment]
Isn't the default hotkey for viewing recipe "R"? 
If I'm not wrong, right-click is used for view "Usage"

**Comment by Sabster** [comment]
It works in windows...  (And right click is usage - left click is recipe...)

**Comment by Arkhorse** [comment]
Recipe is right click for me. I might have changed the defaults a long time ago, and maybe MultiMC carries it over?

The recipe only shows the fact that you can get the other acorn out of it. Its not clear that you get sap out of the same action.

**Comment by Darkosto** [comment]
Sap has a recipe and is already in JEI.
