### ISSUE TITLE
Activating Ghast Trap does not trigger Advancement

### ISSUE THREAD

**Issue by mkleiman312** [DarkPacks/SkyFactory-4#995]
## Bug Report
SF4 4.0.5. Activating the Ghast Trap does not trigger the associated Twilight Forest advancement.  Tested (a) activation alone, (b) activation that captures the Ur-Ghast, and (c) activation that captures the Ur-Ghast and applies the killing damage. In all tests, the trap was fully empowered before redstone activation.

## Expected Behaviour
Advancement (twilightforest:ghast_trap) should trigger upon any successful activation of the Ghast Trap.

## Possible Solution
Added:
 "twilightforest:ghast_trap": {
    "criteria": {
      "activate_ghast_trap": "xxxx-xx-xx xx:xx:xx +xxx"
    },
    "done": true
to the Advancement json file.

## Steps to Reproduce (for bugs)
See bug description.

## Logs
Will upload upon request.

## World Information

* Preset: SkyFactory4 (default)

* Prestige: Yes

* Modpack Version world created in: 4.0.5

* Additional Content Installed: n/a

**Comment by jkhazi** [comment]
I completed this advancement first try so there must be something wrong on your end.

**Comment by mkleiman312** [comment]
> I completed this advancement first try so there must be something wrong on your end.

Did you do so in SF4 4.0.5?

**Comment by jkhazi** [comment]
Yeah, it was about 4 hours ago

**Comment by mkleiman312** [comment]
"twilightforest:ghast_trap" didn't even appear in my advancement json file as false, until I added the entry manually. Perhaps it was user-error, or a one-off.

**Comment by jkhazi** [comment]
In my experience advancements break after playing a long time, to get it rolling i have to relog, maybe yours had an issue like this when you did the knight phantoms? I have no other idea.

**Comment by bunchamino** [comment]
I 'm complete this advancements. !! before boss spawn (don't  move to center of area)
1. you must kill ghast near ghast trap still ghast trap ready to activate (loud and very smoke upper trap)
2. when trap ready you just stand on pressure plate for activate.
3. then go to center area and kill urGhast boss.
